devices ko convention  trader serialization
downstream refs:
90f0868 823040a ffe6b85 8e1257f 988fa8f 9965162 f078ef3 448e0c0 fdaadbe 98d3226 3e0d475 e26386a 797494e 62f8203 527fa73 0014b59 4c70597 000fda0 7a9cee7 1fcf222 a3db916 6b75335 d3a1b5e 386bd84 9dd31f2 330b05b 9c514a8 bba9f00 cadaa16 caf5825 8048f3e 4738546 e724dc3 120ebc5 90409b9 a31b33d b97ff0a c342188 de8af1e 21d937c 0543a22 2c5725c 8acf721 860cf99 b130806 e66fa6a 09a41bf 709fbc5 03f3870 6a38f48 74d1bca 01e2342 d01cd23 c8b2eda 11d7f4e e1c68bb e95f388 409677e d9f9aa2 6adb09e 64ff516 7bc9875 a42defa 19941e7 afeee5e be4bd74 82ebdbb e090896 116a940 bbb850f f12f605 74e7650 f9c1a05 642ce03 277570a 43909c4

diff --git a/core0/us/android/bin/sign_apk.in b/core0/us/android/bin/sign_apk.in
--- a/core0/us/android/bin/sign_apk.in
+++ b/core0/us/android/bin/sign_apk.in
@@ -25,14 +25,20 @@
 us="##str3##"
 
 inst=0
-if [ "_$1" == "_--install" ]; then
+if [[ "_$1" == "_--install" ]]; then
   inst=1
 fi
 
 if [[ ! -f /var/$us/ush_config ]]; then
     echo "KO 87036 /var/$us/ush_config must exist with envvar keyroot"
+    exit 1
 fi
 . /var/$us/ush_config
+
+if [[ "_$keyroot" == "_" ]]; then
+    echo "KO 87037 keyroot must be defined. keyroot=<directory>"
+    exit 1
+fi
 
 jarsigner="jarsigner"
 keytool="keytool"
@@ -44,7 +50,7 @@ fi
 function sign_apks {
     echo "signing APKs"
     ks=$1
-    for file in `find . -name "*-unsigned.apk"`; do
+    for file in `find app/build/outputs/apk -name "*-unsigned.apk"`; do
         echo "found unsigned apk: $file"
         newfile=`echo $file | sed "s/-unsigned//"`
         echo "using $pass"
@@ -57,7 +63,31 @@ function sign_apks {
         mv $file $newfile
         echo "signature $newfile"
         echo "$file -> $newfile"
-        $keytool -list -printcert -jarfile $newfile
+        $keytool -printcert -jarfile $newfile
+    done
+}
+
+function sign_bundles {
+    echo "signing bundles"
+    ks=$1
+    for file in `find app/build/outputs/bundle -name "*.aab"`; do
+        cert=`$keytool -printcert -jarfile $file`
+        if [[ "_$cert" != "_Not a signed jar file" ]]; then
+            echo "$file is already signed"
+            continue
+        fi
+        echo "found unsigned bundle: $file"
+        newfile=`echo $file | sed "s/-unsigned//"`
+        echo "using $pass"
+#        $jarsigner -verbose -keystore $ks $file distr <<< "$pass"
+        $jarsigner -keystore $ks $file distr <<< "$pass"
+        if [ $? -ne 0 ]; then
+            echo "signer failed" >2
+            exit 1
+        fi
+        echo "signature $newfile"
+        echo "$file -> $newfile"
+        $keytool -printcert -jarfile $file
     done
 }
 
@@ -66,19 +96,22 @@ gpg_passphrase_file="$keyroot/.gnupg/passphrase"
 gpg="gpg --homedir $keyroot/.gnupg"
 pass=`cat $gpg_passphrase_file`
 
-sign_apks $keyroot/keystore.jks
-
-echo "in "`pwd`
-find . -type f -name "*.apk"
-if [ $inst -eq 1 ]; then
-	echo "waiting for device"
-	adb wait-for-device
-	echo "installing"
-	adb install `find . -type f -name "*.apk"`
-#	reset
-#	adb logcat | grep System.out
-
+ks=$keyroot/cbs/$us/keystore.jks
+echo "using keystore at $ks in "`pwd`
+if [[ -d app/build/outputs/apk ]]; then
+    sign_apks $ks
+    echo "APKs:"
+    find app/build/outputs/apk -type f -name "*.apk"
+    if [[ $inst -eq 1 ]]; then
+        echo "waiting for device"
+        adb wait-for-device
+        echo "installing"
+        adb install `find . -type f -name "*.apk"`
+    fi
+fi
+if [[ -d app/build/outputs/bundle ]]; then
+    sign_bundles $ks
+    echo "Bundles:"
+    find app/build/outputs/bundle -type f -name "*.aab"
 fi
 exit 0
-
-
diff --git a/core1/bin/10_make_build_jobs b/core1/bin/10_make_build_jobs
--- a/core1/bin/10_make_build_jobs
+++ b/core1/bin/10_make_build_jobs
@@ -32,6 +32,7 @@ else
 	echo "KO 8585 Missing .cbs/config."
 	exit 1
 fi
+brands=`realpath $brands`
 
 abrands=`find $brands -maxdepth 1 -mindepth 1 -type d | sed "s~$brands/~~" | xargs`
 
@@ -40,7 +41,9 @@ function help {
 	echo "existing brands: $abrands"
 	echo "--release implies --without-logs --without-counters --without-connlog"
 	echo "--debug implies --with-logs --with-counters --with-connlog"
-    echo "--test. build for tunning tests"
+    echo "--test      build for tunning tests"
+    echo "--batch     no interaction with user"
+    echo "--only_deps  no core0"
 	echo "Positional options. They override the setting left by previously appearing options."
 }
 
@@ -55,8 +58,10 @@ counters=0
 connlog=0
 bjdir="build_jobs"
 test=0
-ignore_cache=0
+ignore_cache=0 
 fcgi=0
+let batch=0
+let only_deps=0
 
 while [[ true ]]; do
     opt=$1
@@ -131,6 +136,12 @@ while [[ true ]]; do
         shift
         echo "output flag -o=$bjdir"
         continue
+    elif [[ "_$opt" == "_--batch" ]]; then
+        let batch=1
+        continue
+    elif [[ "_$opt" == "_--only_deps" ]]; then
+        let only_deps=1
+        continue
     elif [[ _$opt == _-* ]]; then
         echo "KO 60594 Invalid flag $opt"
         help
@@ -170,8 +181,10 @@ echo ""
 echo "Output:"
 echo "  bjdir=$bjdir"
 echo "--------------------------------------"
-echo "yes?"
-read x
+if [[ $batch -eq 0 ]]; then
+    echo "yes?"
+    read x
+fi
 
 hash=""
 
@@ -216,14 +229,14 @@ function make_build_job {
     brand=$1
     dryrun=$2
     echo "make_build_job $brand $dryrun"
-    if [ "_$dryrun" != "_" ]; then
+    if [[ "_$dryrun" != "_" ]]; then
     	echo "brand $brand"
     	return
     fi
     set +e
     donebrand=`cat /tmp/done_brands | grep $brand`
     set -e
-    if [ "_$donebrand" == "_$brand" ]; then
+    if [[ "_$donebrand" == "_$brand" ]]; then
         echo "brand $brand already done"
         return;
     fi
@@ -406,9 +419,13 @@ function ec_sources {
     #libsecp256k1
     echo "git clone -q ${secp256k1_git}"
     git clone -q ${secp256k1_git}
+    if [[ $? -ne 0 ]]; then
+        echo "KO 50445 Cannot clone ${secp256k1_git}."
+        exit 1
+    fi        
     pushd secp256k1 > /dev/null
         git checkout -q $secp256k1_hash
-        rm .git -r
+        rm .git -rf
     popd > /dev/null
 }
 
@@ -428,9 +445,13 @@ function fcgi_sources {
     #fcgi
     echo "git clone -q ${fcgi_git} fastcgi++"
     git clone -q ${fcgi_git} fastcgi++
+    if [[ $? -ne 0 ]]; then
+        echo "KO 50445 Cannot clone ${fcgi_git}."
+        exit 1
+    fi        
     pushd fastcgi++
         git checkout -q $fcgi_hash
-        rm .git -r
+        rm .git -rf
     popd
 }
 
@@ -452,6 +473,10 @@ function make_build_jobs {
         pushd "$bjdir"/fcgi_src > /dev/null
             fcgi_sources
         popd  > /dev/null
+    fi
+    if [[ $only_deps -eq 1 ]]; then
+        echo "skipping core0"
+        return
     fi
     mkdir -p $bjdir/$branch
     pushd "$bjdir" > /dev/null
diff --git a/core1/bin/80_deploy_blobs b/core1/bin/80_deploy_blobs
--- a/core1/bin/80_deploy_blobs
+++ b/core1/bin/80_deploy_blobs
@@ -41,7 +41,7 @@ grootkey=`ush show_groot_key`
 ssh="ssh -i ${grootkey}"
 scp="scp -i ${grootkey}"
 
-rm -f /tmp/msg1091
+#rm -f /tmp/msg1091
 
 set -x
 
@@ -80,14 +80,19 @@ for blob in `find blobs -type f -name "*.tzst"`; do
     if [[ $? -ne 0 ]]; then
         exit 1
     fi
-    echo "$node:/var/$brand/blob; ($ssh -p $port $ip) exec su gov; bin/up_blobs" >> /tmp/msg1091
+#    echo "$node:/var/$brand/blob; ($ssh -p $port $ip) exec su gov; bin/up_blobs" >> /tmp/msg1091
+    $ssh -p $port gov@$ip bin/up_blobs
+    if [[ $? -ne 0 ]]; then
+        echo "KO 88791 cannot ssh to BDN brand $brand"
+        exit 1
+    fi
 done
 
 set +x
 
-echo "Blobs have been delivered to BDPs:"
-echo "Next steps:"
-cat /tmp/msg1091
-rm -f /tmp/msg1091
+echo "Blobs have been delivered to BDPs, and they have uploaded the blob to blockchain."
+#echo "Next steps:"
+#cat /tmp/msg1091
+#rm -f /tmp/msg1091
 
 exit 0
