wallet_connection crafter/decoder  tft
downstream refs:
567fbd67 e4739db0 11fc6dad 8a2c54a4 4b7571fa 509950fc e1f0a003 0779acaf 64973c90 75d9cacc 54653cae d38afbe9 c7636333 58a8fe30 67e40137 4b8008a3 cd74d140 f0845615 d04acbd7 65bcc910 2801f868 bd674f6c 5d6c8e8f 052bb0e2 291fef79 4541694d d4ec69f4 29f4828d 7db72c72 204c960b 42b814a3 2c163ab2 b012e27e ed249f12 65a71049 72bf6eb0 67177ade 6453e580 9faeb723 4ea2981f 3bd91f01 ff45bbb7 7ddab374 91a17341 3dfc1cb5 c2dd6464 f0e786ac

diff --git a/core0/us/android/bin/sign_apk.in b/core0/us/android/bin/sign_apk.in
--- a/core0/us/android/bin/sign_apk.in
+++ b/core0/us/android/bin/sign_apk.in
@@ -24,19 +24,49 @@
 
 us="##str3##"
 
-inst=0
-if [[ "_$1" == "_--install" ]]; then
-  inst=1
-fi
+function help {
+    echo "$0                 Sign apks and bundles"
+    echo "$0  --install      Sign and install apk in device using adb"
+    echo "$0  --keyroot      specify parent directory for finding cbs/$us/keystore.jks. if empty keyroot is loaded from file /var/$us/ush_config"
+}
 
-if [[ ! -f /var/$us/ush_config ]]; then
-    echo "KO 87036 /var/$us/ush_config must exist with envvar keyroot"
+#==============example parse flags leaving line without flags in opt=============
+let inst=0
+keyroot=""
+while [[ true ]]; do
+    opt=$1
+    shift
+    if [ "_$opt" == "_--install" ]; then
+        echo "install"
+        let inst=1
+        continue
+    elif [ "_$opt" == "_--keyroot" ]; then
+        echo "keyroot"
+        keyroot="$1"
+        shift
+        continue
+    else
+        break
+    fi
+done
+#====================================
+cmd=$opt
+if [[ -n $cmd ]]; then
+    help
+    echo "KO 89785 Invalid command"
     exit 1
 fi
-. /var/$us/ush_config
+
+if [[ -z $keyroot ]]; then
+    if [[ ! -f /var/$us/ush_config ]]; then
+        echo "KO 87036 /var/$us/ush_config must exist with envvar keyroot"
+        exit 1
+    fi
+    . /var/$us/ush_config
+fi
 
 if [[ "_$keyroot" == "_" ]]; then
-    echo "KO 87037 keyroot must be defined. keyroot=<directory>"
+    echo "KO 87037 Invalid keyroot."
     exit 1
 fi
 
@@ -53,7 +83,7 @@ function sign_apks {
     for file in `find app/build/outputs/apk -name "*-unsigned.apk"`; do
         echo "found unsigned apk: $file"
         newfile=`echo $file | sed "s/-unsigned//"`
-        echo "using $pass"
+        echo "using $gpg_passphrase_file"
 #        $jarsigner -verbose -keystore $ks $file distr <<< "$pass"
         $jarsigner -keystore $ks $file distr <<< "$pass"
         if [ $? -ne 0 ]; then
@@ -78,7 +108,7 @@ function sign_bundles {
         fi
         echo "found unsigned bundle: $file"
         newfile=`echo $file | sed "s/-unsigned//"`
-        echo "using $pass"
+        echo "using $gpg_passphrase_file"
 #        $jarsigner -verbose -keystore $ks $file distr <<< "$pass"
         $jarsigner -keystore $ks $file distr <<< "$pass"
         if [ $? -ne 0 ]; then
@@ -91,13 +121,13 @@ function sign_bundles {
     done
 }
 
-gpgkey=`cat $keyroot/distr_signing_key`
-gpg_passphrase_file="$keyroot/.gnupg/passphrase"
-gpg="gpg --homedir $keyroot/.gnupg"
+#gpgkey=`cat $keyroot/distr_signing_key`
+gpg_passphrase_file="$keyroot/cbs/$us/gnupg/passphrase"
+#gpg="gpg --homedir $keyroot/.gnupg"
 pass=`cat $gpg_passphrase_file`
 
 ks=$keyroot/cbs/$us/keystore.jks
-echo "using keystore at $ks in "`pwd`
+echo "using keystore at $ks"
 if [[ -d app/build/outputs/apk ]]; then
     sign_apks $ks
     echo "APKs:"
@@ -115,3 +145,4 @@ if [[ -d app/build/outputs/bundle ]]; then
     find app/build/outputs/bundle -type f -name "*.aab"
 fi
 exit 0
+
diff --git a/core1/bin/50_tokenized_files_and_sign b/core1/bin/50_tokenized_files_and_sign
--- a/core1/bin/50_tokenized_files_and_sign
+++ b/core1/bin/50_tokenized_files_and_sign
@@ -28,7 +28,7 @@ echo "#################################"
 if [[ -f ./.cbs/config ]]; then
     . ./.cbs/config
 else
-    echo "KO 8585 Missing .cbs/config."
+    echo "KO 85852 Missing .cbs/config."
     exit 1
 fi
 
@@ -38,7 +38,6 @@ hash=""
 let inst=0
 while [[ true ]]; do
     opt=$1
-    echo "read opt=$opt"
     shift
     if [[ "_$opt" == "_--install" ]]; then
         echo "install flag"
@@ -73,21 +72,21 @@ fi
 distr="distr"
 mkdir -p $distr
 
-function mk_sloccount {
-    ghash=$1
-    branch=$2
-    echo "mk_sloccount gitrep $gitrep ghash $ghash branch $branch"
-    mkdir tmpsloc
-    pushd tmpsloc > /dev/null
-        git clone -b $branch --single-branch $gitrep rep
-        pushd rep > /dev/null
-            echo "checkout $ghash"
-            git checkout -q $ghash
-            sloccount . > ../../sloccount.txt
-        popd > /dev/null
-    popd > /dev/null
-    rm -rf tmpsloc
-}
+#function mk_sloccount {
+#    ghash=$1
+#    branch=$2
+#    echo "mk_sloccount gitrep $gitrep ghash $ghash branch $branch"
+#    mkdir tmpsloc
+#    pushd tmpsloc > /dev/null
+#        git clone -b $branch --single-branch $gitrep rep
+#        pushd rep > /dev/null
+#            echo "checkout $ghash"
+#            git checkout -q $ghash
+#            sloccount . > ../../sloccount.txt
+#        popd > /dev/null
+#    popd > /dev/null
+#    rm -rf tmpsloc
+#}
 
 function patch {
     ifile="${1}.in"
@@ -100,41 +99,38 @@ function patch {
     done
 }
 
-function mk_checksums {
-    branddir=$1
-    echo "mk_checksums $branddir"
-    pushd $branddir > /dev/null
-        rm -f sha256sums.txt
-        rm -f sha256sums.txt.gpg
-        rm -f gpg_pubkey.txt
-        file=../sha256sums.txt
-        echo -n "" > $file
-        for f in `find . -type f`; do
-            echo -n "."
-            sha256sum $f >> $file
-        done
-        echo ""
-        mv $file .
-        gpgkey=$distr_key
-        if [[ "_$gpgkey" == "_" ]]; then
-            echo "KO 91124 gpgkey not set"
-            exit 1
-        fi
-#        gpg_passphrase_file=${distr_gpg_home}/passphrase
-        echo "gpg_passphrase_file $gpg_passphrase_file"
-        echo "distr_gpg_home $distr_gpg_home"
-        gpg="gpg --homedir $distr_gpg_home"
-        echo "$gpg --batch --yes --passphrase-file $gpg_passphrase_file --default-key $gpgkey --sign sha256sums.txt"
-#        $gpg --batch --yes --passphrase-file $gpg_passphrase_file --default-key $gpgkey --sign sha256sums.txt
-        $gpg --batch --yes --default-key $gpgkey --sign sha256sums.txt
-        r=$?
-        if [[ $r -ne 0 ]]; then
-            echo "KO 88944"
-            exit 1
-        fi
-        $gpg --armor --export $gpgkey > gpg_pubkey.txt
-    popd > /dev/null
-}
+#function mk_checksums {
+    #branddir=$1
+    #echo "mk_checksums $branddir"
+    #pushd $branddir > /dev/null
+        #rm -f sha256sums.txt
+        #rm -f sha256sums.txt.gpg
+        #rm -f gpg_pubkey.txt
+        #file=../sha256sums.txt
+        #echo -n "" > $file
+        #for f in `find . -type f`; do
+        #    echo -n "."
+        #    sha256sum $f >> $file
+        #done
+        #echo ""
+        #mv $file .
+        #gpgkey=$distr_key
+        #if [[ "_$gpgkey" == "_" ]]; then
+        #    echo "KO 91124 gpgkey not set"
+        #    exit 1
+        #fi
+        #echo "distr_gpg_home $distr_gpg_home"
+        #gpg="gpg --homedir $distr_gpg_home"
+        #echo "$gpg --batch --yes --default-key $gpgkey --sign sha256sums.txt"
+        #$gpg --batch --yes --default-key $gpgkey --sign sha256sums.txt
+        #r=$?
+        #if [[ $r -ne 0 ]]; then
+        #    echo "KO 88944"
+        #    exit 1
+        #fi
+        #$gpg --armor --export $gpgkey > gpg_pubkey.txt
+    #popd > /dev/null
+#}
 
 function sign_apks {
     brand=$1
@@ -153,7 +149,6 @@ function sign_apks {
         echo "found unsigned apk: $file"
         newfile=`echo $file | sed "s/-unsigned//"`
         echo "Signing apk $file using keystore at $ks"
-#         $jarsigner -verbose -keystore $ks $file distr <<< "$pass"
         $jarsigner -keystore $ks $file distr <<< "$pass"
         if [[ $? -ne 0 ]]; then
             echo "signer failed" >2
@@ -196,7 +191,7 @@ echo "vhash: $vhash"
 
 githash=`cat $distr/build_hashes | grep "^vhash $vhash" | sort | uniq | head -n1 | awk '{ print $5 }'`
 echo "githash: $githash"
-mk_sloccount $githash $branch
+#mk_sloccount $githash $branch
 
 v="${branch}_${vhash}"
 echo "looking for core_${v}.tar.zst"
@@ -236,31 +231,31 @@ for branddir in `find $distr -maxdepth 1 -mindepth 1 -type d`; do
     fi
     . $strfile
     if [[ "_$str3" != "_$brand" ]]; then
-        echo "KO 4032 - str3 in file $strfile must be $brand"
+        echo "KO 40362 str3 in file $strfile must be $brand"
         exit 1
     fi
     echo "title: $str1"
-    if [[ -d $distr/$brand/raspberry_pi ]]; then
-        pushd $distr/$brand/raspberry_pi/ > /dev/null
-            for i in `ls -1 *.zip`; do
-                str_os_raspi=$i #$brand-os_raspi_$hash.zip
-                break
-            done
-        popd > /dev/null
-        echo "Image $str_os_raspi"
-        str_os_raspi_size=`ls -la $distr/$brand/raspberry_pi/$str_os_raspi | awk '{ print $5 }'`
-        echo "str_os_raspi_size $str_os_raspi_size"
-        str_os_raspi_sha256sum=`sha256sum $distr/$brand/raspberry_pi/$str_os_raspi | awk '{ print $1 }'`
-   else
+    #if [[ -d $distr/$brand/raspberry_pi ]]; then
+    #    pushd $distr/$brand/raspberry_pi/ > /dev/null
+    #        for i in `ls -1 *.zip`; do
+    #            str_os_raspi=$i #$brand-os_raspi_$hash.zip
+    #            break
+    #        done
+    #    popd > /dev/null
+    #    echo "Image $str_os_raspi"
+    #    str_os_raspi_size=`ls -la $distr/$brand/raspberry_pi/$str_os_raspi | awk '{ print $5 }'`
+    #    echo "str_os_raspi_size $str_os_raspi_size"
+    #    str_os_raspi_sha256sum=`sha256sum $distr/$brand/raspberry_pi/$str_os_raspi | awk '{ print $1 }'`
+   #else
         str_os_raspi_size="0"
         str_os_raspi_sha256sum="0"
-   fi
+   #fi
    patch doc/node_setup_instructions_linux
    patch doc/node_setup_instructions_windows
-   find doc
+   #find doc
    mv doc/node_setup_instructions_linux $distr/$brand/node_setup_instructions_linux.txt
    mv doc/node_setup_instructions_windows $distr/$brand/node_setup_instructions_windows.txt
-   cp sloccount.txt $distr/$brand/
+   #cp sloccount.txt $distr/$brand/
    cp $distr/build_hashes $distr/$brand/
    cat doc/release_notes | grep "RELEASE NOTES" -A1000000 >  $distr/$brand/release_notes
    if [[ -d $branddir/html ]]; then
@@ -272,9 +267,9 @@ for branddir in `find $distr -maxdepth 1 -mindepth 1 -type d`; do
    if [[ -d $branddir/misc ]]; then
        find $branddir/misc -type f -exec cp {} $distr/$brand/ \;
    fi
-   mk_checksums $distr/$brand
+   #mk_checksums $distr/$brand
 done
-rm -f sloccount.txt
+#rm -f sloccount.txt
 echo "Finished $distr"
 #find $distr -type f
 exit 0
diff --git a/core1/bin/99_postupgrade b/core1/bin/99_postupgrade
--- a/core1/bin/99_postupgrade
+++ b/core1/bin/99_postupgrade
@@ -24,16 +24,16 @@
 
 . .cbs/config
 
-if [[ -d $branch ]]; then
-    echo "KO 33928 $branch exists"
-    exit 1
-fi
+#if [[ -d $branch ]]; then
+#    echo "KO 33928 $branch exists"
+#    exit 1
+#fi
 if [[ ! -d distr ]]; then
     echo "KO 20199 distr doesn't exists"
     exit 1
 fi
 let ne=`cat distr/build_hashes | grep "$branch" | wc -l`
-if [[ $ne -ne 5 ]]; then
+if [[ $ne -ne 5 ]]; then  #arch
     echo "KO 43398 expecting 5 entries containing $branch in distr/build_hashes"
     exit 1
 fi
@@ -42,7 +42,7 @@ if [[ ! -d blobs ]]; then
     exit 1
 fi
 let ne=`ls blobs -1 | grep "$branch" | wc -l`
-let ene=`ls ../core2/brands -1 | wc -l`
+let ene=`ls ${brands}/ -1 | wc -l`
 if [[ $ne -ne $ene ]]; then
     echo "KO 43398 expecting $ene blobs containing $branch in blobs/"
     exit 1
@@ -52,27 +52,112 @@ echo "Confirm that the network is running ${branch}."
 echo "Yes?"
 read a
 
+function update_devjobs {
+    brand=$1
+    echo "=================== github brand $brand branch $branch"
+    if [[ -z $branch ]]; then
+        echo "KO 86681 need branch."
+        exit 1
+    fi
+
+    echo "Update devjobs" #TODO fix for multiple devjobs
+    echo "Run bin/devjob_tool --id ${devjob_id} sync"
+    echo "yes?"
+    read a
+
+    bin/devjob_tool --branch $branch --id ${devjob_id} sync
+
+    echo "CTRL-Z. complete tasks. the resume with fg and say yes"
+    echo "yes?"
+    read a
+}
+
+function android_playstore {
+    brand=$1
+    echo "=================== android_playstore brand $brand branch $branch"
+    if [[ -z $branch ]]; then
+        echo "KO 86681 need branch."
+        exit 1
+    fi
+
+    appstoreaccount=${googleplay_account}
+    appname=${android_app_name}
+
+    echo "Update Google PlayStore"
+    pushd ../core0/us > /dev/null
+        bin/apply_brand ../../core2/brands/$brand $branch
+        pushd brand_$brand/us > /dev/null
+            bin/configure --appstore
+            if [[ $? -ne 0 ]]; then
+                echo "KO 87964 configure failed."
+                exit 1
+            fi
+            make android
+            if [[ $? -ne 0 ]]; then
+                echo "KO 87965 make android failed."
+                exit 1
+            fi
+            bin/sign_apk --keyroot ${keyroot}
+            if [[ $? -ne 0 ]]; then
+                echo "KO 87966 sign_apk failed."
+                exit 1
+            fi
+            pwd
+        popd > /dev/null
+    popd > /dev/null
+
+    bundl="../core0/us/brand_$brand/us/android/app/build/outputs/bundle/release/output-release.aab"
+    if [[ ! -f $bundl ]]; then
+        echo "KO 67745 bundle not found."
+        exit 1
+    fi
+    bundle=`realpath $bundl`
+
+    cat << EOF
+Goto https://play.google.com/console/"
+    1> Use account $appstoreaccount
+    2> Choose app $appname
+    3> Go to Production. Click 'Create New Release'
+    4> upload bundle at $bundle
+    5> Google suggests Release name like '22101819 (${brand}-${branch}_a9fab2.842136 2022-10-18_19-52-09)'
+    6> Change to something like '${brand}-${branch}_a9fab2.842136 2022-10-18_19-52-09'
+    7> Fill release notes:
+EOF
+
+    let ord=`echo $branch | sed "s~alpha-\(.*\)~\1~"`
+    let prev=$ord-1
+    echo "------ Info for release notes:"
+    cat doc/release_notes | grep "^alpha-$ord " -A1000 | grep -v "alpha-$ord" | grep "^alpha-$prev" -B1000 | grep -v "^alpha-$prev" | grep -v "^$"
+    echo "---------------------------------------"
+
+    echo "CTRL-Z. complete tasks. the resume with fg and say yes"
+    read a
+}
+
+function post_upgrade0 {
+    brand=$1
+    bdir=${brands}/${brand}
+    . ${bdir}/strset0
+
+    if [[ ${upload_googleplay} -eq 1 ]]; then
+        android_playstore $brand
+    fi
+
+    if [[ "_${devjob_id}" != "_" ]]; then
+        update_devjobs $brand
+    fi
+}
+
 function post_upgrade {
     echo ""
     echo "Post network upgrade tasks:"
-    brands=`find release_history/$branch/distr -mindepth 1 -maxdepth 1 -type d  | grep -v "deps$" | tr '/' ' ' | awk {'print $NF'}`
+    inclbrands=`find distr -mindepth 1 -maxdepth 1 -type d  | grep -v "deps$" | tr '/' ' ' | awk {'print $NF'}`
     let ecode=0
-    for b in $brands; do
-        echo "brand $b"
-        bdir=../core2/brands/$b
-        if [[ -x $bdir/bin/postupgrade ]]; then
-            echo "Found tasks script at $bdir/bin/postupgrade"
-            $bdir/bin/postupgrade $branch
-            if [[ $? -ne 0 ]]; then
-                echo "********************************************** skipping brand $b REVIEW
-                let ecode=1
-            fi
-        else
-            echo "No tasks found at $bdir/bin/postupgrade"
-        fi
+    for brand in ${inclbrands}; do
+        echo "==post_upgrade============================================= brand ${brand}"
+        post_upgrade0 $brand
     done
 }
-
 
 function save_release_history {
     echo -n "enter new branch: "
@@ -108,6 +193,11 @@ function save_release_history {
 
 post_upgrade
 save_release_history
+
+echo "==============================================="
+
+echo "Last, but not least, modify doc/release_notes, commit, and push the new branch."
+echo "cypherpunks write code."
 
 exit $ecode
 
