Android 8->11
downstream refs:
61e4526 cce94c3 9bccc38 db0c096 5ddfe17 9a67353 1196e0d 30a5021 c613bc4 05647db a1d9de2 76b08e9 5307f6c 8b10c64 b5d22b4 a741dd6 ab671ff b6c129f 131539a 3df0a44 55a97fd cf16d9e 0bd9764 1885071 341ec7e 375d8db bfae099 d5be473 4ccd8fa 1a71278 d72ae43 ab1d20e dad0255 017a5f8 a29c744 a529298 9815d4b be8dcea ea0229e e8b7fd4 a3d89d5 080e5a2 cfd1693 b66602e 42c3e76 38709d2 892cbb0 9529c13 b9f60b8 73fba46 cc3c540 e0dcb88 9a47cd8 649aaed 59525a8 515963d f0446f0 23e0a46 c876aea a854c2e 5f59dd0 f24cb1d 2647117 0e0ea1b f070937 5bf83f7 f166b5d 5daab9f e06fb0b 54c1052 71d8514 ff246f4 eb32096 810f3f4 273bad4 e8f0eb7 0090526 225e5b5 81361fd 96c18c9 5fc67b8 753dcb1 20071e1 ecd5874 b71d861 8cc7d88 2a83feb 095ea2c 5a4d386 80c2485 b7eb1f0 06adbb8 48ef406 ce87542 6a4edee e9f43ce 7b20821 6d2c923 d08213b 0ced28b f0f5d59 68105ee 3a623dd ea152d7 d04e090 7925108 d9c4207 3df0a0d 29185f7 fd0848f 3ec7672 f4a3cb5 26e8d35 91701c5 23e7474 593cb2f 3e4083c 5456131 014a308 65dfd7c 37b51db bf0f73c 1b4bbb9 ce35ef0 6a563a9

diff --git a/core1/bin/50_tokenized_files_and_sign b/core1/bin/50_tokenized_files_and_sign
--- a/core1/bin/50_tokenized_files_and_sign
+++ b/core1/bin/50_tokenized_files_and_sign
@@ -28,15 +28,15 @@ echo "#################################"
 if [[ -f ./.cbs/config ]]; then
     . ./.cbs/config
 else
-	echo "KO 8585 Missing .cbs/config."
-	exit 1
+    echo "KO 8585 Missing .cbs/config."
+    exit 1
 fi
 
 strset="en-uk"
 hash=""
 
 let inst=0
-while [ true ]; do
+while [[ true ]]; do
     opt=$1
     echo "read opt=$opt"
     shift
@@ -51,7 +51,7 @@ while [ true ]; do
 done
 
 build_jobs=$opt
-if [ "_$build_jobs" == "_" ]; then
+if [[ "_$build_jobs" == "_" ]]; then
     build_jobs="build_jobs"
     echo -n "specify which one: "
     find . -maxdepth 1 -type d -name "build_jobs*" | sed "s~^\./~~" | xargs
@@ -61,12 +61,12 @@ echo "using dir $build_jobs"
 
 jarsigner="jarsigner"
 keytool="keytool"
-if [ "_$JAVA_HOME" != "_" ]; then
+if [[ "_$JAVA_HOME" != "_" ]]; then
     jarsigner=$JAVA_HOME/bin/jarsigner
     keytool=$JAVA_HOME/bin/keytool
 fi
 
-if [ "_$1" != "_" ]; then
+if [[ "_$1" != "_" ]]; then
     strset=$1
 fi
 
@@ -102,6 +102,7 @@ function patch {
 
 function mk_checksums {
     branddir=$1
+    echo "mk_checksums $branddir"
     pushd $branddir > /dev/null
         rm -f sha256sums.txt
         rm -f sha256sums.txt.gpg
@@ -109,39 +110,65 @@ function mk_checksums {
         file=../sha256sums.txt
         echo -n "" > $file
         for f in `find . -type f`; do
-            echo "checksum $f"
+            echo -n "."
             sha256sum $f >> $file
         done
+        echo ""
         mv $file .
-        $gpg --batch --yes --passphrase-file $gpg_passphrase_file --default-key $gpgkey --sign sha256sums.txt
+        gpgkey=$distr_key
+        if [[ "_$gpgkey" == "_" ]]; then
+            echo "KO 91124 gpgkey not set"
+            exit 1
+        fi
+#        gpg_passphrase_file=${distr_gpg_home}/passphrase
+        echo "gpg_passphrase_file $gpg_passphrase_file"
+        echo "distr_gpg_home $distr_gpg_home"
+        gpg="gpg --homedir $distr_gpg_home"
+        echo "$gpg --batch --yes --passphrase-file $gpg_passphrase_file --default-key $gpgkey --sign sha256sums.txt"
+#        $gpg --batch --yes --passphrase-file $gpg_passphrase_file --default-key $gpgkey --sign sha256sums.txt
+        $gpg --batch --yes --default-key $gpgkey --sign sha256sums.txt
+        r=$?
+        if [[ $r -ne 0 ]]; then
+            echo "KO 88944"
+            exit 1
+        fi
         $gpg --armor --export $gpgkey > gpg_pubkey.txt
     popd > /dev/null
 }
 
-gpgkey=$distr_key
-gpg_passphrase_file=$distr_passphrase_file
-gpg="gpg --homedir $distr_gpg_home"
-pass=`cat $gpg_passphrase_file`
-
 function sign_apks {
-    echo "signing APKs"
-    ks=$1
-    for file in `find $distr -name "*-unsigned.apk"`; do
-	echo "found unsigned apk: $file"
+    brand=$1
+    branddir=$brands/$brand
+    echo "sign apks $brand $branddir"
+    distr_passphrase_file=${distr_gpg_home}/passphrase
+    pass=`cat $distr_passphrase_file`
+    ks=$keyroot/keystore.jks
+    echo "keystore $ks"
+    if [[ ! -f $ks ]]; then
+        echo "KO 66501 $ks not found."
+        exit 1
+    fi
+    let signed=0
+    for file in `find $distr/$brand -name "*-unsigned.apk"`; do
+        echo "found unsigned apk: $file"
         newfile=`echo $file | sed "s/-unsigned//"`
-        $jarsigner -verbose -keystore $ks $file distr <<< "$pass"
-        if [ $? -ne 0 ]; then
+        echo "Signing apk $file using keystore at $ks"
+#         $jarsigner -verbose -keystore $ks $file distr <<< "$pass"
+        $jarsigner -keystore $ks $file distr <<< "$pass"
+        if [[ $? -ne 0 ]]; then
             echo "signer failed" >2
             exit 1
         fi
+        let signed=1
         mv $file $newfile
         echo "signature $newfile"
         echo "$file -> $newfile"
         $keytool -list -printcert -jarfile $newfile
     done
+    if [[ $signed -ne 1 ]]; then
+        echo "WA 86954 No unsigned apk found for brand $brand"
+    fi
 }
-
-sign_apks $keyroot/keystore.jks
 
 hash=""
 branch=""
@@ -171,69 +198,83 @@ githash=`cat $distr/build_hashes | grep "^vhash $vhash" | sort | uniq | head -n1
 echo "githash: $githash"
 mk_sloccount $githash $branch
 
-
 v="${branch}_${vhash}"
 echo "looking for core_${v}.tar.zst"
 
 cat $distr/build_hashes
 
 for branddir in `find $distr -maxdepth 1 -mindepth 1 -type d`; do
+    echo "branddir $branddir"
     brand=$(basename $branddir)
-#for brand in `cat $distr/build_hashes | grep "^vhash " | awk '{ print $6 }' | sort | uniq`; do
-    if [ -f $distr/$brand/bin/apply_blob ]; then
-        echo "brand $brand"
-        if [ ! -d $distr/$brand ]; then
-            continue;
-        fi
-        branddir=$brands/$brand
-        strfile=$branddir/$strset
-        if [ ! -f $strfile ]; then
-            echo "KO 33029 unknown set $strset for $brand"
-	        exit 1
-        fi
-        . $strfile
-        if [ "_$str3" != "_$brand" ]; then
-            echo "KO 4032 - str3 in file $strfile must be $brand"
-            exit 1
-        fi
-        echo "title: $str1"
-        if [ -d $distr/$brand/raspberry_pi ]; then
-            pushd $distr/$brand/raspberry_pi/ > /dev/null
-                for i in `ls -1 *.zip`; do
-                    str_os_raspi=$i #$brand-os_raspi_$hash.zip
-                    break
-                done
-            popd > /dev/null
-            echo "Image $str_os_raspi"
-            str_os_raspi_size=`ls -la $distr/$brand/raspberry_pi/$str_os_raspi | awk '{ print $5 }'`
-            echo "str_os_raspi_size $str_os_raspi_size"
-            str_os_raspi_sha256sum=`sha256sum $distr/$brand/raspberry_pi/$str_os_raspi | awk '{ print $1 }'`
-        else
-            str_os_raspi_size="0"
-            str_os_raspi_sha256sum="0"
-        fi
-        patch doc/node_setup_instructions_linux
-        patch doc/node_setup_instructions_windows
-        find doc
-        mv doc/node_setup_instructions_linux $distr/$brand/node_setup_instructions_linux.txt
-        mv doc/node_setup_instructions_windows $distr/$brand/node_setup_instructions_windows.txt
-        cp sloccount.txt $distr/$brand/
-        cp $distr/build_hashes $distr/$brand/
-        cat doc/release_notes | grep "RELEASE NOTES" -A1000000 >  $distr/$brand/release_notes
-        if [ -d $branddir/html ]; then
-	        pushd $branddir
-		        tar -I zstd -cf html.tar.zst html
-	        popd
-	        mv $branddir/html.tar.zst $distr/$brand/
-        fi
-        if [ -d $branddir/misc ]; then
-            find $branddir/misc -type f -exec cp {} $distr/$brand/ \;
-        fi
-        mk_checksums $distr/$brand
+    if [[ "_$brand" == "_deps" ]]; then
+        continue
     fi
+    echo "brand $brand"
+    if [[ ! -f $distr/$brand/bin/apply_blob ]]; then
+         echo "KO 79221 File does not exist: $distr/$brand/bin/apply_blob"
+         exit 1
+    fi
+    echo "brand $brand"
+    if [[ ! -d $distr/$brand ]]; then
+        continue;
+    fi
+    if [[ -f ./.cbs/config_$brand ]]; then
+        echo "sourcing ./.cbs/config_$brand"
+        . ./.cbs/config_$brand
+    else
+        echo "KO 85856 Missing .cbs/config_$brand."
+        exit 1
+    fi
+    echo "Keyroot for brand $brand is $keyroot"
+    sign_apks $brand
+
+    branddir=$brands/$brand
+    strfile=$branddir/$strset
+    if [[ ! -f $strfile ]]; then
+        echo "KO 33029 unknown set $strset for $brand"
+        exit 1
+    fi
+    . $strfile
+    if [[ "_$str3" != "_$brand" ]]; then
+        echo "KO 4032 - str3 in file $strfile must be $brand"
+        exit 1
+    fi
+    echo "title: $str1"
+    if [[ -d $distr/$brand/raspberry_pi ]]; then
+        pushd $distr/$brand/raspberry_pi/ > /dev/null
+            for i in `ls -1 *.zip`; do
+                str_os_raspi=$i #$brand-os_raspi_$hash.zip
+                break
+            done
+        popd > /dev/null
+        echo "Image $str_os_raspi"
+        str_os_raspi_size=`ls -la $distr/$brand/raspberry_pi/$str_os_raspi | awk '{ print $5 }'`
+        echo "str_os_raspi_size $str_os_raspi_size"
+        str_os_raspi_sha256sum=`sha256sum $distr/$brand/raspberry_pi/$str_os_raspi | awk '{ print $1 }'`
+   else
+        str_os_raspi_size="0"
+        str_os_raspi_sha256sum="0"
+   fi
+   patch doc/node_setup_instructions_linux
+   patch doc/node_setup_instructions_windows
+   find doc
+   mv doc/node_setup_instructions_linux $distr/$brand/node_setup_instructions_linux.txt
+   mv doc/node_setup_instructions_windows $distr/$brand/node_setup_instructions_windows.txt
+   cp sloccount.txt $distr/$brand/
+   cp $distr/build_hashes $distr/$brand/
+   cat doc/release_notes | grep "RELEASE NOTES" -A1000000 >  $distr/$brand/release_notes
+   if [[ -d $branddir/html ]]; then
+       pushd $branddir
+           tar -I zstd -cf html.tar.zst html
+       popd
+       mv $branddir/html.tar.zst $distr/$brand/
+   fi
+   if [[ -d $branddir/misc ]]; then
+       find $branddir/misc -type f -exec cp {} $distr/$brand/ \;
+   fi
+   mk_checksums $distr/$brand
 done
 rm -f sloccount.txt
 echo "Finished $distr"
-find $distr -type f
+#find $distr -type f
 exit 0
-
