hotfix. new wallets did't work well unless backed restarted after their creation.  Revert "hotfix. new wallets did't work well unless backed restarted after their creation."  hotfix. new wallets did't work well unless backed restarted after their creation.
downstream refs:
6c49fd35 0b08c556 a595d615 08f3b302 2006683f b26b0318 38de2420 8bc509b2 58b0166d

diff --git a/core1/bin/70_make_blobs b/core1/bin/70_make_blobs
--- a/core1/bin/70_make_blobs
+++ b/core1/bin/70_make_blobs
@@ -82,6 +82,10 @@ for branddir in `find distr -maxdepth 1 -mindepth 1 -type d`; do
                 echo "KO 87945 missing release_notes."
                 exit 1
             fi
+            if [[ ! -f $blobdir/doc/strset ]]; then
+                echo "KO 87946 missing strset file."
+                exit 1
+            fi
             cp deps $blobdir/ -R
             echo "Excluding OS Image"
             rm -rf $blobdir/raspberry_pi
@@ -109,7 +113,10 @@ for branddir in `find distr -maxdepth 1 -mindepth 1 -type d`; do
             tar -I zstd -cf $blobdir.tzst $blobdir
             mv $blobdir.tzst ../blobs/
             mv /tmp/${brand}_install_blob ../blobs/
+            . $blobdir/doc/strset
             rm -rf $blobdir
+            #write partid
+            echo "$str40" > ../blobs/${blobdir}.tzst.partid
 	    popd > /dev/null
     else
         echo "skipped distr/$brand"
diff --git a/core1/bin/80_deploy_blobs b/core1/bin/80_deploy_blobs
--- a/core1/bin/80_deploy_blobs
+++ b/core1/bin/80_deploy_blobs
@@ -50,57 +50,109 @@ scp="scp -i ${grootkey}"
 
 #set -x
 
-for blob in `find blobs/ -type f -name "*.tzst"`; do
-    echo "------------------------------------------------------------------------------------"
-    echo "------------------------------------------------------------------------------------"
-    echo "blob: $blob"
-    echo "------------------------------------------------------------------------------------"
-    echo "------------------------------------------------------------------------------------"
-    bname=$(basename $blob)
-    brand=`echo "$bname" | tr '_' ' ' | awk '{ print $1 }'`
-    branch=`echo "$bname" | tr '_' ' ' | awk '{ print $2 }'`
-    hash=`echo "$bname" | tr '_' ' ' | awk '{ print $3 }'`
-    flags=`echo "$bname" | tr '_' ' ' | awk '{ print $4 }'`
-    echo ""
-    echo "brand $brand branch $branch hash $hash flags $flags"
-    if [ -f ./.cbs/config_$brand ]; then
-        . ./.cbs/config_$brand
-    else
-        echo "KO 70694 Missing .cbs/config_$brand file"
-        exit 1
-    fi
-    node=$distr_node_pkh
-    echo "node $node"
-    ush -pkh nick $node > /tmp/usho
-    r=$?
-    cat /tmp/usho
-    if [[ $r -ne 0 ]]; then
-        exit 1
-    fi
-    ip=`cat /tmp/usho | grep "^reachable_addr" | awk '{ print $NF }'`
-    port=`cat /tmp/usho | grep "^reachable_ssh_port" | awk '{ print $NF }'`
-    rm /tmp/usho
-    if [[ $oub -eq 0 ]]; then
-        $ssh -p$port $ip "mkdir -p /var/$brand/blob; mkdir -p /var/$brand/blob_prev; touch /var/$brand/blob/mvbug.tzst; mv /var/$brand/blob/*.tzst /var/$brand/blob_prev/; rm /var/$brand/blob_prev/mvbug.tzst"
-        if [[ $? -ne 0 ]]; then
+function up_blobs {
+    for blob in `find blobs/ -type f -name "*.tzst"`; do
+        echo "------------------------------------------------------------------------------------"
+        echo "------------------------------------------------------------------------------------"
+        echo "blob: $blob"
+        echo "------------------------------------------------------------------------------------"
+        echo "------------------------------------------------------------------------------------"
+        bname=$(basename $blob)
+        brand=`echo "$bname" | tr '_' ' ' | awk '{ print $1 }'`
+        branch=`echo "$bname" | tr '_' ' ' | awk '{ print $2 }'`
+        hash=`echo "$bname" | tr '_' ' ' | awk '{ print $3 }'`
+        flags=`echo "$bname" | tr '_' ' ' | awk '{ print $4 }'`
+        if [[ ! -f $blob.partid ]]; then
+            echo "KO 78699 $blob.partid not found."
             exit 1
         fi
-        $scp -P$port $blob $ip:/var/$brand/blob/
-        if [[ $? -ne 0 ]]; then
-            echo "KO 55031"
+        partid=`cat $blob.partid`
+        echo ""
+        echo "brand $brand branch $branch hash $hash flags $flags partid $partid"
+        if [[ -f ./.cbs/config_$brand ]]; then
+            . ./.cbs/config_$brand
+        else
+            echo "KO 70694 Missing .cbs/config_$brand file"
             exit 1
         fi
-    fi
+        dir=$(dirname $blob)
+        part=`cat $blob.partid`
+        node=$distr_node_pkh
+        echo "node $node"
+        ush -pkh nick $node > /tmp/usho
+        r=$?
+        cat /tmp/usho
+        if [[ $r -ne 0 ]]; then
+            exit 1
+        fi
+        ip=`cat /tmp/usho | grep "^reachable_addr" | awk '{ print $NF }'`
+        port=`cat /tmp/usho | grep "^reachable_ssh_port" | awk '{ print $NF }'`
+        rm /tmp/usho
+        if [[ $oub -eq 0 ]]; then
+        $ssh -p $port gov@$ip bin/up_blobs ${brand}
+            if [[ $? -ne 0 ]]; then
+                echo "KO 88791 cannot ssh to BDN brand $brand"
+                exit 1
+            fi
+        fi
 
-    brandcode="$str40"
-    $ssh -p $port gov@$ip bin/up_blobs ${brand} ${brandcode}
-    if [[ $? -ne 0 ]]; then
-        echo "KO 88791 cannot ssh to BDN brand $brand"
-        exit 1
-    fi
-done
+    done
+}
 
-#set +x
+function scp_blobs {
+    for blob in `find blobs/ -type f -name "*.tzst"`; do
+        echo "------------------------------------------------------------------------------------"
+        echo "------------------------------------------------------------------------------------"
+        echo "blob: $blob"
+        echo "------------------------------------------------------------------------------------"
+        echo "------------------------------------------------------------------------------------"
+        bname=$(basename $blob)
+        brand=`echo "$bname" | tr '_' ' ' | awk '{ print $1 }'`
+        branch=`echo "$bname" | tr '_' ' ' | awk '{ print $2 }'`
+        hash=`echo "$bname" | tr '_' ' ' | awk '{ print $3 }'`
+        flags=`echo "$bname" | tr '_' ' ' | awk '{ print $4 }'`
+        if [[ ! -f $blob.partid ]]; then
+            echo "KO 78699 $blob.partid not found."
+            exit 1
+        fi
+        partid=`cat $blob.partid`
+        echo ""
+        echo "brand $brand branch $branch hash $hash flags $flags partid $partid"
+        if [[ -f ./.cbs/config_$brand ]]; then
+            . ./.cbs/config_$brand
+        else
+            echo "KO 70694 Missing .cbs/config_$brand file"
+            exit 1
+        fi
+        dir=$(dirname $blob)
+        part=`cat $blob.partid`
+        node=$distr_node_pkh
+        echo "node $node"
+        ush -pkh nick $node > /tmp/usho
+        r=$?
+        cat /tmp/usho
+        if [[ $r -ne 0 ]]; then
+            exit 1
+        fi
+        ip=`cat /tmp/usho | grep "^reachable_addr" | awk '{ print $NF }'`
+        port=`cat /tmp/usho | grep "^reachable_ssh_port" | awk '{ print $NF }'`
+        rm /tmp/usho
+        if [[ $oub -eq 0 ]]; then
+            $ssh -p$port $ip "mkdir -p /var/$brand/blob; mkdir -p /var/$brand/blob_prev; touch /var/$brand/blob/mvbug.tzst; mv /var/$brand/blob/*.tzst /var/$brand/blob_prev/; rm /var/$brand/blob_prev/mvbug.tzst; echo "$partid" > /var/$brand/blob/partid"
+            if [[ $? -ne 0 ]]; then
+                exit 1
+            fi
+            $scp -P$port $blob $ip:/var/$brand/blob/
+            if [[ $? -ne 0 ]]; then
+                echo "KO 55031"
+                exit 1
+            fi
+        fi
+    done
+}
+
+scp_blobs
+#up_blobs
 
 echo "Blobs have been delivered to BDPs, and they have uploaded the blob to blockchain."
 echo "Next step:"
diff --git a/core1/bin/brand_tool b/core1/bin/brand_tool
--- a/core1/bin/brand_tool
+++ b/core1/bin/brand_tool
@@ -23,9 +23,12 @@
 #===-
 
 function help {
-    echo "$0 new <brand_seed_dir>      Create a New brand. If the brand is not new it will ask before rewriting parts."
-    echo "$0 gen_strset <brand_seed_dir>"
-    echo "$0 upload_bde_setup <brand_seed_dir>"
+    cat << EOF
+$0 new <brand_seed_dir>      Create a New brand. If the brand is not new it will ask before rewriting parts.
+$0 gen_strset <brand_seed_dir>
+$0 upload_bde_setup <brand_seed_dir>
+$0 gen_bookmarks <brand_seed_dir>
+EOF
 }
 
 cmd=$1
@@ -219,6 +222,33 @@ function gen_govk {
     fi
 }
 
+function walletsk {
+    if [[ ! -z ${node_wallet_k} ]]; then
+        return
+    fi
+    node_wallet_k=`cat ${brandkeyroot}/walletk`
+    if [[ $? -ne 0 ]]; then
+        echo "KO 45824 cannot retrieve node_wallet_k from ${brandkeyroot}/walletk"
+        exit 1
+    fi
+    if [[ -z ${node_wallet_k} ]]; then
+        echo "KO 45926 cannot load ${brandkeyroot}/walletk."
+        exit 1
+    fi
+}
+
+function walletaddr {
+    if [[ ! -z ${node_wallet_addr} ]]; then
+        return
+    fi
+    walletsk
+    node_wallet_addr=`${us}-wallet priv_key ${node_wallet_k} | grep "^addr " | awk '{ print $2 }'`
+    if [[ $? -ne 0 ]]; then
+        echo "KO 75823 cannot generate addr from node_wallet_k"
+        exit 1
+    fi
+}
+
 function gen_walletk {
     echo "gen_walletk"
     if [[ ! -f ${brandkeyroot}/walletk ]]; then
@@ -233,21 +263,9 @@ function gen_walletk {
         fi
         echo "${node_wallet_k}" > ${brandkeyroot}/walletk
     else
-        node_wallet_k=`cat ${brandkeyroot}/walletk`
-        if [[ $? -ne 0 ]]; then
-            echo "KO 45824 cannot retrieve node_wallet_k from ${brandkeyroot}/walletk"
-            exit 1
-        fi
-        if [[ -z ${node_wallet_k} ]]; then
-            echo "KO 45926 cannot load ${brandkeyroot}/govk."
-            exit 1
-        fi
+        walletsk
     fi
-    node_wallet_addr=`${us}-wallet priv_key ${node_wallet_k} | grep "^addr " | awk '{ print $2 }'`
-    if [[ $? -ne 0 ]]; then
-        echo "KO 75823 cannot generate addr from node_wallet_k"
-        exit 1
-    fi
+    walletaddr
 }
 
 function gen_settings {
@@ -282,8 +300,10 @@ function gen_bookmarks {
     if [[ -z ${trade_bookmark_protocol_selection} ]]; then
         trade_bookmark_protocol_selection="- - "
     fi
+    walletaddr
     subhome=""
     #subhome=".subhome"
+    echo "$us-wallet create_bookmark \"${trade_bookmark_label}\" ${brand_seed_dir}/icoapp.png \"${trade_bookmark_chan}${node_wallet_addr}${subhome}\" ${trade_bookmark_protocol_selection} ${brand_dir}/bookmarks"
     $us-wallet create_bookmark "${trade_bookmark_label}" ${brand_seed_dir}/icoapp.png "${trade_bookmark_chan}${node_wallet_addr}${subhome}" ${trade_bookmark_protocol_selection} ${brand_dir}/bookmarks
     if [[ ! -f ${brand_dir}/bookmarks ]]; then
         echo "KO 91028 bookmarks hasn't been created"
@@ -955,6 +975,10 @@ if [[ "_$cmd" == "_gen_strset" ]]; then
 fi
 if [[ "_$cmd" == "_upload_bde_setup" ]]; then
     upload_bde_setup
+    exit 0
+fi
+if [[ "_$cmd" == "_gen_bookmarks" ]]; then
+    gen_bookmarks
     exit 0
 fi
 
