upstream devjob_2b4ed310 refs: c4424f9  rbse  upstream devjob_2b4ed310 refs: 58215b0 22ca7eb 65a6dc3 3ff2912 4452770 ec846cc a88f618 8cb015e df6e99c f0c68de 9a8eb7a 450975c db758e4 8592049 3c32475 b7fc349 206ba1e d0f2177 97f6c04 d0ab749 1569be5 c25b2ce 1c8e5bd 77cdb38 9e61227 ba529da f275d3b bc6194d af81150 bc6f035 d218371 c941b6b db1ff5f 93f408a 5307a78 e01146f 2939b14
downstream refs:
794d1200 13e27497 8ed56064 c855926a 606a614e 4c4d4f22 3cf5e2e2 e7a78f5f f5a8328f a4fa1001 58b06943 fa00cd9d 540d253d e2a2b121 e281dab4 b910c17e 5d99312d b6090624 5995afb6 852c0593 b0606788 faa020ac 4253b1b3 bbd48d59 cf42fb5c 1b528042 a3f438fe c1b5c1cc 97a2ee96 abc6919e aaef725b 7991fb51 5c1888a3 bce784b0 190c169e a5e159d9 a79eba30 034c22fe 583e73a3 897018e6 812ff26a 1138148c f91be230 3ff79e48 7cf91eda b2fa1819

diff --git a/core1/bin/brand_tool b/core1/bin/brand_tool
--- a/core1/bin/brand_tool
+++ b/core1/bin/brand_tool
@@ -26,6 +26,7 @@ function help {
     cat << EOF
 New/update:
     $0 update <brand_seed_dir>      Update an existing brand or create a New brand. If the brand is not new it will ask before rewriting parts.
+    Input for new: copy existing brand_seeds/* dir
 
 strtset:
     $0 gen_strset <brand_seed_dir>
@@ -340,6 +341,7 @@ function gen_govk {
             >&2 echo "KO 45926 cannot create node_gov_k. empty. wallet working ok?"
             exit 1
         fi
+        mkdir -p ${brandkeyroot}
         echo "${node_gov_k}" > ${brandkeyroot}/govk
     fi
     govaddr
@@ -397,6 +399,7 @@ function gen_walletk {
             >&2 echo "KO 45826 cannot create node_wallet_k. empty. wallet working ok?"
             exit 1
         fi
+        mkdir -p ${brandkeyroot}
         echo "${node_wallet_k}" > ${brandkeyroot}/walletk
     fi
     walletaddr
@@ -749,6 +752,10 @@ function gen_android_keys {
     keytool="keytool"
     if [[ "_$JAVA_HOME" != "_" ]]; then
         keytool=$JAVA_HOME/bin/keytool
+        if [[ ! -x $keytool ]]; then
+            >&2 echo "KO 88199 $keytool not found."
+            exit 1
+        fi
     fi
     if [[ ! -f ${brandkeyroot}/keystore.jks ]]; then
         echo -n "gen android keys (${brandkeyroot}/keystore.jks)" #? [y/n]: "
@@ -910,7 +917,7 @@ function ssh_passwordless {
         exit 1
     fi
     idrsapub=$(cat /root/.ssh/id_rsa.pub)
-    echo "Access to BDE:"
+    echo "Access to BDE port 22:"
     ssh $unixname "if [[ ! -d /root/.ssh ]]; then ssh-keygen; fi; echo \"$idrsapub #brand_tool\" >> /root/.ssh/authorized_keys; cat /root/.ssh/authorized_keys"
     if [[ $? -ne 0 ]]; then
         >&2 echo "KO 87984 smthing went wrong"
@@ -951,14 +958,20 @@ function bde_bootstrap {
 }
 
 function docheck {
+    echo "check"
     a=$(cat ${brandkeyroot}/govk)
+    echo "check a"
     b=$(su ${GOVUSER} -c "${us}-wallet priv_key $a" | grep "^addr " | awk '{ print $2 }')
+    echo "check b"
     c=$(cat ${brand_dir}/en-uk | grep "^str66=" | sed "s~^str66=\"\(.*\)\" #distr_node_pkh~\1~")
+    echo "check c"
     if [[ "_$b" != "_$c" ]]; then
         >&2 echo "KO 76895 Inconsistency 1. ${brand_dir}/en-uk"
         exit 1
     fi
-    d=$(ssh $unixname "cat /home/${GOVUSER}/.${brand}/gov/k")
+    ssh="ssh -p16671"
+    echo "============>$ssh $unixname "cat /home/${GOVUSER}/.${brand}/gov/k""
+    d=$($ssh $unixname "cat /home/${GOVUSER}/.${brand}/gov/k")
     if [[ "_$a" != "_$d" ]]; then
         echo "KO 76895 Inconsistency 2. remote govk"
         exit 1
diff --git a/core1/bin/devjob_tool b/core1/bin/devjob_tool
--- a/core1/bin/devjob_tool
+++ b/core1/bin/devjob_tool
@@ -43,21 +43,30 @@ function help {
 }
 
 function help {
-    echo "$0 [options] <command>"
-    echo "Commands:"
-    echo "    new                Generate new upstream devjob."
-    echo "        --upload"
-    echo "        --workdir <name>"
-    echo "        --branch <branch>"
-    echo "        --brand <brand>"
-    echo -n "        Available brands: "; ls -1 $brands | xargs
-    echo "    sync <options>     Synchronize upstream devjob."
-    echo "        --id <id>      by id (ids in file .cbs/devjobs_active)"
-    echo "        --url <url>    upstream devjob git url"
-    echo "        --dryrun       Don't push neither upstream nor downstream."
-    echo "        --dsbranch <name>  Use existing/Create a new downstream feature branch."
+    cat << EOF
+$0 [options] <command>
+Commands:
+    new                Generate new upstream devjob.
+        --upload            .
+        --workdir <name>    .
+        --branch <branch>   .
+        --brand <brand>     .
+        Available brands:   { $(ls -1 $brands | xargs) }
+
+    sync <options>     Synchronize upstream devjob.
+        --id <id>           by id (ids in file .cbs/devjobs_active)
+        --url <url>         upstream devjob git url
+        --dryrun            Don't push neither upstream nor downstream.
+        --dsbranch <name>   Use existing/Create a new downstream feature branch.
+
+    --h                Print this help.
+
+EOF
+    echo "======================="
     echo "active devjobs: id url"
-    cat $djactive | grep -v "^#"
+    echo "======================="
+    cat $djactive | grep -v "^#" | column -t -s' '
+    echo "======================="
 }
 
 optid=""
@@ -104,12 +113,15 @@ while [[ true ]]; do
         workdir=$1
         shift
         continue
-    elif [[ _$opt == _-* ]]; then
-        echo "KO 60501 Invalid flag $opt"
+    elif [[ "_$opt" == "_--h" ]]; then
         help
+        exit 0
+    elif [[ _$opt == _-* ]]; then
+        >&2 help
+        >&2 echo "KO 60501 Invalid flag $opt"
         exit 1
     else
-        echo "end parsing flags"
+        #echo "end parsing flags"
         break
     fi
 done
@@ -379,6 +391,8 @@ function adaptd {
     nbranch=$2 #hqrefactor0
     timepoint=$3
     c2=$4
+    usbin=$5
+
     echo "    ##########################"
     echo "    ## adapt downstream $timepoint ##"
     echo "    ##########################"
@@ -400,6 +414,7 @@ function adaptd {
 #git checkout alpha-55
 #git checkout ${baseh} 
 #cp core2/brand_seeds/plebble/strset0 /tmp/
+#cp bin/make /tmp/
 #pwd
 #exit 1
         mv core2/brands/$brand x1
@@ -413,6 +428,8 @@ function adaptd {
         mv x1 core2/brands/$brand
         mv x2 core2/brand_seeds/$brand
 
+        rm -r bin
+        cp -r $usbin bin
 
         git add core2
         git add -u
@@ -483,26 +500,34 @@ function adapt { #create branch nbranch based on baseh. Then unlicense code, cre
         fi
         cp -r ${dsc2} core2
 
-
-
-
 #echo "*1*********************"
 #mv downstream/core2/brand_seeds/katlas /tmp/
 #exit 1
-        if [[ ! -f core1/brand_seeds/strset0 ]]; then
-            mkdir -p core1/brand_seeds/$brand
-            cp /tmp/strset0 core1/brand_seeds/$brand/
-            git add core1/brand_seeds/$brand/strset0
-        fi
-        if [[ -f /tmp/makefile_distr ]]; then
-            cp /tmp/makefile_distr core1/snippets/
+#        if [[ ! -f core1/brand_seeds/strset0 ]]; then
+#            mkdir -p core1/brand_seeds/$brand
+#            cp /tmp/strset0 core1/brand_seeds/$brand/
+#            git add core1/brand_seeds/$brand/strset0
+#        fi
+#        if [[ -f /tmp/makefile_distr ]]; then
+#            cp /tmp/makefile_distr core1/snippet/
 #echo "*1*****************************"
+#read a
 #pwd
 #exit 1
 #            mkdir -p core1/brand_seeds/$brand
 #            cp /tmp/strset0 core1/brand_seeds/$brand/
 #            git add core1/brand_seeds/$brand/strset0
-        fi
+#        fi
+#        if [[ -f /tmp/make ]]; then
+#            cp /tmp/makefile_distr core1/snippet/
+#echo "*1*****************************"
+#read a
+#pwd
+#exit 1
+#            mkdir -p core1/brand_seeds/$brand
+#            cp /tmp/strset0 core1/brand_seeds/$brand/
+#            git add core1/brand_seeds/$brand/strset0
+#        fi
 
         rm core2/brands/${brand} -r
         rm core2/brand_seeds/${brand} -r
@@ -941,8 +966,10 @@ function procurl {
         echo "## save core2...       ##"
         echo "#########################"
         echo "saving core2 on branch ${branch}"
-        cp downstream/core2 c2 -R
+        cp -r downstream/core2 c2
+        cp -r downstream/bin usbin
         dsc2=`realpath c2`
+        dsusbin=`realpath usbin`
 
 # ┌──────────┐                    ┌────────┐
 # │downstream│                    │upstream│
@@ -974,7 +1001,7 @@ function procurl {
         echo "######################"
         echo "## make_patch_downs ##"
         echo "######################"
-        adaptd ${downstream_hash} hqrefactor0 beg ${dsc2}
+        adaptd ${downstream_hash} hqrefactor0 beg ${dsc2} ${dsusbin}
         echo "prepare patch for upstream ${downstream_hash} --> ${branch}"
         pushd downstream > /dev/null
             git diff --binary hqrefactor0 ${branch} > ../patch4upstream
