coldfix - bin/99 failed.  coldfix - bin/99 failed.  upstream devjob_2b4ed310 refs: 3ae302a  upstream devjob_2b4ed310 refs: 72bc0e0 0b51d7c bca5b85
downstream refs:
46988cec 62c69e70 dff9e914 d392dbfc be61f050 9ca859d4 9fefeaa8 f63e85a0 c94a5f44 318e2508 d69689e2 45dd24f5 cc399325 2d59f8d0 72ebdb85 a9cacaf0 0b231b75 2ccce550 84653823 3603f7c8 9542a2d8 7b1e736e 8e7b7f9c 7510b0bb a4c6cda4 761d01f6 b93f707d 69081d12 1d3a435f 36be9905 5af29ddc c053b713 b373caab a336d1f1 1fabcce1 6b25e4df a2eda9db 60a4d9e7 a9b7d519 39106343 781be8d3 33e966e6 9f9fb645 df87fb20 717e3454 f906e2df 685beaf0 03ca2dcf 76ced831 01683461 a225e1ae d9a58f01 c4b2a783 af6aecc9 059c6acc d74475ec 54318bda ab4b6a3d 65a2cf61 97089f32 edfc60f2 53e349f5 b28209ff a23eccfc ab25a977 2fc06dfe d0b205f2 4158e987 213ec44f 32a89ddf 4d3961c9 6b94bc4d e6436e77 f9219447 3d5e9c77 be76549c 80b08968 c15b7ef5 a4d2f955 e0130a4d d8375a63 676a2f6c a5035815 366c2f60 c99d3cc2 6bb5c495 23682ddd 3d33228a 29fa1f5a 0fab1a7b 5e1e0757 a68658f4 52109bcb 3cde69fd db80dbb9 8fb83d30 26981326 9f1441b3 979f2ff1 e336eb97 791b74a3 78d028f5 fa98db0a d145b31a bf7c4ddf dcf64513 3e795c67 fa0764cf 217193e5 2eecfc42 fd4daac0 98a18ee4 bfe48c8d 39501a72 0efc434c 8fda298e ffda50ef 54470e7a 73ac135c c00d2a16 fb659518 3f536b05 b99d72e0 a0f3ac66 12bd47f3 dab2222d b3d159f3 78cca419 3d14fbad a0d14190 79e7fb39 7adb81fd e1769ba9 efee4579 6bf1b182 d17b4420 8035b71b cb4227a8 d7cfbb5e 5d7b28c3 fa1b475c a280f176 c50619ef 89eb4c8d ae452378 3d9aaed6 93533218 307fcd0e 3a1ed142 84b8f3ef aabd5a44 35dd6a27 c13c452b df5361f6 bbc9d95a db0c55ec 5bef9a0e 996baff1 2dd679c6 9ce13312 9a76a8a4 94a6a648 11ae88ce ef69afcc 952a7f29 b6524f63 5c16bd87 0b042b8e 347505c0 003e6ecc 6ff907d0 bd6d17bc 7198b0d7 48b5c822 c9d10d4a 9ab909ec cce37b44 0b526264 acd3caab 02273118 2c81a7c2 ca4870cd 9cbb521b 865c499b cc833e18 bf02545c 0030d560 18b247a2 fe654e6d a4dd4a94 a14a82cc 7cbe1666 2f2b77ab 66b91ed4 4b95cf0a cdc1a7c4 e4b6d397 e5fab8ab 034e6427 07bb0cc2 fe42e2c9 6a2121b2 d04c3c19 2991e5ed b9c0f386 d26f7816 6d572d8a 7ecd9dd5 0f811c00 a1b0e7ec 949899bf 9d326e44 1525aa4b 6a6c669c 50c79a8b 2c2944cd 32a3c444 24f05a00 c45aac1d 5ac0a12e fed2d19e cd4a68cb c9a7ba8a 9a98db8d be55b573 f14c26fa 2446fc80 e2348f21 d7a89b6c e1c10f21 a968b7b4 68a49bc6

diff --git a/core0/us/bin/apply_brand b/core0/us/bin/apply_brand
--- a/core0/us/bin/apply_brand
+++ b/core0/us/bin/apply_brand
@@ -24,6 +24,8 @@
 branddir=$1
 branch=$2
 
+. lib/shenv
+
 dbg=0
 logs=0
 counters=0
@@ -38,9 +40,9 @@ function help {
 function findbrand {
     d=$1
     if [[ -d $d ]]; then
-        n=`find $d -maxdepth 1 -mindepth 1 -type d | wc -l`
+        n=$(find $d -maxdepth 1 -mindepth 1 -type d | wc -l)
         if [[ $n -eq 1 ]]; then
-            branddir=`find $d -maxdepth 1 -mindepth 1 -type d`
+            branddir=$(find $d -maxdepth 1 -mindepth 1 -type d)
             echo "selecting existing brand at $branddir"
         fi
 	fi
@@ -62,18 +64,18 @@ if [[ -f ../../.revs ]]; then
 fi
 
 if [[ "_$branddir" == "_" ]]; then
-    help
-    echo "KO 40307"
+    >&2 help
+    >&2 echo "KO 40307"
     exit 1
 fi
 
 if [[ "_$branch" == "_" ]]; then
-    help
-    echo "KO 46538"
+    >&2 help
+    >&2 echo "KO 46538"
     exit 1
 fi
 
-branddir=`realpath $branddir`
+branddir=$(realpath $branddir)
 
 echo "applying $branddir"
 echo "branch $branch"
@@ -91,33 +93,33 @@ function copyhash {
 }
 
 function patch_core {
-    branddir=$1
-    c0=$2
-    if [ -f $branddir/en-uk ]; then
+    branddir="$1"
+    c0="$2"
+    if [[ -f $branddir/en-uk ]]; then
         $c0/us/bin/override_env $c0/us/res/strings/en-uk $branddir/en-uk > $c0/us/res/strings/en-uk.ovr
     else
-      echo "KO 7060"
+      >&2 echo "KO 70600 "
       exit 1
     fi
-    if [ $dbg -eq 1 ]; then
-      sed -i 's~^str29=\(.*\)~str29=1~' $c0/us/res/strings/en-uk.ovr
+    if [[ $dbg -eq 1 ]]; then
+        sedi 's~^str29=\(.*\)~str29=1~' $c0/us/res/strings/en-uk.ovr
     else
-      sed -i 's~^str29=\(.*\)~str29=0~' $c0/us/res/strings/en-uk.ovr
+        sedi 's~^str29=\(.*\)~str29=0~' $c0/us/res/strings/en-uk.ovr
     fi
-    if [ $logs -eq 1 ]; then
-      sed -i 's~^str33=\(.*\)~str33=1~' $c0/us/res/strings/en-uk.ovr
+    if [[ $logs -eq 1 ]]; then
+        sedi 's~^str33=\(.*\)~str33=1~' $c0/us/res/strings/en-uk.ovr
     else
-      sed -i 's~^str33=\(.*\)~str33=0~' $c0/us/res/strings/en-uk.ovr
+        sedi 's~^str33=\(.*\)~str33=0~' $c0/us/res/strings/en-uk.ovr
     fi
-    if [ $counters -eq 1 ]; then
-      sed -i 's~^str41=\(.*\)~str41=1~' $c0/us/res/strings/en-uk.ovr
+    if [[ $counters -eq 1 ]]; then
+        sedi 's~^str41=\(.*\)~str41=1~' $c0/us/res/strings/en-uk.ovr
     else
-      sed -i 's~^str41=\(.*\)~str41=0~' $c0/us/res/strings/en-uk.ovr
+        sedi 's~^str41=\(.*\)~str41=0~' $c0/us/res/strings/en-uk.ovr
     fi
-    if [ $connlog -eq 1 ]; then
-      sed -i 's~^str42=\(.*\)~str42=1~' $c0/us/res/strings/en-uk.ovr
+    if [[ $connlog -eq 1 ]]; then
+        sedi 's~^str42=\(.*\)~str42=1~' $c0/us/res/strings/en-uk.ovr
     else
-      sed -i 's~^str42=\(.*\)~str42=0~' $c0/us/res/strings/en-uk.ovr
+        sedi 's~^str42=\(.*\)~str42=0~' $c0/us/res/strings/en-uk.ovr
     fi
     pushd $c0 > /dev/null
         pushd us > /dev/null
@@ -147,37 +149,37 @@ function patch_android {
     echo "us/android: replacing us.cash with: $str28"
     pushd $c0/us/android > /dev/null
         gradlename=${str28/./-}
-        sed -i "s/us-cash/$gradlename/g" settings.gradle
+        sedi "s/us-cash/$gradlename/g" settings.gradle
         pushd app > /dev/null
-            sed -i "s/applicationId \"us\.cash\"/applicationId \"$str28\"/" build.gradle
+            sedi "s/applicationId \"us\.cash\"/applicationId \"$str28\"/" build.gradle
             if [[ $? -ne 0 ]]; then
-                echo "KO 88796"
+                >&2 echo "KO 88796"
                 exit 1
             fi
-            sed -i "s#versionName \"0 28/03/2017\"#versionName \"$core0_version_name $core0_build_date\"#" build.gradle
+            sedi "s#versionName \"0 28/03/2017\"#versionName \"$core0_version_name $core0_build_date\"#" build.gradle
             if [[ $? -ne 0 ]]; then
-                echo "KO 88797"
+                >&2 echo "KO 88797"
                 exit 1
             fi
-            sed -i "s#versionCode 6#versionCode $core0_version_code#" build.gradle
+            sedi "s#versionCode 6#versionCode $core0_version_code#" build.gradle
             if [[ $? -ne 0 ]]; then
-                echo "KO 88798"
+                >&2 echo "KO 88798"
                 exit 1
             fi
             pushd src > /dev/null
                 find . -type f -name "*.java" -exec sed -i "s/package us\.cash;/package $str28;/g" {} \;
                 find . -type f -name "*.java.in" -exec sed -i "s/package us\.cash;/package $str28;/g" {} \;
-                sed -i "s/android:value=\"us\.cash\./android\:value=\"$str28./g" main/AndroidManifest.xml.in
+                sedi "s/android:value=\"us\.cash\./android\:value=\"$str28./g" main/AndroidManifest.xml.in
                 find . -type f -name "*.xml" -exec sed -i "s/us\.cash\./$str28./g" {} \;
                 pushd main/java  > /dev/null
-                    pkgdir=`echo $str28 | sed "s#\.#/#g"`
-                    if [ ! -d $pkgdir ]; then
+                    pkgdir=$(echo $str28 | sed "s#\.#/#g")
+                    if [[ ! -d $pkgdir ]]; then
                         mkdir tmp
                         mv us/cash/* tmp/
                         rm us* -r
                         mkdir -p $pkgdir
                         mv tmp/* $pkgdir/
-            rmdir tmp
+                        rmdir tmp
                     fi
                 popd > /dev/null
             popd > /dev/null
@@ -189,12 +191,12 @@ tf=$(mktemp /tmp/override_env.XXXXXX)
 echo "" > $tf
 
 #just to pick the brand name
-if [ -f $branddir/en-uk ]; then
+if [[ -f $branddir/en-uk ]]; then
     echo "overriding env"
     . $branddir/en-uk
 else
-    echo "KO 50095 en-uk missing"
-    rm $tf -f
+    >&2 echo "KO 50095 en-uk missing"
+    rm -f $tf
     exit 1
 fi
 brand=$str3
@@ -203,41 +205,41 @@ out=brand_$brand
 rm -rf $out
 mkdir $out
 pushd $out > /dev/null
-    url=`git config --get remote.origin.url`
+    url=$(git config --get remote.origin.url)
     git clone -b $branch --single-branch $url rep
-    if [ $? -ne 0 ]; then
-        echo "KO 50128 Invalid url or branch"
+    if [[ $? -ne 0 ]]; then
+        >&2 echo "KO 50128 Invalid url or branch"
         exit 1
     fi
     c0=rep/core0
     pushd $c0/us > /dev/null
-    . res/strings/en-uk
-        if [ -f $branddir/en-uk ]; then
+        . res/strings/en-uk
+        if [[ -f $branddir/en-uk ]]; then
             echo "overriding env"
             bin/override_env res/strings/en-uk $branddir/en-uk > $tf
         else
-            echo "KO 7040"
+            >&2 echo "KO 7040"
             rm -f $tf
             exit 1
         fi
     popd > /dev/null
     . $tf
-    if [ $dbg -eq 1 ]; then
+    if [[ $dbg -eq 1 ]]; then
         str29=1
     else
         str29=0
     fi
-    if [ $logs -eq 1 ]; then
+    if [[ $logs -eq 1 ]]; then
         str33=1
     else
         str33=0
     fi
-    if [ $counters -eq 1 ]; then
+    if [[ $counters -eq 1 ]]; then
         str41=1
     else
         str41=0
     fi
-    if [ $connlog -eq 1 ]; then
+    if [[ $connlog -eq 1 ]]; then
         str42=1
     else
         str42=0
@@ -255,9 +257,9 @@ pushd $out > /dev/null
         popd > /dev/null
     popd > /dev/null
     echo "patch core"
-    patch_core $branddir $c0
+    patch_core "$branddir" "$c0"
     echo "patch android"
-    patch_android $branddir $c0
+    patch_android "$branddir" "$c0"
     rm rep/.git -rf
     mv $c0/us .
     rm rep -r
diff --git a/core0/us/bin/configure b/core0/us/bin/configure
--- a/core0/us/bin/configure
+++ b/core0/us/bin/configure
@@ -22,6 +22,8 @@
 #===----------------------------------------------------------------------------
 #===-
 
+. lib/shenv
+
 function banner {
     cat << EOF
 ----------------------------------------------
@@ -42,10 +44,9 @@ fi
 . res/strings/$strset
 androidname0=${str28}
 
-#api_v override 
+#api_v override
 let api_v_gov0=${str97}
 let api_v_wallet0=${str98}
-
 
 if [[ -f res/strings/${strset}.ovr ]]; then
     echo "found override string set"
@@ -134,7 +135,7 @@ done
 function findbrand {
     d=$1
     if [[ -d $d ]]; then
-        n=`find $d -maxdepth 1 -mindepth 1 -type d | wc -l`
+        n=$(find $d -maxdepth 1 -mindepth 1 -type d | wc -l)
         if [[ $n -eq 1 ]]; then
             branddir=`find $d -maxdepth 1 -mindepth 1 -type d`
             echo "selecting existing brand at $branddir"
@@ -151,7 +152,7 @@ fi
 
 if [[ "_$branddir" != "_" ]]; then
     if [[ ! -d $branddir ]]; then
-        echo "brand $branddir not found"
+        >&2 echo "KO 49441 brand $branddir not found."
         exit 1
     fi
     cp $branddir/${strset} res/strings/${strset}.ovr
@@ -168,7 +169,6 @@ fi
 if [[ -f res/strings/${strset}.ovr ]]; then
     . res/strings/${strset}.ovr
 fi
-
 
 if [[ $dbg -eq 1 ]]; then
     str29=1
@@ -221,13 +221,13 @@ if [[ ! -f res/strings/${strset}.ovr ]]; then
     cp res/strings/${strset} res/strings/${strset}.ovr
 fi
 
-sed -i "s/^str29=.*//" res/strings/${strset}.ovr
-sed -i "s/^str33=.*//" res/strings/${strset}.ovr
-sed -i "s/^str41=.*//" res/strings/${strset}.ovr
-sed -i "s/^str42=.*//" res/strings/${strset}.ovr
-sed -i "s/^str45=.*//" res/strings/${strset}.ovr
-sed -i "s/^str62=.*//" res/strings/${strset}.ovr
-sed -i "s/^str83=.*//" res/strings/${strset}.ovr
+sedi "s/^str29=.*//" res/strings/${strset}.ovr
+sedi "s/^str33=.*//" res/strings/${strset}.ovr
+sedi "s/^str41=.*//" res/strings/${strset}.ovr
+sedi "s/^str42=.*//" res/strings/${strset}.ovr
+sedi "s/^str45=.*//" res/strings/${strset}.ovr
+sedi "s/^str62=.*//" res/strings/${strset}.ovr
+sedi "s/^str83=.*//" res/strings/${strset}.ovr
 
 echo "str29=$str29 #dbg" >> res/strings/${strset}.ovr
 echo "str33=$str33 #logs" >> res/strings/${strset}.ovr
@@ -241,9 +241,9 @@ cat res/strings/${strset}.ovr | grep -v "^$" > res/strings/${strset}.ovr_
 mv res/strings/${strset}.ovr_ res/strings/${strset}.ovr
 
 function checkbin {
-    which make
+    which ${make}
     if [[ $? -ne 0 ]]; then
-        echo "KO 44921 run bin/apt first"
+        >&2 echo "KO 44921 ${make} not found. run bin/apt first"
         exit 1
     fi
 }
@@ -254,8 +254,8 @@ let warngit=0
 function gen_api {
     echo "generating RPC-API code snippets "
     pushd api > /dev/null
-        make clean
-        make -j8
+        ${make} clean
+        ${make} -j${jobs}
     popd > /dev/null
     echo ""
 
@@ -268,11 +268,11 @@ function gen_api {
     if [[ ${api_v_gov0} -ne ${api_v_gov} ]]; then
         if [[ $gitenv == 1 ]]; then
             echo "Updating strset with gov api versioning info ${api_v_gov0} -> ${api_v_gov}"
-            sed -i "s/^str97=[0-9]*/str97=${api_v_gov}/" res/strings/${strset}
+            sedi "s/^str97=[0-9]*/str97=${api_v_gov}/" res/strings/${strset}
             let api_v_gov0=$api_v_gov
             let warngit=1
         else
-            echo "KO 79588 Inconsistency in gov RPC-API versions."
+            >&2 echo "KO 79588 Inconsistency in gov RPC-API versions."
             exit 1
         fi
     fi
@@ -280,11 +280,11 @@ function gen_api {
     if [[ ${api_v_wallet0} -ne ${api_v_wallet} ]]; then
         if [[ $gitenv == 1 ]]; then
             echo "Updating strset with wallet api versioning info ${api_v_wallet0} -> ${api_v_wallet}"
-            sed -i "s/^str98=[0-9]*/str98=${api_v_wallet}/" res/strings/${strset}
+            sedi "s/^str98=[0-9]*/str98=${api_v_wallet}/" res/strings/${strset}
             let api_v_wallet0=$api_v_wallet
             let warngit=1
         else
-            echo "KO 79589 Inconsistency in wallet RPC-API versions."
+            >&2 echo "KO 79589 Inconsistency in wallet RPC-API versions."
             exit 1
         fi
     fi
@@ -322,7 +322,7 @@ patch_sdk_src_file2() {
     fi
     n=`cat ${file}_old | wc -l`
     dst=${file}
-    indent=`cat ${file}_old | grep "^ *//#include <us/$origfile>" | sed "s~^\( *\)//.*~\1~"`
+    indent=$(cat ${file}_old | grep "^ *//#include <us/$origfile>" | sed "s~^\( *\)//.*~\1~")
     cat ${file}_old | grep "^ *//#include <us/$origfile>" -B$n > $dst
     if [[ $? -ne 0  ]]; then
         echo "write to ${dst} failed. permissions?"
@@ -357,7 +357,7 @@ patch_sdk_src() {
     echo "patching sdk sources"
     usdir="."
     pfx="$usdir/sdk/wallet/java"
-    files=`find $pfx/us -name "*.java" -exec grep -H "^ *//#include " {} \; | tr ':' ' ' | awk '{print $1}' | sort | uniq`
+    files=$(find $pfx/us -name "*.java" -exec grep -H "^ *//#include " {} \; | tr ':' ' ' | awk '{print $1}' | sort | uniq)
     for f in $files; do
         patch_sdk_src_file $f
     done
@@ -365,7 +365,7 @@ patch_sdk_src() {
 
 function configure_sdk {
     if [[ ! -f vcs_git_java ]]; then
-        echo "KO 89345 failed vcs_git_java"
+        >&2 echo "KO 89345 failed vcs_git_java"
         exit 1
     fi
     progress_reset
@@ -373,11 +373,15 @@ function configure_sdk {
     usdir="."
     pfx="$usdir/sdk/wallet/java"
     sedregex="s/^import org.spongycastle./import org.bouncycastle./g"
-    find $pfx/us/gov/crypto -name "*.java" -exec sed -i "$sedregex" {} \;
+    for f in $(find $pfx/us/gov/crypto -name "*.java"); do
+        sedi "$sedregex" $f
+    done
     progress
-    find $pfx/test/us/gov/crypto -name "*.java" -exec sed -i "$sedregex" {} \;
+    for f in $(find $pfx/test/us/gov/crypto -name "*.java"); do
+        sedi "$sedregex" $f
+    done
     progress
-    sed -i "$sedregex" $pfx/us/gov/socket/datagram.java
+    sedi "$sedregex" $pfx/us/gov/socket/datagram.java
     progress
     rm -f sdk/wallet/java/selected_cryptosuite
     echo ""
@@ -403,16 +407,18 @@ function progress {
 function patch {
     ifile="${1}.in"
     ofile=$1
+#echo "patch $ifile $ofile"
+
     if [[ "_$2" != "_" ]]; then
         #echo "$1 -> $2"
         ofile=$2
     fi
     cp $ifile $ofile
-    strs=`cat $ifile  | grep -o "##str[0-9]*##" | sed "s/#//g"`
+    strs=$(cat $ifile  | grep -o "##str[0-9]*##" | sed "s/#//g")
     for s in $strs; do
         progress
         # echo -n "$s = ${!s}; "
-        sed -i "s%##$s##%${!s}%g" $ofile
+        sedi "s%##$s##%${!s}%g" $ofile
     done
     progress
 }
@@ -425,7 +431,7 @@ function patchin {
 
 function reroot {
     if [[ "_$1" != "_$2" ]]; then
-        cp $1 $2 -R
+        cp -r $1 $2
     fi
     progress
 }
@@ -445,6 +451,7 @@ progress_reset
 javapkgdir=`echo $str28 | sed "s#\.#/#g"`
 echo "java_pkg_dir: $javapkgdir"
 echo "processing .in files "
+
 patch raspbian/make
 patch raspbian/10-us/files/rc.local
 patch etc/motd etc/${str3}_motd
@@ -491,14 +498,13 @@ patch etc/nginx/conf.d/us-hidden.conf etc/nginx/conf.d/${str3}-hidden.conf
 patch snippet/distr_makefile snippet/${str3}_distr_makefile
 patch android/app/src/main/AndroidManifest.xml
 if [[ $appstore -eq 1 ]]; then
-    sed -i "s~<uses-permission android:name=\"android.permission.REQUEST_INSTALL_PACKAGES\" />~~" android/app/src/main/AndroidManifest.xml
+    sedi "s~<uses-permission android:name=\"android.permission.REQUEST_INSTALL_PACKAGES\" />~~" android/app/src/main/AndroidManifest.xml
 fi
 patch android/bin/sign_apk
-for f in `find android/app/src/main/java -name CFG.java.in`; do
+for f in $(find android/app/src/main/java -name CFG.java.in); do
     patchin $f
 done
 patch sdk/wallet/java/us/CFG.java
-#patch android/app/build.gradle
 patch api/config.h
 patch Doxyfile
 patch test/makefile
@@ -522,7 +528,7 @@ androidname=${str28}
 if [[ "_${androidname}" != "_${androidname0}" ]]; then
     if [[ $gitenv -eq 1 ]]; then
         echo "git environment: android app name remains ${androidname0}"
-        sed -i "s/package=\"${androidname}\"/package=\"${androidname0}\"/" android/app/src/main/AndroidManifest.xml
+        sedi "s/package=\"${androidname}\"/package=\"${androidname0}\"/" android/app/src/main/AndroidManifest.xml
         androidname=${androidname0}
     fi
 fi
@@ -530,7 +536,7 @@ fi
 echo "VCS"
 bin/gen_vcs_git
 if [[ ! -f vcs_git_env ]]; then
-    echo "KO 30219 configure finished with error."
+    >&2 echo "KO 30219 configure finished with error."
     exit 1
 fi
 
@@ -551,15 +557,16 @@ echo ""
 echo "ANDROID"
 pushd android > /dev/null
     ./configure
-    if [ $? -ne 0 ]; then
-    exit 1
+    if [[ $? -ne 0 ]]; then
+        >&2 echo "KO 44938 "
+        exit 1
     fi
 popd > /dev/null
 
 echo ""
 echo "Instrumentation"
 let instr=$logs
-if [ $instr -eq 0 ]; then
+if [[ $instr -eq 0 ]]; then
     if [[ -f ../../.git/config ]]; then
         let instr=1
     fi
@@ -569,11 +576,11 @@ if [ $instr -eq 0 ]; then
     fi
 fi
 
-if [ $instr -eq 0 ]; then
+if [[ $instr -eq 0 ]]; then
      echo "stripping instrumentation code...";
      bin/strip .
-     if [ $? -ne 0 ]; then
-         echo "KO 66975 Strip failed"
+     if [[ $? -ne 0 ]]; then
+         >&2 echo "KO 66975 Strip failed"
          exit 1
      fi
 else
@@ -621,3 +628,4 @@ if [[ $warngit -eq 1 ]]; then
 fi
 
 exit 0
+
diff --git a/core0/us/bin/distr_make.in b/core0/us/bin/distr_make.in
--- a/core0/us/bin/distr_make.in
+++ b/core0/us/bin/distr_make.in
@@ -22,19 +22,32 @@
 #===----------------------------------------------------------------------------
 #===-
 
+###################################################################
+#blob location: tft_alpha-53_7-8d558b/core/x86_64/bin/tft_distr_make
+#pwd: -------------------------------------------^
+###################################################################
+
 distr=$1
 target=$2
 prefix=$3
 jaildir=$4
 
+if [[ ! -f ${distr}/lib/shenv ]]; then
+    >&2 pwd
+    >&2 echo "KO 69532 ${distr}/lib/shenv not found."
+    exit 1
+fi
+
+. ${distr}/lib/shenv
+
 JAILDIR=""
-if [ "_$jaildir" != "_" ]; then
+if [[ "_$jaildir" != "_" ]]; then
     mkdir -p $jaildir
     JAILDIR=$(realpath $jaildir)
 fi
 
-if [ "_$prefix" != "_" ]; then
-    if [ "_$JAILDIR" != "_" ]; then
+if [[ "_$prefix" != "_" ]]; then
+    if [[ "_$JAILDIR" != "_" ]]; then
         PREFIX=$JAILDIR$prefix #preix must be absolute dir
     else
         PREFIX=$(realpath $prefix)
@@ -82,14 +95,14 @@ function clean_deprecated {
 function regenerate_motd {
     cat etc/motd_hdr > $JAILDIR/etc/motd
     while read -r line; do
-        us=`echo $line | awk '{print $2}'`
-        if [ -f $JAILDIR/var/${us}_motd ]; then
+        us=$(echo $line | awk '{print $2}')
+        if [[ -f $JAILDIR/var/${us}_motd ]]; then
             cat $JAILDIR/var/${us}_motd >> $JAILDIR/etc/motd
         fi
     done < $JAILDIR/var/us_nets
 }
 
-if [ "_$target" == "_" ]; then
+if [[ "_$target" == "_" ]]; then
     echo "$0 <dist dir> <install|install-nginx|install-system-base> <prefix> <jaildir>"
     echo "  defaults: prefix=<jaildir>/usr/local"
     echo "            jaildir=\"\""
@@ -97,7 +110,7 @@ fi
 
 function init_jail {
     if [[ "_${JAILDIR}" == "_" ]]; then
-        echo "KO 30178: jaildir init failed."
+        >&2 echo "KO 30178 jaildir init failed."
         exit 1
     fi
     if [[ -f /home/${GOVUSER}/.${US}/config ]]; then
@@ -137,10 +150,10 @@ function init_jail {
         cp /var/${US}/ush_config ${JAILDIR}/var/${US}/
     fi
     if [[ -f ${JAILDIR}/var/us_nets ]]; then
-        ch=`cat ${JAILDIR}/var/us_nets | grep " $blob_brand " | awk '{print $1}'`
-        if [ "_$ch" != "_" ]; then
+        ch=$(cat ${JAILDIR}/var/us_nets | grep " $blob_brand " | awk '{print $1}')
+        if [[ "_$ch" != "_" ]]; then
             ushome="/home/${GOVUSER}/.${US}"
-            if [ "_$ch" != "_0" ]; then
+            if [[ "_$ch" != "_0" ]]; then
                 ushome="$ushome/$ch"
             fi
             whome="$ushome/wallet"
@@ -164,9 +177,9 @@ if [[ "_${JAILDIR}" != "_" ]]; then
     init_jail
 fi
 
-if [ "_$target" == "_install" ]; then
+if [[ "_$target" == "_install" ]]; then
     mkdir -p ${JAILDIR}/tmp
-    pushd $distr > /dev/null
+    pushd ${distr} > /dev/null
         # pre/post-install-system-base
         echo "#!/bin/bash -x" > ${JAILDIR}/tmp/pre-install
         echo "#!/bin/bash -x" > ${JAILDIR}/tmp/post-install
@@ -258,7 +271,7 @@ EOF
         echo "written ${JAILDIR}${DATADIR0}/wallet/config"
 
         . ${JAILDIR}${DATADIR0}/config  #User selected channel now in env
-        if [ $CHANNEL -ne 0 ]; then
+        if [[ $CHANNEL -ne 0 ]]; then
             DATADIR=${DATADIR0}/${CHANNEL}
         else
             DATADIR=${DATADIR0}
@@ -266,8 +279,8 @@ EOF
         mkdir -p ${JAILDIR}${DATADIR}
 
         # seed nodes - /home/gov/.us[|/channel]/gov/nodes
-        if [ -f etc/nodes.distr${CHANNEL} ]; then
-            n=`cat etc/nodes.distr${CHANNEL} | wc -l`
+        if [[ -f etc/nodes.distr${CHANNEL} ]]; then
+            n=$(cat etc/nodes.distr${CHANNEL} | wc -l)
             echo "$n seed nodes"
             mkdir -p ${JAILDIR}${DATADIR}/gov
             cp etc/nodes.distr${CHANNEL} ${JAILDIR}${DATADIR}/gov/nodes.distr
@@ -309,8 +322,8 @@ EOF
 
         # post-install
         cat << EOF >> ${JAILDIR}/tmp/post-install
-chown ${GOVUSER}:${GOVUSER} /var/log/${US} -R
-chown ${GOVUSER}:${GOVUSER} ${DATADIR0} -R
+chown -R ${GOVUSER}:${GOVUSER} /var/log/${US}
+chown -R ${GOVUSER}:${GOVUSER} ${DATADIR0}
 EOF
 
         # exec post-install
@@ -327,7 +340,7 @@ EOF
     echo "done."
 fi
 
-if [ "_$target" == "_install-system-base" ]; then
+if [[ "_$target" == "_install-system-base" ]]; then
     mkdir -p ${JAILDIR}/tmp
     pushd $distr > /dev/null
         if [[ "_${JAILDIR}" == "_" ]]; then
@@ -344,7 +357,8 @@ if [ "_$target" == "_install-system-base" ]; then
         # system dependencies
         #
         if [[ ${TORSERVER} -eq 0 ]]; then
-            echo "systemctl stop tor" >> ${JAILDIR}/tmp/pre-install-system-base
+            write_systemctl stop tor >> ${JAILDIR}/tmp/pre-install-system-base
+            #echo "systemctl stop tor" >> ${JAILDIR}/tmp/pre-install-system-base
         fi
 
         # exec pre-install-system-base
@@ -425,7 +439,7 @@ EOF
         cat ${JAILDIR}$file | grep -v ".* #${US}" > $tf  #deprecate since alpha-29.20
         #cat ${JAILDIR}$file | grep -v ".* #${US}-distr_make" > $tf
         if [[ ${SSH_DEV} -eq 1 ]]; then
-            let n22=`cat $tf | grep "^Port 22" | wc -l`
+            let n22=$(cat $tf | grep "^Port 22" | wc -l)
             if [[ $n22 -eq 0 ]]; then
                 echo "Port 22 #${US}-distr_make" >> $tf  #leave 22 active if there wasn't any port specified already
             fi
@@ -434,7 +448,7 @@ EOF
         echo "PasswordAuthentication yes #${US}-distr_make" >> $tf
         mv $tf ${JAILDIR}$file
         echo "chmod 644 $file" >> ${JAILDIR}/tmp/post-install-system-base
-        echo "systemctl restart ssh" >> ${JAILDIR}/tmp/post-install-system-base
+        write_systemctl restart sshd >> ${JAILDIR}/tmp/post-install-system-base
 
         #
         # /etc/systemd
@@ -479,14 +493,8 @@ EOF
 
         # /home/gov/downloads
         mkdir -p ${JAILDIR}${GOVHOME}/downloads
-        echo "chown ${GOVUSER}:${GOVUSER} ${GOVHOME}/ -R" >> ${JAILDIR}/tmp/post-install-system-base
-        echo "chown ${GOVUSER}:${GOVUSER} ${GOVHOME}/.[^.]* -R" >> ${JAILDIR}/tmp/post-install-system-base
-        #TODO remove this fix. v alpha-29.20 chowned gov all dirs under /home
-        for f in `find /home -maxdepth 1 -mindepth 1 -type d`; do
-           n=$(basename $f)
-           echo $n
-           echo "chown $n.$n /home/$n -R" >> ${JAILDIR}/tmp/post-install-system-base
-        done
+        echo "chown -R ${GOVUSER}:${GOVUSER} ${GOVHOME}/" >> ${JAILDIR}/tmp/post-install-system-base
+        echo "chown -R ${GOVUSER}:${GOVUSER} ${GOVHOME}/.[^.]*" >> ${JAILDIR}/tmp/post-install-system-base
 
         #echo "chown ${GOVUSER}.${GOVUSER} ${GOVHOME}/downloads -R" >> ${JAILDIR}/tmp/post-install-system-base
         #echo "chown ${GOVUSER}.${GOVUSER} ${GOVHOME}/.bash_aliases" >> ${JAILDIR}/tmp/post-install-system-base
@@ -548,8 +556,8 @@ EOF
 
             cat << EOF >> ${JAILDIR}/tmp/post-install-system-base
 chmod 700 -R /var/lib/tor/${US}_hidden
-chown debian-tor:debian-tor /var/lib/tor/${US}_hidden -R
-systemctl restart tor
+chown -R debian-tor:debian-tor /var/lib/tor/${US}_hidden
+$(write_systemctl restart tor)
 EOF
         else
 
@@ -568,7 +576,7 @@ EOF
         #TODO: not overwrite existing conf if pinned
         let rewrite_http_conf=1
         if [[ -f ${JAILDIR}/etc/nginx/sites-available/${US}.conf ]]; then
-            au=`cat ${JAILDIR}/etc/nginx/sites-available/${US}.conf | grep "^#--${US}: AUTOUPDATE " | sed "s/.*AUTOUPDATE \([01]\).*/\1/"`
+            au=$(cat ${JAILDIR}/etc/nginx/sites-available/${US}.conf | grep "^#--${US}: AUTOUPDATE " | sed "s/.*AUTOUPDATE \([01]\).*/\1/")
             if [[ "_$au" == "_0" ]]; then
                 let rewrite_http_conf=0
             fi
@@ -614,9 +622,9 @@ EOF
         rm $tf
 
         cat << EOF >> ${JAILDIR}/tmp/post-install-system-base
-chown ${GOVUSER}:${GOVUSER} /var/log/${US} -R
+chown -R ${GOVUSER}:${GOVUSER} /var/log/${US}
 systemctl enable nginx
-systemctl restart nginx
+$(write_systemctl restart nginx)
 if [[ -f /usr/sbin/ldconfig ]]; then
     /usr/sbin/ldconfig
 else
@@ -639,7 +647,7 @@ EOF
     popd > /dev/null
 fi
 
-if [ "_$target" == "_install-dev" ]; then
+if [[ "_$target" == "_install-dev" ]]; then
     pushd $distr > /dev/null
         echo "PREFIX=${PREFIX}"
         echo "INCDIR=${INCDIR}"
diff --git a/core0/us/bin/gen_http_nodes b/core0/us/bin/gen_http_nodes
--- a/core0/us/bin/gen_http_nodes
+++ b/core0/us/bin/gen_http_nodes
@@ -40,7 +40,7 @@ shift
 
 if [[ "_$cmd" != "_scan" ]]; then
     help
-    echo "KO 86875 Invalid command."
+    >&2 echo "KO 86875 Invalid command."
     exit 1
 fi
 
@@ -48,7 +48,7 @@ nodes0=/tmp/nodes0
 if [[ ! -f $nodes0 ]]; then
     echo "Finding all nodes with http port open"
     echo "" > $nodes0
-    for h in `cat etc/nodes.distr0 | sed 's/72$/80/'`; do
+    for h in $(cat etc/nodes.distr0 | sed 's/72$/80/'); do
         cmd="timeout 10 wget -t 1 --quiet --connect-timeout=2 -O - $h"
         echo "Exec: $cmd"
         eval $cmd > /dev/null
@@ -68,13 +68,13 @@ if [[ "_$US" == "_" ]]; then
 	exit 0
 fi
 
-httpnodes="`cat $nodes0 | shuf | xargs` "
+httpnodes="$(cat $nodes0 | shuf | xargs) "
 echo "httpnodes=$httpnodes"
 file="/tmp/nodes_${US}"
 echo "" > $file
 while [[ true ]]; do
-    httpnode=`echo $httpnodes | tr ' ' '\n' | head -n1`
-    httpnodes=`echo "$httpnodes" | sed "s#$httpnode ##"`
+    httpnode=$(echo $httpnodes | tr ' ' '\n' | head -n1)
+    httpnodes=$(echo "$httpnodes" | sed "s#$httpnode ##")
     echo "httpnode=$httpnode"
     if [ "_$httpnode" == "_" ]; then
         break
@@ -92,7 +92,7 @@ while [[ true ]]; do
         echo "${httpnode} hasn't ${US}"
         continue;
     fi
-    curhash=`cat curhash`
+    curhash=$(cat curhash)
     rm curhash
     echo "======================================${httpnode} has ${US}"
     echo "$httpnode" >> $file
@@ -100,7 +100,7 @@ done
 rm -f curhash
 echo "${US} nodes:"
 echo -n "str67=\""
-v=`cat $file | sort | xargs`
+v=$(cat $file | sort | xargs)
 echo -n $v
 echo "\" #Seeds; Use bin/gen_http_nodes"
 
diff --git a/core0/us/bin/gen_pub b/core0/us/bin/gen_pub
--- a/core0/us/bin/gen_pub
+++ b/core0/us/bin/gen_pub
@@ -23,21 +23,21 @@
 #===-
 
 function symlink {
-  src=$1
-  dst=$2
-  if [ "_$dst" == "_" ]; then
-     f=$(basename $src)
-     rm -f $f
-  else
-      rm -f $dst
-  fi
-  ln -s $src $dst
+    src=$1
+    dst=$2
+    if [[ "_$dst" == "_" ]]; then
+        f=$(basename $src)
+        rm -f $f
+    else
+        rm -f $dst
+    fi
+    ln -s $src $dst
 }
 
 o=""
 sep="======================================================"
 function fun {
-    ts=`date +"%Y-%m-%d_%H-%M-%S"`
+    ts=$(date +"%Y-%m-%d_%H-%M-%S")
     o="pub/$3.txt"
     echo "generation timestamp $ts" > $o
     echo "description: $1" >> $o
@@ -63,8 +63,8 @@ function update {
         pub=$pub/$ch
     fi
 
-    if [ $CHANNEL -ne $ch ]; then
-        echo "KO 59995 config problem. channel do not match."
+    if [[ $CHANNEL -ne $ch ]]; then
+        >&2 echo "KO 59995 config problem. channel do not match."
         return
     fi
 
@@ -101,17 +101,17 @@ function update {
     $gov version > $pub/version.txt
 }
 
-if [ ! -f /var/us_nets ]; then
-    echo "KO 59253 cannot find file /var/us_nets"
+if [[ ! -f /var/us_nets ]]; then
+    >&2 echo "KO 59253 cannot find file /var/us_nets"
     exit 1
     return
 fi
 
 while read -r line; do
-    US=`echo $line | awk '{print $2}'`
-    addr=`echo $line | awk '{print $3}'`
-    key=`echo $line | awk '{print $4}'`
-    ch=`echo $line | awk '{print $1}'`
+    US=$(echo $line | awk '{print $2}')
+    addr=$(echo $line | awk '{print $3}')
+    key=$(echo $line | awk '{print $4}')
+    ch=$(echo $line | awk '{print $1}')
     update $US $addr $key $ch
 done < /var/us_nets
 
diff --git a/core0/us/bin/gen_vcs_git b/core0/us/bin/gen_vcs_git
--- a/core0/us/bin/gen_vcs_git
+++ b/core0/us/bin/gen_vcs_git
@@ -29,7 +29,7 @@ if [[ "_$modfiles" != "_" ]]; then
     if [[ -f $modfiles ]]; then
         cat $modfiles
     else
-        echo "KO 65834 file not found."
+        >&2 echo "KO 65834 file not found."
         exit 1
     fi
 fi
@@ -42,17 +42,17 @@ gitdir=""
 devjobtag=""
 if [[ -f ../../.revs ]]; then
     . ../../.revs
-    devjob=`echo "$devjob_id" | grep "devjob_" | sed "s/devjob_\(.*\)/\1/"`
-    devjobtag="dj`echo $upstream_hash | cut -c1-8`_"
+    devjob=$(echo "$devjob_id" | grep "devjob_" | sed "s/devjob_\(.*\)/\1/")
+    devjobtag="dj$(echo $upstream_hash | cut -c1-8)_"
 fi
 gitdir="../../.git"
 
 locally_modified=""
 if [[ -d $gitdir ]]; then
     echo "git environment"
-    branch=`git branch | grep '*' | awk '{print $NF}'`
-    revhash=`git log | head -n1 | awk '{print $2}'`
-    let nl=`git diff --name-only | grep -v us/sdk/wallet/java/us/vcs.java | wc -l`
+    branch=$(git branch | grep '*' | awk '{print $NF}')
+    revhash=$(git log | head -n1 | awk '{print $2}')
+    let nl=$(git diff --name-only | grep -v us/sdk/wallet/java/us/vcs.java | wc -l)
     echo -n "Local modifications: "
     if [[ $nl -gt 0 ]]; then
         echo "Yes."
@@ -65,27 +65,27 @@ else
         echo "Not in git environment. Found existing vcs_git files."
         exit 0
     else
-        echo "KO 60908 Not in a git environment. vcs_git_env not found. Abort."
+        >&2 echo "KO 60908 Not in a git environment. vcs_git_env not found. Abort."
         exit 1
     fi
 fi
 echo "generating vcs_git files $locally_modified"
-bdate=`date +%Y-%m-%d_%H-%M-%S`
-vcode=`date +%y%m%d%H`
+bdate=$(date +%Y-%m-%d_%H-%M-%S)
+vcode=$(date +%y%m%d%H)
 #if [[ "_$vcode" == "_22081115" ]]; then
 #    vcode="22081116"  #needed for a google play upload retry in the same hour
 #fi
-if [ -f res/strings/en-uk.ovr ]; then
-    cfghash=`sha256sum res/strings/en-uk.ovr $modfiles | sha256sum | awk '{print $1}'`
+if [[ -f res/strings/en-uk.ovr ]]; then
+    cfghash=$(sha256sum res/strings/en-uk.ovr $modfiles | sha256sum | awk '{print $1}')
 else
     if [[ "_$modfiles" == "_" ]]; then
         cfghash="0"
     else
-        cfghash=`sha256sum $modfiles | awk '{print $1}'`
+        cfghash=$(sha256sum $modfiles | awk '{print $1}')
     fi
 fi
-codehashname=`echo $revhash |  cut -c1-6`$locally_modified
-cfghashname=`echo $cfghash |  cut -c1-6`
+codehashname=$(echo $revhash |  cut -c1-6)$locally_modified
+cfghashname=$(echo $cfghash |  cut -c1-6)
 hashname="$codehashname.$cfghashname"
 if [[ "_$override_hashname" != "_" ]]; then
     hashname=$override_hashname
@@ -137,4 +137,3 @@ std::string us::vcs::build_date = "$core0_build_date";
 EOF
 echo "generated file vcs_git_cpp"
 exit 0
-
diff --git a/core1/bde_setup/bde_data/wallet/bin/hook b/core1/bde_setup/bde_data/wallet/bin/hook
--- a/core1/bde_setup/bde_data/wallet/bin/hook
+++ b/core1/bde_setup/bde_data/wallet/bin/hook
@@ -22,39 +22,58 @@
 #===----------------------------------------------------------------------------
 #===-
 
-brand=linkbox
 cmd=$1
 shift
+
+if [[ ! -f /var/us_nets ]]; then
+    echo "KO 78699 install node software first."
+    exit 1
+fi
+
+brand=$(cat /var/us_nets | awk '{print $2}')
+if [[ $? -ne 0 ]]; then
+    echo "KO 78669 /var/us_nets is in a bad state."
+    exit 1
+fi
+
 function new_wallet {
     template=$1
     tgtdir=$2
     sk=$3
-    name="Dr. Anonymous Doctor"
-    if [[ ! -d $template ]]; then
-        echo "KO 86753 missing dir template/$template"
-        exit 1
-    fi
-    mkdir -p $tgtdir
-    cp $template/* $tgtdir/ -R
-    r=$?
-    if [[ $r -ne 0 ]]; then
-        pwd
-        echo "KO 67588 copy failed: cp $template/* $tgtdir/ -R"
-    fi
-    if [[ -d $tgtdir/trader ]]; then
-        f=`find $tgtdir/trader -name "params_private.in"`
-        for file in $f; do
-            nfn=`echo "$tgtdir/params_private.in" |  sed "s~params_private\.in\$~params_private~"`
-            mv $file $nfn
-            sed -i "s/##personality_sk##/${sk}/" $nfn
-        done
+    if [[ "_$template" != "_-" ]]; then
+        if [[ ! -d $template ]]; then
+            echo "KO 86753 missing dir template/$template" | tee -a /var/log/${brand}/hook_new_wallet
+            exit 1
+        fi
+        t=$(basename $template)
+        pdir=$(dirname $template)
+        tinputdir="${pdir}-input"
+        name=$(cat $tinputdir/$t/name)
 
-        f=`find $tgtdir/trader -name "name.in"`
-        for file in $f; do
-            nfn=`echo "$tgtdir/name.in" |  sed "s~name\.in\$~name~"`
-            mv $file $nfn
-            sed -i "s/##name##/${name}/" $nfn
-        done
+        mkdir -p ${tgtdir}
+        cp -rp ${template}/* ${tgtdir}/
+        r=$?
+        if [[ $r -ne 0 ]]; then
+            pwd | tee -a /var/log/${brand}/hook_new_wallet
+            echo "KO 67588 copy failed: cp -rp ${template}/* ${tgtdir}/" | tee -a /var/log/${brand}/hook_new_wallet
+        fi
+        if [[ -d $tgtdir/trader ]]; then
+            f=$(find $tgtdir/trader -name "params_private.in")
+            for file in $f; do
+                nfn=$(echo "$file" | sed "s~params_private\.in~params_private~")
+                mv $file $nfn
+                echo "    params_private -> $nfn" >> /var/log/${brand}/hook_new_wallet
+                sed -i "s/##personality_sk##/${sk}/" $nfn
+            done
+
+            f=$(find $tgtdir/trader -name "name.in")
+            for file in $f; do
+                nfn=$(echo "$file" |  sed "s~name\.in~name~")
+                mv $file $nfn
+                echo "    name -> $nfn" >> /var/log/${brand}/hook_new_wallet
+                sed -i "s/##name##/${name}/" $nfn
+            done
+        fi
     fi
     echo "$template $tgtdir $r" >> /var/log/${brand}/hook_new_wallet
     exit $r
@@ -64,7 +83,9 @@ if [[ "_$cmd" == "_new_wallet" ]]; then
     template=$1
     tgtdir=$2
     sk=$3
+    echo "new_wallet $template $tgtdir *****" >> /var/log/${brand}/hook_new_wallet
     new_wallet $template $tgtdir $sk
 fi
 echo "KO 86752 invalid cmd $cmd"
 exit 1
+
diff --git a/core1/bde_setup/mk_bde b/core1/bde_setup/mk_bde
--- a/core1/bde_setup/mk_bde
+++ b/core1/bde_setup/mk_bde
@@ -25,12 +25,210 @@
 # Flush DNS cache: systemd-resolve --flush-caches
 #
 
+function help {
+    echo "sets up BDE (Brand Distribution End)"
+    echo "Requies ports 53, 80, and 443 opened."
+}
+
+function bindzones {
+    tf=$(mktemp /tmp/mk_bde_bindzones.XXXXXX)
+
+    # .bashrc - include command aliases
+    file=/etc/bind/named.conf.local
+    cat $file | grep -v ".*--${US}" > $tf
+    cat << EOF >> $tf
+    zone "${domain}" {                       //--${US}
+        type master;                        //--${US}
+        file "/etc/bind/zones/db.${domain}"; //--${US}
+    };                                      //--${US}
+                                            //--${US}
+EOF
+    echo "New file $file"
+    cat $file
+    echo "New file /etc/bind/zones/db.${domain}"
+    cat bde_data/bind/db.${domain}
+    if [[ -f $file ]]; then
+        echo "<<<<<<<<<< diff $file"
+        diff $file $tf
+        echo "<<<<<<<<<< diff $file"
+    fi
+    if [[ -f /etc/bind/zones/db.${domain} ]]; then
+        echo "<<<<<<<<<< diff /etc/bind/zones/db.${domain}"
+        diff /etc/bind/zones/db.${domain} bde_data/bind/db.${domain}
+        echo "<<<<<<<<<< diff /etc/bind/zones/db.${domain}"
+    fi
+    echo -n "Install bind files? [y/n]: "
+    read a
+    if [[ "_$a" != "_y" ]]; then
+        return
+    fi
+
+    mv $tf $file
+
+    chgrp bind $file
+    chmod 644 $file
+
+    mkdir -p /etc/bind/zones/
+    if [[ -f /etc/bind/zones/db.${domain} ]]; then
+        echo "Replacing /etc/bind/zones/db.${domain}"
+    fi
+    cp bde_data/bind/db.${domain} /etc/bind/zones/
+
+    rndc reload
+    if [[ $? -ne 0 ]]; then
+        echo "KO 78109 bind didnt reload."
+        exit 1
+    fi
+}
+
+function nginx_conf {
+    if [[ -f /etc/nginx/sites-available/${domain} ]]; then
+        echo "old /etc/nginx/sites-available/${domain}"
+        cat /etc/nginx/sites-available/${domain}
+        echo "new /etc/nginx/sites-available/${domain}"
+        cat bde_data/nginx/sites-available/${domain}
+        echo "<<<<<<<<<<<<< /etc/nginx/sites-available/${domain}"
+        diff /etc/nginx/sites-available/${domain} bde_data/nginx/sites-available/${domain}
+        echo "<</<<<<<<<<<< /etc/nginx/sites-available/${domain}"
+    fi
+    echo -n "Install nginx conf files? [y/n]: "
+    read a
+    if [[ "_$a" != "_y" ]]; then
+        return
+    fi
+    if [[ ! -f /etc/nginx/sites-available/${domain} ]]; then
+        cp bde_data/nginx/sites-available/${domain} /etc/nginx/sites-available/
+        pushd /etc/nginx/sites-enabled > /dev/null
+            ln -s /etc/nginx/sites-available/${domain}
+        popd
+        systemctl reload nginx
+        if [[ $? -ne 0 ]]; then
+            echo "KO 78119 nginx didnt reload."
+            exit 1
+        fi
+    else
+        echo "KO 68577 function  nginx_conf not ready for rewrite"
+        exit 1
+    fi
+}
+
+function htmldocs {
+    echo -n "Install html? [y/n]: "
+    read a
+    if [[ "_$a" != "_y" ]]; then
+        return
+    fi
+    echo "Replacing html"
+    mkdir -p /var/www/html/${US}
+    rm -rf /var/www/html/${US}/* -R
+    cp bde_data/nginx/html/* /var/www/html/${US}/ -R
+}
+
+function certbotinst {
+    echo -n "Install certbot? [y/n]: "
+    read a
+    if [[ "_$a" != "_y" ]]; then
+        return
+    fi
+    if [[ ! -x /usr/bin/certbot ]]; then
+        apt -y install certbot
+    fi
+    ssl_email="$str2"
+
+    mkdir -p /var/log/${US}
+    echo "2>&1 certbot -a manual --preferred-challenges dns -m ${ssl_email} --agree-tos -i nginx -w /var/www/html/${US} --domains "${domain}"  | tee -a /var/log/${US}/certbotrun"
+
+    echo "=============================================="
+    echo "== depending on the following feedback from certbot, do manuall something like this:============================================"
+    cat << EOF
+    echo "_acme-challenge IN TXT Vpr6hXl983KrG26Q0pMXXrfTO2rsgwe0kpnXNYD-zX8" >> /etc/bind/zones/db.${domain}; let v=`cat /etc/bind/zones/db.${domain} | grep "; Serial" | awk '{ print $1 }'`; let v2=$v+1; sed -i "s~^\(\s*\)1\(\s*\); Serial~\1${v2}\2; Serial~" /etc/bind/zones/db.${domain}; rndc reload
+    dig +short TXT _acme-challenge.${domain}
+EOF
+    echo "=============================================="
+
+    2>&1 certbot -a manual --preferred-challenges dns -m ${ssl_email} --agree-tos -i nginx -w /var/www/html/${US} --domains "${domain}"  | tee -a /var/log/${US}/certbotrun
+}
+
+function walletconf_custodial {
+    if [[ $custodial_server -ne 1 ]]; then
+        return
+    fi
+    echo "Config custodial server"
+    su gov -c "${US}-wallet conf authorize_and_create_guest_wallet | grep \"authorize_and_create_guest_wallet 1\" > /dev/null"
+    if [[ $? -eq 1 ]]; then
+        echo "configuring wallet for creating guest wallets [conf authorize_and_create_guest_wallet=1]"
+        su gov -c "${US}-wallet conf authorize_and_create_guest_wallet 1"
+#        run as user gov: wallet conf authorize_and_create_guest_wallet 1
+    else
+        echo "wallet already configured [conf authorize_and_create_guest_wallet=1]"
+    fi
+}
+
+function rootwallet {
+    walletconf_custodial
+    echo -n "Install (rewrite) root wallet? [y/n]: "
+    read a
+    if [[ "_$a" != "_y" ]]; then
+        return
+    fi
+    pathtar=""
+    pushd bde_data > /dev/null
+        rm -f wallet.tgz
+        tar -czf wallet.tgz wallet
+        rm -f walletbase.tgz
+        tar -czf template_base.tgz template_base
+        pathtar="$(pwd)"
+    popd  > /dev/null
+    home=`su gov -c "${US}-gov print_home"`
+    if [[ $? -ne 0 ]]; then
+        echo "KO 78699"
+        return
+    fi
+    echo -n "extract wallet ($pathtar/wallet.tgz) into $home? [y/n]: "
+    read a
+    if [[ "_$a" != "_y" ]]; then
+        return
+    fi
+    pushd $home > /dev/null
+        tar -xzf $pathtar/wallet.tgz
+        for t in $(find wallet/template -maxdepth 1 -mindepth 1 -type d); do
+            pushd $t > /dev/null
+                tar -xzf $pathtar/template_base.tgz  
+                if [[ -d template_base ]]; then
+                    pushd template_base > /dev/null
+                        tar -czf ../x.tgz *
+                    popd > /dev/null
+                    rm -rf template_base
+                    tar -xzf x.tgz
+                    rm x.tgz
+                fi
+                if [[ -d wallet_template ]]; then
+                    pushd wallet_template > /dev/null
+                        tar -czf ../x.tgz *
+                    popd > /dev/null
+                    rm -rf wallet_template
+                    tar -xzf x.tgz
+                    rm x.tgz
+                fi
+            popd > /dev/null
+        done
+        chown gov:gov wallet -R
+    popd > /dev/null
+    echo  $home/wallet updated
+    echo -n "Restart wallet service? [y/n]: "
+    read a
+    if [[ "_$a" != "_y" ]]; then
+        return
+    fi
+    systemctl restart ${US}-wallet    
+}
+
 if [[ ! -f strset0 ]]; then
-    echo "KO 83092 Please use the parent program: bin/brand_tool upload_bde_setup"
+    echo "KO 83092 Please use the parent program: bin/brand_tool gen_bde_setup"
     exit 1
 fi
 if [[ ! -f strset ]]; then
-    echo "KO 83093 Please use the parent program: bin/brand_tool upload_bde_setup"
+    echo "KO 83093 Please use the parent program: bin/brand_tool gen_bde_setup"
     exit 1
 fi
 
@@ -38,23 +236,28 @@ fi
 . strset
 
 US="$str3"
+if [[ "_$US" == "_" ]]; then
+    echo "KO 67583 Invalid variable US"
+    exit 1
+fi
 
-domain=${str68}
-ssl_email="$str2"
+if [[ ! -f /var/us_nets ]]; then
+    echo "KO 83762 Install node before upgrading to bde"
+    exit 1
+fi
 
-function help {
-    echo "sets up BDE (Brand Distribution End)"
-    echo "Requies ports 53, 80, and 443 opened."
-}
+installed_us=`cat /var/us_nets | awk '{print $2}'`
 
-function undo {
-    oldstr68=""
-    rm -f /etc/bind/zones/db.${oldstr68}
-    rm -f /etc/nginx/sites-enabled/${oldstr68}
-    rm -f /etc/nginx/sites-available/${oldstr68}
-}
+if [[ ${installed_us} != ${US} ]]; then
+    echo "KO 83761 This package is only compatible with brand ${US}. Installed brand: ${installed_us}"
+    exit 1
+fi
 
-#======================bind
+su gov -c "${US}-wallet version"
+if [[ $? -ne 0 ]]; then
+    echo "KO 85774"
+    exit 1
+fi
 
 if [[ ! -f /etc/named/named.conf.local ]]; then
     apt -y install bind9 bind9-utils
@@ -63,84 +266,27 @@ if [[ ! -f /etc/bind/named.conf.local ]]; then
     echo "KO 78109 file /etc/bind/named.conf.local doesn't exist."
     exit 1
 fi
+domain=${str68}
 if [[ ! -f bde_data/bind/db.${domain} ]]; then
     echo "KO 78108 bde_data/db.${domain} doesn't exist."
     exit 1
 fi
 
-#temporary file
-tf=$(mktemp /tmp/distr_make.XXXXXX)
+bindzones
+nginx_conf
+htmldocs
+certbotinst
+rootwallet
 
-# .bashrc - include command aliases
-file=/etc/bind/named.conf.local
-cat $file | grep -v ".*--${US}" > $tf
-cat << EOF >> $tf
-zone "${domain}" {                       //--${US}
-    type master;                        //--${US}
-    file "/etc/bind/zones/db.${domain}"; //--${US}
-};                                      //--${US}
-                                        //--${US}
-EOF
-mv $tf $file
-
-chgrp bind $file
-chmod 644 $file
-
-mkdir -p /etc/bind/zones/
-if [[ -f /etc/bind/zones/bde_data/bind/db.${domain} ]]; then
-    echo "Replacing /etc/bind/zones/bde_data/bind/db.${domain}"
-fi
-cp bde_data/bind/db.${domain} /etc/bind/zones/
-
-rndc reload
-if [[ $? -ne 0 ]]; then
-    echo "KO 78109 bind didnt reload."
-    exit 1
-fi
-
-#======================nginx
-
-if [[ ! -x /usr/bin/certbot ]]; then
-    apt -y install certbot
-fi
-
-if [[ ! -f /etc/nginx/sites-available/${domain} ]]; then
-    cp bde_data/nginx/sites-available/${domain} /etc/nginx/sites-available/
-    pushd /etc/nginx/sites-enabled > /dev/null
-        ln -s /etc/nginx/sites-available/${domain}
-    popd
-    systemctl reload nginx
-    if [[ $? -ne 0 ]]; then
-        echo "KO 78119 nginx didnt reload."
-        exit 1
+if [[ ! -f /etc/bind/zones/db.${domain} ]]; then
+    echo "WARNING: /etc/bind/zones/db.${domain} doesn't exist!"
+else
+    if [[ $custodial_server -eq 1 ]]; then
+        cat /etc/bind/zones/db.${domain} | grep "custodial" > /dev/null
+        if [[ $? -ne 0 ]]; then
+            echo "WARNING: /etc/bind/zones/db.${domain} should contain an A record for 'custodial'."
+        fi
     fi
-fi
-
-if [[ "_$US" == "_" ]]; then
-    echo "KO 67583 Invalid variable US"
-    exit 1
-fi
-
-mkdir -p /var/www/html/${US}
-rm -rf /var/www/html/${US}/* -R
-cp bde_data/nginx/html/* /var/www/html/${US}/ -R
-
-mkdir -p /var/log/${US}
-echo "2>&1 certbot -a manual --preferred-challenges dns -m ${ssl_email} --agree-tos -i nginx -w /var/www/html/${US} --domains "${domain}"  | tee -a /var/log/${US}/certbotrun"
-
-echo "=============================================="
-echo "== depending on the following feedback from certbot, do manuall something like this:============================================"
-cat << EOF
-echo "_acme-challenge IN TXT Vpr6hXl983KrG26Q0pMXXrfTO2rsgwe0kpnXNYD-zX8" >> /etc/bind/zones/db.${domain}; let v=`cat /etc/bind/zones/db.${domain} | grep "; Serial" | awk '{ print $1 }'`; let v2=$v+1; sed -i "s~^\(\s*\)1\(\s*\); Serial~\1${v2}\2; Serial~" /etc/bind/zones/db.${domain}; rndc reload
-dig +short TXT _acme-challenge.${domain}
-EOF
-echo "=============================================="
-
-2>&1 certbot -a manual --preferred-challenges dns -m ${ssl_email} --agree-tos -i nginx -w /var/www/html/${US} --domains "${domain}"  | tee -a /var/log/${US}/certbotrun
-
-if [[ $custodial_server -eq 1 ]]; then
-    echo "==configure wallet for creating guest wallets============================================"
-    run as user gov: wallet conf authorize_and_create_guest_wallet 1
 fi
 
 exit 0
diff --git a/core1/bin/10_make_build_jobs b/core1/bin/10_make_build_jobs
--- a/core1/bin/10_make_build_jobs
+++ b/core1/bin/10_make_build_jobs
@@ -26,10 +26,12 @@ echo "########################"
 echo "## 10_make_build_jobs ##"
 echo "########################"
 
+. lib/shenv
+
 if [[ -f .cbs/config ]]; then
     . .cbs/config
 else
-	echo "KO 8585 Missing .cbs/config."
+	>&2 echo "KO 8585 Missing .cbs/config."
 	exit 1
 fi
 brands=`realpath $brands`
@@ -51,6 +53,7 @@ devjob=""
 
 echo "10_make_build_jobs $@"
 echo "initial release config"
+#------------------------------------------ args
 release=1
 debug=0
 logs=0
@@ -62,12 +65,11 @@ ignore_cache=0
 fcgi=0
 let batch=0
 let only_deps=0
-
 while [[ true ]]; do
     opt=$1
     shift
     if [[ "_$opt" == "_--release" ]]; then
-        echo "release flag"
+        #echo "release flag"
         debug=0
         release=1
         logs=0
@@ -75,7 +77,7 @@ while [[ true ]]; do
         connlog=0
         continue
     elif [[ "_$opt" == "_--debug" ]]; then
-        echo "debug flag"
+        #echo "debug flag"
         debug=1
         release=0
         logs=1
@@ -83,48 +85,48 @@ while [[ true ]]; do
         connlog=1
     continue
         elif [[ "_$opt" == "_--with-logs" ]]; then
-        echo "logs flag"
+        #echo "logs flag"
         logs=1
     continue
         elif [[ "_$opt" == "_--without-logs" ]]; then
-        echo "-logs flag"
+        #echo "-logs flag"
         logs=0
     continue
         elif [[ "_$opt" == "_--with-counters" ]]; then
-        echo "counters flag"
+        #echo "counters flag"
         counters=1
         continue
     elif [[ "_$opt" == "_--without-counters" ]]; then
-        echo "-counters flag"
+        #echo "-counters flag"
         counters=0
         continue
     elif [[ "_$opt" == "_--with-connlog" ]]; then
-        echo "connlog flag"
+        #echo "connlog flag"
         connlog=1
         continue
     elif [[ "_$opt" == "_--without-connlog" ]]; then
-        echo "-connlog flag"
+        #echo "-connlog flag"
         connlog=0
         continue
     elif [[ "_$opt" == "_--with-fcgi" ]]; then
-        echo "fcgi flag"
+        #echo "fcgi flag"
         fcgi=1
         continue
     elif [[ "_$opt" == "_--without-fcgi" ]]; then
-        echo "-fcgi flag"
+        #echo "-fcgi flag"
         fcgi=0
         continue
     elif [[ "_$opt" == "_--branch" ]]; then
-        echo "-branch flag"
+        #echo "-branch flag"
         branch=$1
         shift
         continue
     elif [[ "_$opt" == "_--ignore-cache" ]]; then
-        echo " [ignore cache]"
+        #echo " [ignore cache]"
         ignore_cache=1
         continue
     elif [[ "_$opt" == "_--test" ]]; then
-        echo "--test flag"
+        #echo "--test flag"
         test=1
         continue
     elif [[ "_$opt" == "_--help" ]]; then
@@ -133,7 +135,7 @@ while [[ true ]]; do
     elif [[ "_$opt" == "_-o" ]]; then
         bjdir=$1
         shift
-        echo "output flag -o=$bjdir"
+        #echo "output flag -o=$bjdir"
         continue
     elif [[ "_$opt" == "_--batch" ]]; then
         let batch=1
@@ -142,31 +144,35 @@ while [[ true ]]; do
         let only_deps=1
         continue
     elif [[ _$opt == _-* ]]; then
-        echo "KO 60594 Invalid flag $opt"
+        >&2 echo "KO 60594 Invalid flag $opt"
         help
         exit 1
     else
-        echo "end parsing flags"
+        #echo "end parsing flags"
         break
     fi
 done
-conf=$opt
+conf="$opt"
+#echo ">$conf<"
+
+#-/---------------------------------------- args
+
 if [[ "_$conf" == "_" ]]; then
-    help
-    echo "KO 69862 brand expected."
+    >&2 help
+    >&2 echo "KO 69862 quoted brands expected."
     exit 1
 fi
 
 if [[ "_$branch" == "_" ]]; then
-    help
-    echo "KO 38723 Invalid branch"
+    >&2 help
+    >&2 echo "KO 38723 Invalid branch"
     exit 1
 fi
 
 echo "--------------------------------------"
 echo "Input:"
 echo "  branch=$branch"
-echo "  brand=$conf"
+echo "  brands=$conf"
 echo ""
 echo "Flags:"
 echo "  release=$release"
@@ -181,6 +187,7 @@ echo "Output:"
 echo "  bjdir=$bjdir"
 echo "--------------------------------------"
 if [[ $batch -eq 0 ]]; then
+    echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: seeds! bin/gen_http_nodes"
     echo "yes?"
     read x
 fi
@@ -189,38 +196,35 @@ hash=""
 
 function patch {
     ifile="${1}.in"
-    ofile=$1
-    if [ "_$2" != "_" ]; then
+    ofile="$1"
+    if [[ "_$2" != "_" ]]; then
         echo "$1 -> $2"
         ofile=$2
     fi
     cp $ifile $ofile
-    strs=`cat $ifile  | grep -o "##str[0-9]*##" | sed "s/#//g"`
+    strs=$(cat $ifile  | grep -o "##str[0-9]*##" | sed "s/#//g")
     for s in $strs; do
         echo "$s = ${!s}"
-        sed -i "s%##$s##%${!s}%g" $ofile
+        sedi "s%##$s##%${!s}%g" $ofile
     done
 }
 
 function reroot {
-    if [ "_$1" != "_$2" ]; then
-        cp $1 $2 -R
+    if [[ "_$1" != "_$2" ]]; then
+        cp -r $1 $2
     fi
 }
 
 function patch_of {
-    brand=$1
+    brand="$1"
     strset="en-uk"
-    if [ ! -f $brand/core0/us/res/strings/$strset ]; then
-        echo "KO 50942 Unknown set ${strset}."
+    if [[ ! -f $brand/core0/us/res/strings/$strset ]]; then
+        >&2 echo "KO 50942 Unknown set ${strset}."
         exit 1
     fi
-
     . $brand/core0/us/res/strings/$strset
     . $brand/core0/us/res/strings/${strset}.ovr
     cp core1/snippet/makefile_distr $brand/
-    #cp core1/snippet/install_r2r $brand/
-    #chmod +x $brand/install_r2r
     echo "$brand/makefile_distr"
 }
 
@@ -240,14 +244,14 @@ function make_build_job {
         return;
     fi
     if [[ ! -d  $brands/$brand ]]; then
-        echo "KO 76095 brand spec not found at $brands/$brand"
+        >&2 echo "KO 76095 brand spec not found at $brands/$brand"
         exit 1
     fi
     rm -rf rep
     echo "cloning: git clone -b $branch --single-branch $gitrep rep"
     git clone -b $branch --single-branch $gitrep rep
     if [[ $? -ne 0 ]]; then
-        echo "KO 68594 Aborted."
+        >&2 echo "KO 68594 Aborted."
         exit 1
     fi
     pushd rep > /dev/null
@@ -257,7 +261,7 @@ function make_build_job {
         pushd core0/us/srctool > /dev/null
             make
             if [[ $? -ne 0 ]]; then
-                echo "KO 44665"
+                >&2 echo "KO 44665"
                 exit 1
             fi
         popd > /dev/null
@@ -265,7 +269,7 @@ function make_build_job {
         pushd core0/us > /dev/null
             ../../srctool --dir -a $brands/$brand/source_code_header .
             if [[ $? -ne 0 ]]; then
-                echo "KO 71180 patch_src failed"
+                >&2 echo "KO 71180 patch_src failed"
                 exit 1
             fi
         popd > /dev/null
@@ -273,7 +277,7 @@ function make_build_job {
         pushd core1 > /dev/null
             ../srctool --dir -a $brands/$brand/source_code_header .
             if [[ $? -ne 0 ]]; then
-                echo "KO 79681 patch_src failed"
+                >&2 echo "KO 79681 patch_src failed"
                 exit 1
             fi
         popd > /dev/null
@@ -315,8 +319,8 @@ function make_build_job {
                 echo "configuring core0. flags: $fgs"
     	        echo "bin/configure $fgs"
                 bin/configure $fgs
-                if [ $? -ne 0 ]; then
-                    echo "KO 20021 Configure failed."
+                if [[ $? -ne 0 ]]; then
+                    >&2 echo "KO 20021 Configure failed."
                     exit 1
                 fi
                 find . -type f -name "*.in" -delete
@@ -329,8 +333,8 @@ function make_build_job {
         popd > /dev/null
 
         strset="en-uk"
-        if [ ! -f $brand/core0/us/res/strings/$strset ]; then
-            echo "KO 60459 unknown set ${strset}."
+        if [[ ! -f $brand/core0/us/res/strings/$strset ]]; then
+            >&2 echo "KO 60459 unknown set ${strset}."
             exit 1
         fi
         set -a
@@ -344,18 +348,15 @@ function make_build_job {
             bin/configure $fgs
             find . -name "*.in" -delete
             rm bin/configure
-            #echo "adding headers to r2r sources "
-            #bin/patch_src -a ../core0/us/doc/header || exit 1 
         popd > /dev/null
         if [[ $str76 -eq 1 ]]; then
             echo "licensing core2"
             pushd core2 > /dev/null
                 ../srctool --dir -a $brands/$brand/source_code_header .
                 if [[ $? -ne 0 ]]; then
-                    echo "KO 79682 patch_src failed"
+                    >&2 echo "KO 79682 patch_src failed"
                     exit 1
                 fi
-    #            bin/patch_src -a $brands/$brand/source_code_header || exit 1
             popd > /dev/null
             cp core2 $brand/ -R
             pushd "$brand/core2/us/trader" > /dev/null
@@ -365,8 +366,6 @@ function make_build_job {
                 bin/configure $fgs
                 find . -name "*.in" -delete
                 rm bin/configure
-                #echo "adding headers to r2r sources "
-                #bin/patch_src -a ../core0/us/doc/header || exit 1 
             popd > /dev/null
         fi
         rm srctool
@@ -378,13 +377,20 @@ function make_build_job {
 
 function make_brands {
     dryrun=$1
-    if [ "_$conf" == "_all" ]; then
-        for b in $abrands; do
-            make_build_job $b $dryrun
-        done
-    else
-        make_build_job $conf $dryrun
+    if [[ "_$conf" == "_all" ]]; then
+        conf=${abrands}
     fi
+    for b in $conf; do
+        make_build_job "$b" $dryrun
+    done
+#exit 1
+#    if [[ "_$conf" == "_all" ]]; then
+#        for b in $abrands; do
+#            make_build_job $b $dryrun
+#        done
+#    else
+#        make_build_job $conf $dryrun
+#    fi
 }
 
 function make_brands0 {
@@ -419,7 +425,7 @@ function ec_sources {
     echo "git clone -q ${secp256k1_git}"
     git clone -q ${secp256k1_git}
     if [[ $? -ne 0 ]]; then
-        echo "KO 50445 Cannot clone ${secp256k1_git}."
+        >&2 echo "KO 50445 Cannot clone ${secp256k1_git}."
         exit 1
     fi        
     pushd secp256k1 > /dev/null
@@ -445,7 +451,7 @@ function fcgi_sources {
     echo "git clone -q ${fcgi_git} fastcgi++"
     git clone -q ${fcgi_git} fastcgi++
     if [[ $? -ne 0 ]]; then
-        echo "KO 50445 Cannot clone ${fcgi_git}."
+        >&2 echo "KO 50445 Cannot clone ${fcgi_git}."
         exit 1
     fi        
     pushd fastcgi++
@@ -457,11 +463,18 @@ function fcgi_sources {
 function make_build_jobs {
     branch=$1
     bjdir=$2
-    if [ -f .revs ]; then
+    if [[ -f .revs ]]; then
         src="DJ$devjob_id"
     else
         src="R"
     fi
+    mkdir -p $bjdir/lib/
+    cp ../core0/us/lib/shenv $bjdir/lib/
+    for a in ${cbs_archs}; do
+        var="symlink_${a}"
+        echo $var=\"${!var}\" >> $bjdir/lib/cbsenv
+    done 
+
     mkdir -p $bjdir/ec_src
     pushd "$bjdir"/ec_src > /dev/null
         ec_sources
@@ -526,45 +539,43 @@ function make_build_jobs {
             popd > /dev/null
 
             if [[ "_$hash" == "_" ]]; then
-                echo "KO 58798.1"
+                >&2 echo "KO 58798.1"
                 exit 1
             fi
             if [[ "_$src" == "_" ]]; then
-                echo "KO 58798.2"
+                >&2 echo "KO 58798.2"
                 exit 1
             fi
             if [[ "_$rephash" == "_" ]]; then
-                echo "KO 58798.3"
+                >&2 echo "KO 58798.3"
                 exit 1 
             fi
             if [[ "_$branch" == "_" ]]; then
-                echo "KO 58798.4"
+                >&2 echo "KO 58798.4"
                 exit 1 
             fi
             if [[ "_$debug" == "_" ]]; then
-                echo "KO 58798.5"
+                >&2 echo "KO 58798.5"
                 exit 1 
             fi
             if [[ "_$logs" == "_" ]]; then
-                echo "KO 58798.6"
+                >&2 echo "KO 58798.6"
                 exit 1 
             fi
             if [[ "_$counters" == "_" ]]; then
-                echo "KO 58798.7"
+                >&2 echo "KO 58798.7"
                 exit 1 
             fi
             if [[ "_$connlog" == "_" ]]; then
-                echo "KO 58798.8"
+                >&2 echo "KO 58798.8"
                 exit 1 
             fi
             if [[ "_$fcgi" == "_" ]]; then
-                echo "KO 58798.9"
+                >&2 echo "KO 58798.9"
                 exit 1 
             fi
             echo "vhash ${hash} <- ${src} ${rephash} ${branch} dbg-${debug} logs-${logs} counters-${counters} connlog-${connlog} fcgi-${fcgi}" >> ../build_hashes
-            
         popd >/dev/null
-        
     popd >/dev/null
 }
 
@@ -577,33 +588,45 @@ function move_to_distr {
         brand=`echo $(basename $(dirname $x))`
         echo "brand $brand"
         dist_src=0
+        dist_src_c2=0
         if [[ -f ./.cbs/config_${brand} ]]; then
             . ./.cbs/config_${brand}
         else
-            echo "KO 78869 Missing file ./.cbs/config_${brand}"
+            >&2 echo "KO 78869 Missing file ./.cbs/config_${brand}"
             exit 1
         fi
-        dstdir=$distr/$brand/src
-        mkdir -p ${dstdir}
-        mkdir -p ${dstdir}/core0
-        mkdir -p ${dstdir}/core1
-        echo "Static config"
-        cp ${srcdir}/core0/us/res/strings/en-uk ${dstdir}/core0/config
+        dstdir=$distr/$brand
+#        mkdir -p ${dstdir}
+#        mkdir -p ${dstdir}/core0
+#        mkdir -p ${dstdir}/core1
         if [[ $dist_src -eq 1 ]]; then
+            mkdir -p ${dstdir}/src/core0
+            echo "Static config"
+            cp ${srcdir}/core0/us/res/strings/en-uk ${dstdir}/src/core0/config
+
             echo "Copying core0 sources for brand $brand"
-            cp ${srcdir}/core0 ${dstdir}/ -R
+            cp -r ${srcdir}/core0/* ${dstdir}/src/core0/
+
+            mkdir -p ${dstdir}/src/core1
+            echo "Copying core1 sources for brand $brand"
+            cp -r ${srcdir}/core1/us ${dstdir}/src/core1/
+
+            if [[ $dist_src_c2 -eq 1 ]]; then
+                mkdir -p ${dstdir}/src/core2
+                echo "Copying core2 sources for brand $brand"
+                cp -r ${srcdir}/core2/us ${dstdir}/src/core2/
+            else
+                echo "Omiting core2 sources for brand $brand"
+            fi
         else
-            echo "Omiting core0 sources for brand $brand"
+            echo "Omiting sources for brand $brand"
         fi
-        echo "Copying core1 sources for brand $brand"
-        cp ${srcdir}/core1/us ${dstdir}/core1/ -R
-        cp ${srcdir}/core1/makefile ${dstdir}/core1/
     done
 }
 
 make_brands dryrun
 
-if [ "_$conf" == "_" ]; then
+if [[ "_$conf" == "_" ]]; then
     echo "yes?"
     read ans
 fi
diff --git a/core1/bin/15_make_deps b/core1/bin/15_make_deps
--- a/core1/bin/15_make_deps
+++ b/core1/bin/15_make_deps
@@ -25,6 +25,8 @@ echo "##################"
 echo "## 15_make_deps ##"
 echo "##################"
 
+. lib/shenv
+
 if [[ -f ./.cbs/config ]]; then
     . ./.cbs/config
 else
@@ -43,9 +45,9 @@ function help {
 }
 
 ignore_cache=0
-while [ true ]; do
+while [[ true ]]; do
     opt=$1
-    echo "read opt=$opt"
+    #echo "read opt=$opt"
     shift
     if [ "_$opt" == "_--local-build" ]; then
         echo " [local build]"
@@ -74,7 +76,7 @@ if [ "_$build_jobs" == "_" ]; then
 fi
 echo "using dir $build_jobs"
 
-let fcgi=`cat build_jobs/build_hashes  | grep "^vhash " | sed "s/.*fcgi-\([01]\).*/\1/"`
+let fcgi=`cat ${build_jobs}/build_hashes | grep "^vhash " | sed "s/.*fcgi-\([01]\).*/\1/"`
 if [[ "_$fcgi" == "_" ]]; then
     let fcgi=0
 fi
@@ -87,8 +89,6 @@ function do_arch {
     echo "do_arch $host $arch"
     echo "uploading build_jobs"
     rsync -r -e "$ssh -p$sshport" --progress --delete -a ${build_jobs}.tzst $host:/root/
-
-    #rsync -r -e "$ssh -p$sshport" --progress --delete -a snippet/build_job_make $host:/root/
     echo "building $arch"
     cat << EOF > /tmp/make.sh
 #!/bin/bash
@@ -100,7 +100,7 @@ pushd /root >/dev/null;
         ./make.sh deps
         r=\$?
         if [[ \$r -ne 0 ]]; then
-            echo "make ended with errors"
+            echo "make ended with errors. \$r"
             exit \$r
         fi
     popd >/dev/null
@@ -140,15 +140,15 @@ function wait_done {
             port=${!vport}
             #echo "querying host $host"
             s=`$ssh -p$port $host "head -n1 foo.err"`
-            if [ "_$s" != "_" ]; then
-                echo "?????????Abnormal finding: $s"
-                echo "$ssh -p$port $host \"killall make; killall build_job_make; killall cc1plus\""
+            if [[ "_$s" != "_" ]]; then
+                echo "$ssh -p$port $host \"killall make; killall make.sh; killall cc1plus\""
                 $ssh -p$port $host "killall make; killall build_job_make; killall cc1plus"
                 echo "Complete cerr file: $ssh -p16671 $host \"cat foo.err\""
                 echo "1st Error: $s"
                 exit 1
                 break
             fi
+
             s=`$ssh -p$port $host "tail -n1 foo.out"`
             echo "$arch @$host: $s"
             if [[ $s = ===DONE===* ]]; then
@@ -169,15 +169,30 @@ function wait_done {
 function move_to_distr {
     mkdir -p $distr
     mv deps/x86_64/include deps/
-    rm -r deps/armv7l/include
+    for a in `echo $archs`; do
+        rm -rf deps/$a/include
+    done
     mv deps $distr/
-    [[ ! -d distr/deps/include ]] && echo "KO 68857 missing deps include" && exit 1
-    [[ ! -d distr/deps/x86_64 ]] && echo "KO 68858 missing deps x86_64" && exit 1
+    if [[ ! -d distr/deps/include ]]; then
+        echo "KO 68857 missing deps include"
+        exit 1
+    fi
     if [[ $local_build -eq 0 ]]; then
-        [[ ! -d distr/deps/armv7l ]] && echo "KO 68859 missing deps armv7l" && exit 1
+        for a in ${cbs_archs}; do
+            if [[ ! -d distr/deps/$a ]]; then
+                 echo "KO 68858 missing deps $a"
+                 exit 1
+            fi
+            rm -rf deps/$a/include
+        done
         pushd "$distr/deps" >/dev/null
-            ln -s armv7l armv6l  #raspi Zero
-            ln -s armv7l aarch64  #arm64bits
+            for a in ${cbs_archs}; do
+                var="symlink_$a"
+                sla=${!var}
+                for x in `echo $sla`; do
+                    ln -s $a $x
+                done
+            done
         popd >/dev/null
     fi
     cp snippet/install_deps distr/deps/
@@ -200,7 +215,7 @@ if [[ $ignore_cache -eq 0 ]]; then
         echo "source bin/15_make_deps [cached]" >> $distr/build_hashes
         exit 0
     else
-        echo "deps not found in cache."
+        echo "deps not found in cache (.cache/$cache_file)."
     fi
 else
     echo "Ignoring cache"
@@ -213,13 +228,11 @@ if [[ $local_build -eq 1 ]]; then
     arch=`uname -m`
     vhost=host_$arch
     vport=port_ssh_$arch
-#    !vhost="localhost"
-#    !vport="16671"
     host_x86_64="localhost"
     port_ssh_x86_64="16671"
     wait_done "$arch "
 else
-    wait_done "x86_64 armv7l "
+    wait_done "${cbs_archs}"
 fi
 
 move_to_distr
@@ -235,3 +248,4 @@ echo "Finished"
 find $distr -type f
 
 exit 0
+
diff --git a/core1/bin/20_make_core b/core1/bin/20_make_core
--- a/core1/bin/20_make_core
+++ b/core1/bin/20_make_core
@@ -25,6 +25,8 @@ echo "##################"
 echo "## 20_make_core ##"
 echo "##################"
 
+. lib/shenv
+
 if [[ -f .cbs/config ]]; then
     . .cbs/config
 else
@@ -36,7 +38,7 @@ function help {
     echo " --local-build    "
 }
 
-grootkey=`ush show_groot_key`
+grootkey=$(ush show_groot_key)
 ssh="ssh -i $grootkey "
 hash=""
 branch=""
@@ -69,10 +71,10 @@ function do_arch {
     host=$1
     sshport=$2
     echo "do_arch $host:$sshport"
-    arch=`$ssh -p$sshport $host "uname -m"`
-    echo "do_arch $host $arch"
+    arch=$($ssh -p${sshport} ${host} "uname -m")
+    echo "do_arch ${host} ${arch}"
     echo "uploading $build_jobs"
-    rsync -r -e "$ssh -p$sshport" --progress --delete -a ${build_jobs}.tzst $host:/root/
+    rsync -r -e "$ssh -p${sshport}" --progress --delete -a ${build_jobs}.tzst ${host}:/root/
     if [[ ! -d distr/deps ]]; then
         echo "need to build deps first."
         exit 1
@@ -91,15 +93,21 @@ pushd /root >/dev/null;
     tar -I zstd -xf distr_deps.tzst
     pushd distr/deps >/dev/null
         ./install_deps
-        if [[ $? -ne 0 ]]; then
-            echo "Errors occurred installing deps."
-            exit 1
+        r=\$?
+        if [[ \$r -ne 0 ]]; then
+            echo "Errors occurred installing deps." >&2
+            exit \$r
         fi
     popd >/dev/null
     rm -rf ${build_jobs}
     tar -I zstd -xf $build_jobs.tzst
     pushd $build_jobs >/dev/null
        ./make.sh core
+        r=\$?
+        if [[ \$r -ne 0 ]]; then
+            echo "Errors occurred building core." >&2
+            exit \$r
+        fi
     popd >/dev/null
     rm -rf core
     mv $build_jobs core
@@ -129,7 +137,7 @@ function wait_done {
     progdbfile=progress_20_db
     if [[ -f $progdbfile ]]; then
         prog="0"
-        progtot=`cat $progdbfile | wc -l`
+        progtot=$(cat $progdbfile | wc -l)
         perc="0"
     fi
     while [[ true ]]; do
@@ -137,13 +145,13 @@ function wait_done {
         if [[ "_$archs" == "_" ]]; then
             break
         fi
-        for arch in $archs; do
+        for arch in ${archs}; do
             vhost=host_$arch
             vport=port_ssh_$arch
             host=${!vhost}
             port=${!vport}
             #echo "querying $arch host $host"
-            s=`$ssh -p$port $host "cat foo.err | grep -v \"^distcc\" | head -n1"`
+            s=$($ssh -p$port $host "cat foo.err | grep -v \"^distcc\" | head -n1")
             if [[ "_$s" != "_" ]]; then
                 $ssh -p$port $host "killall make; killall make.sh; killall cc1plus"
                 echo "Complete cerr file: $ssh -p$port $host \"cat foo.err\""
@@ -151,21 +159,21 @@ function wait_done {
                 exit 1
                 break
             fi
-            s=`$ssh -p$port $host "tail -n1 foo.out"`
+            s=$($ssh -p$port $host "tail -n1 foo.out")
             if [[ -f $progdbfile ]]; then
-                obj=`echo $s | awk '{print $NF}'`
-                nprog=`cat $progdbfile | grep "^[ ]*${prog}.*" -A100000 | grep $obj | awk '{print $1}' | head -n1`
+                obj=$(echo $s | awk '{print $NF}')
+                nprog=$(cat $progdbfile | grep "^[ ]*${prog}.*" -A100000 | grep $obj | awk '{print $1}' | head -n1)
                 if [[ $? -eq 0 ]]; then
                     if [[ "_$nprog" != "_" ]]; then
                         prog=$nprog
-                        perc=`echo "${prog} * 100/${progtot}" | bc`
+                        perc=$(echo "${prog} * 100/${progtot}" | bc)
                     fi
                 fi 
             fi
             echo "$arch @$host [$prog/$progtot $perc%]: $s"
             if [[ $s = ===DONE===* ]]; then
-                arch=`$ssh -p$port $host "uname -m"`
-                archs=`echo "$archs" | sed "s#$arch ##"`
+                arch=$($ssh -p$port $host "uname -m")
+                archs=$(echo "$archs" | sed "s#$arch ##")
                 echo "fetching $arch binaries"
                 rsync -r -e "$ssh  -p$port" --progress  -a $host:/root/core.tzst ./
                 tar -I zstd -xf core.tzst
@@ -181,7 +189,6 @@ function wait_done {
 }
 
 function do_arch_localhost {
-    arch=`uname -m`
     cp $build_jobs/* core/ -R
     pushd core > /dev/null
         echo "Compiling core..."
@@ -195,100 +202,162 @@ function do_arch_localhost {
 }
 
 function move_to_distr {
+    #input example produced by core1/snippet/build_job_make:
+    #core/
+    #./build_hashes_x86_64
     mkdir -p $distr
     c1hash=""
 
-    for file in `find core -type f -name "build_hashes_*"`; do
-        arch=`echo $file | sed "s/.*build_hashes_\(.*\)/\1/"`
-        echo "source bin/20_make_core arch $arch" >> $distr/build_hashes
+    for file in $(find core -type f -name "build_hashes_*"); do
+        remote_arch=$(echo $file | sed "s/.*build_hashes_\(.*\)/\1/")
+        echo "source bin/20_make_core arch ${remote_arch}" >> $distr/build_hashes
         cat $file >> $distr/build_hashes
         rm $file
     done
 
+    #./alpha-53/7-bd7f2d/tft/x86_64-dev.tgz
     #num architectures
-    num=`find core -name "*-dev.tgz" | tr '/' ' ' | awk '{print $NF}' | sort | uniq | wc -l`
+    let num=$(find core -name "*-dev.tgz" | tr '/' ' ' | awk '{print $NF}' | sort | uniq | wc -l)
     if [[ $local_build -eq 0 ]]; then
-        if [[ $num -ne 4 ]]; then
-            echo "KO 85529 Expected 4 archs dev" >&2
-            find core -name "*-dev.tgz" 1>&2
-            echo "num=$num expected=3" 1>&2
+        let expected_archs_build=$(echo "${cbs_archs}" | wc -w)
+        echo "expected_archs_build: ${expected_archs_build}"
+        let expected_archs=${expected_archs_build};
+        echo "expected_archs: ${expected_archs}"
+        echo "cbs_archs=${cbs_archs}"
+        for a in ${cbs_archs}; do
+            echo "a=${a}"
+            var="symlink_$a"
+            sla=${!var};
+            echo "    sla=${sla}"
+            let expected_archs+=$(echo "${sla}" | wc -w);
+            echo "    expected_archs->${expected_archs}"
+        done
+        echo "expected_archs: ${expected_archs}"
+        if [[ $num -ne ${expected_archs} ]]; then
+            >&2 echo "KO 85529 Expected ${expected_archs} archs dev"
+            >&2 find core -name "*-dev.tgz"
+            >&2 echo "num=$num expected=${expected_archs}"
             exit 1
         fi
     else
         if [[ $num -ne 1 ]]; then
-            echo "KO 85539 Expected 1 dev archs" >&2
-            find core -name "*.tgz" 1>&2
-            echo "num=$num expected=1" 1>&2
+            >&2 echo "KO 85539 Expected 1 dev archs"
+            >&2 find core -name "*.tgz"
+            >&2 echo "num=$num expected=1"
             exit 1
         fi
     fi
 
-    for file in `find core -name "*-dev.tgz"`; do
-        c1hash=`echo $file | tr '/' ' ' | awk '{ print $(NF-2) }'`
+    #./alpha-53/7-bd7f2d/tft/x86_64.tgz
+    #./alpha-53/7-bd7f2d/tft/x86_64-dev.tgz
+    #./alpha-53/7-bd7f2d/tft/makefile_distr
+
+    for file in $(find core -name "*-dev.tgz"); do
+        c1hash=$(echo $file | tr '/' ' ' | awk '{ print $(NF-2) }')
         break
     done
     echo "c1hash=$c1hash"
 
-    for file in `find core -name "*.tgz"`; do
-        us=`echo $file | tr '/' ' ' | awk '{ print $(NF-1) }'`
+    for file in $(find core -name "*.tgz"); do
+        us=$(echo $file | tr '/' ' ' | awk '{ print $(NF-1) }')
         mkdir -p $distr/${us}/core
         mv $file $distr/${us}/core/
         echo "$file -> $distr/${us}/core/"
     done
 
-    for file in `find core -type f -name "makefile_distr"`; do
-        us=`echo $file | tr '/' ' ' | awk '{ print $(NF-1) }'`
+    for file in $(find core -type f -name "makefile_distr"); do
+        us=$(echo $file | tr '/' ' ' | awk '{ print $(NF-1) }')
         mkdir -p $distr/${us}/core
         mv $file $distr/${us}/core/makefile
         echo "$file -> $distr/${us}/core/makefile"
     done
 
-    #for file in `find core -type f -name "*_setup_debian"`; do
-    #    us=`echo $file | tr '/' ' ' | awk '{ print $(NF-2) }'`
-    #    mkdir -p $distr/${us}/bootstrap
-    #    mv $file $distr/${us}/bootstrap/
-    #    rmdir $(dirname $file)
-    #    echo "$file -> $distr/${us}/bootstrap/${us}_setup_debian"
-    #done
+    #./alpha-53/7-bd7f2d/tft/brand_sha256sum
 
-    for file in `find core -type f -name "brand_sha256sum"`; do
-        us=`echo $file | tr '/' ' ' | awk '{ print $(NF-1) }'`
-        hash=`echo $file | tr '/' ' ' | awk '{ print $(NF-2) }'`
-        branch=`echo $file | tr '/' ' ' | awk '{ print $(NF-3) }'`
+    for file in $(find core -type f -name "brand_sha256sum"); do
+        us=$(echo $file | tr '/' ' ' | awk '{ print $(NF-1) }')
+        hash=$(echo $file | tr '/' ' ' | awk '{ print $(NF-2) }')
+        branch=$(echo $file | tr '/' ' ' | awk '{ print $(NF-3) }')
     	dst="$distr/${us}/core_${branch}_${hash}_src_sha256sums"
         mv $file $dst
         rmdir $(dirname $file)
         echo "$file -> $dst"
     done
 
-    for file in `find core -type f -name "apply_blob"`; do
-        us=`echo $file | tr '/' ' ' | awk '{ print $(NF-1) }'`
+    #./alpha-53/7-bd7f2d/tft/apply_blob
+
+    for file in $(find core -type f -name "apply_blob"); do
+        us=$(echo $file | tr '/' ' ' | awk '{ print $(NF-1) }')
         mkdir -p $distr/${us}/bin
         mv $file $distr/${us}/bin/
         echo "$file -> $distr/${us}/bin/"
     done
 
-    for file in `find core -type f -name "install_blob"`; do
-        us=`echo $file | tr '/' ' ' | awk '{ print $(NF-1) }'`
+    #./alpha-53/7-bd7f2d/tft/install_blob
+
+    for file in $(find core -type f -name "install_blob"); do
+        us=$(echo $file | tr '/' ' ' | awk '{ print $(NF-1) }')
         mkdir -p $distr/${us}/bin
         cp $file $distr/${us}/bin/
         echo "$file -> $distr/${us}/bin/"
     done
 
-    for coredir in `find $distr -type d -name "core"`; do
+    for coredir in $(find $distr -type d -name "core"); do
         dir=$(dirname $coredir)
         pushd "$dir"
             v="${branch}_$c1hash"
-            tar -I zstd -cf core_${v}.tar.zst core
-            rm core -rf
             echo $v > version
         popd
     done
+
+}
+
+function move_to_distr_r2r {
+    mkdir -p distr
+
+    #./alpha-53/7-bd7f2d/tft/r2r/x86_64/libworkflow-consumer.so
+    #./alpha-53/7-bd7f2d/tft/r2r/x86_64/libtrader-pat2slt-slt.so
+
+    for file in $(find core -type f -name "*.so"); do
+        us=$(echo $file | tr '/' ' ' | awk '{ print $(NF-3) }')
+        arch=$(echo $file | tr '/' ' ' | awk '{ print $(NF-1) }')
+        mkdir -p distr/${us}/lib/${arch}/r2r
+        mv $file distr/${us}/lib/${arch}/r2r/
+        echo "$file -> distr/${us}/lib/${arch}/r2r/"
+    done
+    pushd "distr/${us}/lib" >/dev/null
+        for a in $archs; do
+            var="symlink_$a"
+            sla=${!var}
+            for x in $sla; do
+                ln -s $a $x
+            done
+        done
+    popd >/dev/null
+    
+    #./alpha-53/7-bd7f2d/tft/r2r/home/bid2ask/ask/ico.png
+    #./alpha-53/7-bd7f2d/tft/r2r/home/bid2ask/ask/name
+    echo "Aditional r2r files"
+    for h in $(find core -type d -name "home"); do
+        echo "found $h"
+        mkdir -p distr/${us}/r2r/home
+        mv $h/* distr/${us}/r2r/home/
+    done
+
+    #./alpha-53/7-bd7f2d/tft/r2r/html
+    for h in $(find core -type d -name "html"); do
+        echo "found $h"
+        mkdir -p distr/${us}/r2r/html
+        mv $h/* distr/${us}/r2r/html/
+    done
+
+    #./alpha-53/7-bd7f2d/sha256sum
+    find core -name "sha256sum" -delete
 }
 
 pushd $build_jobs > /dev/null
-for f in `find . -type d -name "core0"`; do
-    branch=`echo $f | tr '/' ' ' | awk '{print $2}'`
+for f in $(find . -type d -name "core0"); do
+    branch=$(echo $f | tr '/' ' ' | awk '{print $2}')
     break
 done
 popd > /dev/null
@@ -306,10 +375,11 @@ if [[ $local_build -eq 1 ]]; then
     port_ssh_x86_64="16671"
     wait_done "x86_64 "
 else
-    wait_done "x86_64 armv7l "
+    wait_done "${cbs_archs}"
 fi
 
 move_to_distr
+move_to_distr_r2r
 
 echo "Ignored files:"
 find core -type f
@@ -320,3 +390,4 @@ echo "Finished"
 find $distr -type f
 
 exit 0
+
diff --git a/core1/bin/70_make_blobs b/core1/bin/70_make_blobs
--- a/core1/bin/70_make_blobs
+++ b/core1/bin/70_make_blobs
@@ -62,65 +62,74 @@ if [[ "_$flagscode" != "_" ]]; then
     flagscode="_${flagscode}"
 fi
 
+shenvfile=`realpath ../core0/us/lib/shenv`
+
 for branddir in `find distr -maxdepth 1 -mindepth 1 -type d`; do
+    brand=$(basename $branddir)
+    if [[ ! -f distr/$brand/version ]]; then
+        continue
+    fi
     echo ""
     echo "branddir=$branddir"
-    brand=$(basename $branddir)
     echo "brand=$brand"
     echo "hash=$hash"
-    echo "find $branddir -name \"core_*_$hash.tar.zst\""
-    branch=`find $branddir -name "core_*_$hash.tar.zst" | sed "s#.*core_\(.*\)_${hash}.tar.zst#\1#"`
-    if [[ -f distr/$brand/bin/apply_blob ]]; then #any expected-to-be-there file
-        echo "brand $brand branch $branch hash $hash branddir $branddir"
-        pushd distr > /dev/null
-            blobdir="${brand}_${branch}_${hash}${flagscode}"
-            echo "blobdir=$blobdir"
-            rm -rf $blobdir
-            mkdir -p $blobdir
-            cp $brand/* $blobdir/ -R
-            if [[ ! -f $blobdir/doc/release_notes ]]; then
-                echo "KO 87945 missing release_notes."
-                exit 1
-            fi
-            if [[ ! -f $blobdir/doc/strset ]]; then
-                echo "KO 87946 missing strset file."
-                exit 1
-            fi
-            cp deps $blobdir/ -R
-            echo "Excluding OS Image"
-            rm -rf $blobdir/raspberry_pi
-            cp $blobdir/bin/install_blob /tmp/${brand}_install_blob
-            pushd $blobdir/wallet-cli > /dev/null
-                apk=`find . -type f -name "*.apk"`
-                echo "apk=$apk"
-                if [[ "_$apk" != "_" ]]; then
-                    apkhash=`us-wallet digest $apk`
-                    if [[ $? -ne 0 ]]; then
-                        echo "KO 89782 need a working us-wallet program."
-                        exit 1
-                    fi
-                    ln -s "$apk" blob.apk
-                    echo "$apkhash" > blobhash 
-                    echo "apkhash=$apkhash"
-                fi
-            popd > /dev/null 
-            echo "writing blobmake.sh"
-            pwd
-            ls ../snippet/blob_make.sh
-            echo "cp ../snippet/blob_make.sh $blobdir/make.sh"
-            cp ../snippet/blob_make.sh $blobdir/make.sh
-            chmod +x $blobdir/make.sh           
-            tar -I zstd -cf $blobdir.tzst $blobdir
-            mv $blobdir.tzst ../blobs/
-            mv /tmp/${brand}_install_blob ../blobs/
-            . $blobdir/doc/strset
-            rm -rf $blobdir
-            #write partid
-            echo "$str40" > ../blobs/${blobdir}.tzst.partid
-	    popd > /dev/null
-    else
-        echo "skipped distr/$brand"
+    #echo "find $branddir -name \"core_*_$hash.tar.zst\""
+    branch=`cat distr/${brand}/version | sed "s~\(.*\)_\(.*\)~\1~"`
+    hash2=`cat distr/${brand}/version | sed "s~\(.*\)_\(.*\)~\2~"`
+    if [[ "_$hash2" != "_$hash" ]]; then
+        echo "KO 71123 Inconsistent hashes."
+        exit 1
     fi
+#    branch=`find $branddir -name "core_*_$hash.tar.zst" | sed "s#.*core_\(.*\)_${hash}.tar.zst#\1#"`
+    echo "brand $brand branch $branch hash $hash branddir $branddir"
+    pushd distr > /dev/null
+        blobdir="${brand}_${branch}_${hash}${flagscode}"
+        echo "blobdir=$blobdir"
+        rm -rf $blobdir
+        mkdir -p $blobdir
+        cp -r $brand/* $blobdir/
+        if [[ ! -f $blobdir/doc/release_notes ]]; then
+            echo "KO 87945 missing release_notes."
+            exit 1
+        fi
+        if [[ ! -f $blobdir/doc/strset ]]; then
+            echo "KO 87946 missing strset file."
+            exit 1
+        fi
+        mkdir -p $blobdir/lib
+        cp $shenvfile $blobdir/lib/
+        cp -r deps $blobdir/
+        echo "Excluding OS Image"
+        rm -rf $blobdir/raspberry_pi
+        cp $blobdir/bin/install_blob /tmp/${brand}_install_blob
+        pushd $blobdir/wallet-cli > /dev/null
+            apk=`find . -type f -name "*.apk"`
+            echo "apk=$apk"
+            if [[ "_$apk" != "_" ]]; then
+                apkhash=`us-wallet digest $apk`
+                if [[ $? -ne 0 ]]; then
+                    echo "KO 89782 need a working us-wallet program."
+                    exit 1
+                fi
+                ln -s "$apk" blob.apk
+                echo "$apkhash" > blobhash 
+                echo "apkhash=$apkhash"
+            fi
+        popd > /dev/null 
+        echo "writing blobmake.sh"
+#        pwd
+        ls ../snippet/blob_make.sh
+        echo "cp ../snippet/blob_make.sh $blobdir/make.sh"
+        cp ../snippet/blob_make.sh $blobdir/make.sh
+        chmod +x $blobdir/make.sh           
+        tar -I zstd -cf $blobdir.tzst $blobdir
+        mv $blobdir.tzst ../blobs/
+        mv /tmp/${brand}_install_blob ../blobs/
+        . $blobdir/doc/strset
+        rm -rf $blobdir
+        #write partid
+        echo "$str40" > ../blobs/${blobdir}.tzst.partid
+    popd > /dev/null
 done
 
 echo ""
diff --git a/core1/bin/99_postupgrade b/core1/bin/99_postupgrade
--- a/core1/bin/99_postupgrade
+++ b/core1/bin/99_postupgrade
@@ -22,6 +22,18 @@
 #===----------------------------------------------------------------------------
 #===-
 
+function help {
+    cat << EOF
+$0 <cmd>
+Commands:
+  run                                               postupgrade entry point
+  post_upgrade <brand>                              can be called between network upgrades
+  forkfromhere                                      only run this segment
+  update_static_cfg                                 only run this segment
+  relnotes                                          only run this segment
+EOF
+}
+
 function update_devjobs {
     brand=$1
     echo "=================== github brand $brand branch $branch"
@@ -141,44 +153,71 @@ function post_upgrade {
     done
 }
 
-function save_release_history {
-    let bn=`echo $branch | sed "s~alpha-\([0-9]*\)~\1~"`
+let create_new_branch=1
+
+function forkfromhere {
+    let bn=`echo $branch | sed "s~alpha-\([0-9]*\).*~\1~"`
     let bn=$bn+1
     proposed="alpha-$bn"
-    echo -n "enter new branch (or y for $proposed): "
-    newb=""
-    read newb
-    if [[ "_$newb" == "_y" ]]; then
-        newb=$proposed
-    fi
-    echo "New branch: $newb"
-    echo "y/ctrl-c"
-    read a
+    newb=$proposed
+    while [[ true ]]; do
+        echo -n "enter new or existing branch (or 'y' for ${newb})"
+        read newb
+        if [[ "_$newb" == "_" ]]; then
+            continue
+        fi
+        if [[ "_$newb" == "_y" ]]; then
+            newb=$proposed
+        fi
+        git branch | grep "$newb" > /dev/null
+        if [[ $? -eq 0 ]]; then
+            echo -n "Branch $newb already exists. Use it? (n will ask for a branch again) [y/n]: "
+            read ans
+            if [[ "_$ans" == "_y" ]]; then
+                let create_new_branch=0
+                break
+            fi
+        else
+            echo "Creating new branch $newb."
+            let create_new_branch=1
+            break
+        fi
+    done
 
+    curgit=`git branch | grep "^\* " | awk '{ print $2}'`
+    if [[ "_$curgit" == "_$branch" ]]; then
+        if [[ $create_new_branch -eq 0 ]]; then
+            echo "checking out branch $newb"
+            git checkout $newb
+            if [[ $? -ne 0 ]]; then
+                echo "KO 88979 git gave errors"
+                exit 1
+            fi
+            git pull
+        else
+            echo "creating new git branch $newb"
+            git checkout -b $newb
+        fi
+    fi
+
+    echo "updating branch in cbs/config"
+    sed -i "s/^branch=\"$branch\"/branch=\"$newb\"/" .cbs/config
+
+}
+function save_release_history {
+    if [[ ! -d distr ]]; then
+        echo "WARNING: distr not found - skipping save to history"
+        return
+    fi
     echo "archiving distr files"
     dir=release_history/$branch
     mkdir -p $dir
     mv distr $dir/
     mv blobs $dir/
-
     echo "Saved release history at $dir"
+}
 
-    curgit=`git branch | grep "^\* " | awk '{ print $2}'`
-    if [[ "_$curgit" == "_$branch" ]]; then
-        echo "creating new git branch $newb"
-        git checkout -b $newb
-    fi
-
-    echo "updating new branch in cbs/config"
-    sed -i "s/^branch=\"$branch\"/branch=\"$newb\"/" .cbs/config
-
-    . release_history/$branch/distr/us/src/core0/us/vcs_git_env
-    echo "======================================="
-    echo "info for core1/doc/release_notes:"
-    echo -n "${core0_branch}_${core0_hashname} ${core0_build_date} "
-    cat release_history/$branch/distr/build_hashes | grep vhash | sort | uniq
-    echo "======================================="
-
+function update_static_cfg {
     echo "Updating mainnet API service numbers:"
     pushd ../core0/us/api > /dev/null
         cp generated/gov/svc_v`cat generated/gov/svc_cur_v` netsvc/gov
@@ -194,7 +233,16 @@ function save_release_history {
     sed -i "s~^str99=\([0-9]*\)\(.*\)~str99=${moco}\2~" ../core0/us/res/strings/en-uk
 
     echo " * Increased the monolitic deployments counter str99 in core0/us/res/strings/en-uk."
-    echo "Please commit the newly created branch $nreb with these changes (netsvc. release notes)"
+}
+
+#TODO: REPEATED core0 dir !!!!!!!!!!! release_history/alpha-53/distr/us/src/core0/core0/us
+function relnotes {
+    . release_history/$branch/distr/us/src/core0/us/vcs_git_env
+    echo "======================================="
+    echo "info for core1/doc/release_notes:"
+    echo -n "${core0_branch}_${core0_hashname} ${core0_build_date} "
+    cat release_history/$branch/distr/build_hashes | grep vhash | sort | uniq
+    echo "======================================="
 }
 
 function postupgrade_entry_point {
@@ -203,7 +251,7 @@ function postupgrade_entry_point {
         exit 1
     fi
     let ne=`cat distr/build_hashes | grep "$branch" | wc -l`
-    if [[ $ne -ne 5 ]]; then  #arch
+    if [[ $ne -ne 3 ]]; then  #arch
         echo "KO 43398 expecting 5 entries containing $branch in distr/build_hashes"
         exit 1
     fi
@@ -211,7 +259,7 @@ function postupgrade_entry_point {
         echo "KO 40398 blobs doesn't exists"
         exit 1
     fi
-    let ne=`ls blobs -1 | grep "$branch" | wc -l`
+    let ne=`ls blobs -1 | grep ".tzst.partid" | grep "$branch" | wc -l`
     let ene=`ls ${brands}/ -1 | wc -l`
     if [[ $ne -ne $ene ]]; then
         echo "KO 43398 expecting $ene blobs containing $branch in blobs/"
@@ -224,6 +272,16 @@ function postupgrade_entry_point {
 
     post_upgrade
     save_release_history
+    forkfromhere
+    update_static_cfg
+    relnotes
+
+
+    if [[ $create_new_branch -eq 0 ]]; then
+        echo "Please commit the newly created branch $nreb with these changes (netsvc. release notes)"
+    else
+        echo "Please commit the branch $nreb with these changes (netsvc. release notes)"
+    fi
 
     echo "==============================================="
 
@@ -232,15 +290,6 @@ function postupgrade_entry_point {
 
     exit $ecode
 
-}
-
-function help {
-    cat << EOF
-$0 <cmd>
-Commands:
-  run                                               postupgrade entry point
-  post_upgrade <brand>                              can be called between network upgrades
-EOF
 }
 
 . .cbs/config
@@ -258,6 +307,16 @@ if [[ "_$cmd" == "_post_upgrade" ]]; then
     post_upgrade0 $brand
     exit 1
 fi
+if [[ "_$cmd" == "_forkfromhere" ]]; then
+    forkfromhere
+    exit $?
+fi
+if [[ "_$cmd" == "_update_static_cfg" ]]; then
+    update_static_cfg
+    exit $?
+fi
+
 
 help
 exit 1
+
diff --git a/core1/bin/cbs b/core1/bin/cbs
--- a/core1/bin/cbs
+++ b/core1/bin/cbs
@@ -26,28 +26,30 @@ echo "## Continuous Build Script ##"
 echo "#############################"
 
 if [[ ! -f ./.cbs/config ]]; then
-    echo "KO 15502 missing .cbs/config"
+    >&2 echo "KO 15502 missing .cbs/config"
     exit 1
 fi
 . ./.cbs/config
+. lib/shenv
 
 function help {
     cat << EOF
-$0 [-b] [--local-build] [--flags <flags10>] [--brand <brand|all] <cmd>
---yes              Don't ask questions, assume yes.
---stop-on-blobs
-clear_ccache
-run
-
-*stop <job>
+$0 [-b] [--local-build] [--flags <flags10>] [--brand <brand|all]* <cmd>
+options:
+    --yes              Don't ask questions, assume yes.
+    --stop-on-blobs
+commands:
+    clear_ccache
+    run
+    stop <job>
 EOF
     exit 0
 }
 
-ley yes=0
+let yes=0
 let bg=0
 let local_build=0
-brand=all
+brand=""
 flags10=""
 while [[ true ]]; do
     opt=$1
@@ -61,8 +63,8 @@ while [[ true ]]; do
         let local_build=1
         continue
     elif [[ "_$opt" == "_--brand" ]]; then
-        brand=$1
-        echo "brand $brand"
+        brand="$brand $1"
+        echo "added brand $brand"
         shift
         continue
     elif [[ "_$opt" == "_--flags" ]]; then
@@ -92,27 +94,20 @@ function run_cbs_init {
     flags10="$flags10 --branch $branch -o build_jobs_distr"
     flags15=""
     flags20=""
-    flags35=""
     if [[ $local_build -eq 1 ]]; then
-        echo "Creating single-arch blobs on this local machine. arch=`uname -m`"
+        echo "Creating single-arch blobs on this local machine. arch=$arch"
         flags15="${flags15} --local-build"
         flags20="${flags20} --local-build"
-        flags35="${flags35} --local-build"
     fi
-    echo "brand=$brand"
+    if [[ "_$brand" == "_" ]]; then
+        brand="all"
+    fi
+    echo "brands=$brand"
     echo "branch=$branch"
     echo "flags10(src)=$flags10"
     echo "flags15(deps)=$flags15"
     echo "flags20(core)=$flags20"
-    echo "flags35(r2r)=$flags35"
     echo "flags_compile_job=$flags_compile_job"
-    echo "Make sure you have your signing password ready."
-    echo "Sure? yes or CTRL-C"
-    if [[ $yes -eq 1 ]]; then
-        echo "auto-answering yes"
-    else
-        read ryes
-    fi
 }
 
 sep="-------------------------------------------------------------------------------"
@@ -122,7 +117,7 @@ function run_cbs {
     date
     echo $sep
     echo "bin/10_make_build_jobs ${flags10} ${brand}"
-    bin/10_make_build_jobs ${flags10} $brand
+    bin/10_make_build_jobs ${flags10} "${brand}"
     if [[ $? -ne 0 ]]; then
         exit 1
     fi
@@ -144,18 +139,18 @@ function run_cbs {
     if [[ $? -ne 0 ]]; then
         exit 1
     fi
-    echo $sep
-    echo "bin/35_make_r2r_protocols ${flags35} build_jobs_distr"
-    bin/35_make_r2r_protocols ${flags35} build_jobs_distr
-    if [[ $? -ne 0 ]]; then
-        exit 1
-    fi
-    echo $sep
-    echo "bin/40_make_raspi_image"
-    bin/40_make_raspi_image
-    if [[ $? -ne 0 ]]; then
-        exit 1
-    fi
+#    echo $sep
+#    echo "bin/35_make_r2r_protocols ${flags35} build_jobs_distr"
+#    bin/35_make_r2r_protocols ${flags35} build_jobs_distr
+#    if [[ $? -ne 0 ]]; then
+#        exit 1
+#    fi
+#    echo $sep
+#    echo "bin/40_make_raspi_image"
+#    bin/40_make_raspi_image
+#    if [[ $? -ne 0 ]]; then
+#        exit 1
+#    fi
     echo $sep
     echo "bin/50_tokenized_files_and_sign build_jobs_distr"
     bin/50_tokenized_files_and_sign build_jobs_distr
@@ -180,11 +175,15 @@ function run_cbs {
     echo "Test blob ?"
     if [[ $yes -eq 1 ]]; then
         echo "auto-answering yes"
+        let test_blob=1
     else
         read ryes
+        if [[ "_$ryes" == "_yes" ]]; then
+            let test_blob=1
+        fi
     fi
     if [[ $test_blob -eq 1 ]]; then
-        bin/85_test_blob
+        bin/75_test_blob
     fi
 
     echo "deploy to distribution nodes (Brand Distribution End) ?"
@@ -255,7 +254,7 @@ function c3po19 {
     echo "brand: $brand"
     echo -n "remote seq: "
     $scp -P$port build_jobs_$prog.tzst $user@$host:/root
-    bgssh "buildlog_${host}" -p$port $user@$host 'set -e; cd /root; rm build_jobs_'$prog' -rf; tar -I zstd -xf build_jobs_'$prog'.tzst; cd build_jobs_'$prog'; ./make.sh r2r; cd $(dirname `find . -name install_r2r`); ./install_r2r; cd /root; rm /var/log/'$brand'/* -rf; systemctl restart '$brand'-wallet'
+    bgssh "buildlog_${host}" -p$port $user@$host 'set -e; cd /root; rm build_jobs_'$prog' -rf; tar -I zstd -xf build_jobs_'$prog'.tzst; cd build_jobs_'$prog'; ./make.sh r2r; cd $(dirname $(find . -name install_r2r)); ./install_r2r; cd /root; rm /var/log/'$brand'/* -rf; systemctl restart '$brand'-wallet'
     echo "/$prog"
 }
 
@@ -272,7 +271,7 @@ function c3po20 {
     echo "brand: $brand"
     echo -n "remote seq: "
     $scp -P$port build_jobs_$prog.tzst $user@$host:/root
-    bgssh "buildlog_${host}" -p$port $user@$host 'set -e; rm build_jobs_'$prog' -rf; tar -I zstd -xf build_jobs_'$prog'.tzst; cd build_jobs_'$prog'; ./make.sh core; pwd; cd $(dirname `find . -name makefile_distr`); pwd ; make -f makefile_distr install; echo "installed"; cd /root; rm build_jobs_'$prog' -r; tar -I zstd -xf build_jobs_'$prog'.tzst; cd build_jobs_'$prog'; ./make.sh r2r; cd $(dirname `find . -name install_r2r`); ./install_r2r; cd /root; rm /var/log/'$brand'/* -rf; systemctl restart '$brand'-gov; systemctl restart '$brand'-wallet'
+    bgssh "buildlog_${host}" -p$port $user@$host 'set -e; rm build_jobs_'$prog' -rf; tar -I zstd -xf build_jobs_'$prog'.tzst; cd build_jobs_'$prog'; ./make.sh core; pwd; cd $(dirname $(find . -name makefile_distr)); pwd ; make -f makefile_distr install; echo "installed"; cd /root; rm build_jobs_'$prog' -r; tar -I zstd -xf build_jobs_'$prog'.tzst; cd build_jobs_'$prog'; ./make.sh r2r; cd $(dirname $(find . -name install_r2r)); ./install_r2r; cd /root; rm /var/log/'$brand'/* -rf; systemctl restart '$brand'-gov; systemctl restart '$brand'-wallet'
     echo "/$prog"
 }
 
@@ -289,7 +288,7 @@ function c3po30 {
     echo "brand: $brand"
     echo -n "remote seq: "
     $scp -P$port build_jobs_$prog.tzst $user@$host:/root
-    bgssh "buildlog_${host}" -p$port $user@$host 'set -e; rm build_jobs_'$prog' -rf; tar -I zstd -xf build_jobs_'$prog'.tzst; cd build_jobs_'$prog'; ./make.sh core; pwd; cd $(dirname `find . -name makefile_distr`); pwd ; make -f makefile_distr install; cd /root; rm /var/log/'$brand'/* -rf; systemctl restart '$brand'-gov; systemctl restart '$brand'-wallet; echo "remote process ended"'
+    bgssh "buildlog_${host}" -p$port $user@$host 'set -e; rm build_jobs_'$prog' -rf; tar -I zstd -xf build_jobs_'$prog'.tzst; cd build_jobs_'$prog'; ./make.sh core; pwd; cd $(dirname $(find . -name makefile_distr)); pwd ; make -f makefile_distr install; cd /root; rm /var/log/'$brand'/* -rf; systemctl restart '$brand'-gov; systemctl restart '$brand'-wallet; echo "remote process ended"'
     echo "/$prog"
 }
 
@@ -303,8 +302,8 @@ function do_prog {
     echo "do_prog prog=$prog user=$user brand=$brand flags=$flags host=$host port=$port"
     echo "ok?"
     read x
-    if [ "_$host" == "_" ]; then
-        echo "KO 50499"
+    if [[ "_$host" == "_" ]]; then
+        >&2 echo "KO 50499 "
         exit 1
     fi
     echo "bin/10_make_build_jobs $flags -o build_jobs_$prog $branch $brand"
@@ -338,7 +337,7 @@ fi
 function clear_ccache_arch {
     host=$1
     sshport=$2
-    grootkey=`ush show_groot_key`
+    grootkey=$(ush show_groot_key)
     ssh="ssh -i $grootkey "
     echo "clear_ccache_arch $host:$sshport"
     $ssh -p$sshport $host "ccache -C"
@@ -347,8 +346,8 @@ function clear_ccache_arch {
 if [[ "_$cmd" == "_clear_ccache" ]]; then
     set -x
     ccache -C
-    archs="x86_64 armv7l "
-    for arch in $archs; do
+#    archs="x86_64 armv7l "
+    for arch in $cbs_archs; do
         vhost=host_$arch
         vport=port_ssh_$arch
         host=${!vhost}
@@ -372,7 +371,7 @@ if [[ "_$cmd" == "_android" ]]; then
     set +e
     echo "Invoking bin/50_tokenized_files_and_sign build_jobs_distr"
     bin/50_tokenized_files_and_sign build_jobs_android
-    apk=`find distr -type f -name "*.apk"`
+    apk=$(find distr -type f -name "*.apk")
     echo "$apk"
     echo "install?"
     read x
