temp patch for old devjob  resize images
downstream refs:
f20d83e 2375426 ca22bd9 f620344 043ec55 1273924 cadf8e2 dfc32ff fb0e5ba e9d09a2 6f66b21 8bad258 d3060fa bc4f214 5d136a6 04a42f1 d213cc3 1cac1c0 68aec12 e56b32d 1c4ac6b 423bb1b 7a1f3b6 2d3348a b2217b1 2680c10 ee5d5a6 eb06ff5 db45289 c6d1f90 829021a f90e6f4 2bf6529 05cff19 bc11576 abd8e1d 1736af9 b0a2eb5 536eaa0 a800e06 4885047 78c5990 d98ca86 4236a37 659cd03 2302918 b9a8b40 a8b70eb 70b8d2d 0400011 bd1d551 c6264e4 94a60a4 3f7d362 ead3d9d 28f003c f79c5c7 7cbb0b4 5bb4979 e328218 51dd74d e1f2091 2a3c636 1711fb2 1449cf2 20d27fe 363e5e8 20c86b1 9ab7cee 874bf66 6bc945b d04026e eb90efc 46f666a f1be68f 72d2590 a6ab96f d4d793e 8f2b9c8 fa24181 f0aac97 6090847 b418f82 131e6b4 6b0ae6d c7323a7 2dc1cae 7003382 69bc5f4 5095b27 cba4c4b 762739b 02bfac1 6058988 26439e6 3e3bed3 3177f4b 0a60f5b 4e4af74 877b0c4 9671c20 db3b70f 24e5bc3 9549e5f 450eb83 c6ad23f 94af4d5 7b8ba56 3054f5b 1f9b976 7bf8933 9d046ae d59f017 0fb9855 2dad740 e7a7c66 2e2fc88 0cf1856 9fdfbf1 36c0867 d8aa2f3 237d5a4 117cd74 e4201b5 452c42b db36533 f2f976f 061c015 e808397 9a15797 37ebc7b 0bbd0ec 6505337 6763dc4 8ff6f16 f2c66ca a8addb3 7bb0ba7 d951265 3ee1db1 cd546b8 0dd01d9 1991e71 437c68f 3c1c68a 8099e63 5ae3466 641823f 3d503bf 9cfad1f 4934ec5 f9a63c9 b3fe93c ba953bb eff4b6e 6d3763e e7d2a15 f979e31 a13dcca 1a3e2df ad2a07a e9e1ad5 228311d 17b93b4 f892e5e c50b741 93d598d e892c3a 5c8f983 4057dda 0986fd1 d584eec 5b539c5 b3ce44d 11855e5 c3bd55e 227b9c4 5f259e5 5278fd7 6981c27 76ee4fd 96f77e0 31b9893 170ecb2 f88e2bb 5051ea4

diff --git a/core0/us/bin/apply_blob.in b/core0/us/bin/apply_blob.in
--- a/core0/us/bin/apply_blob.in
+++ b/core0/us/bin/apply_blob.in
@@ -25,13 +25,23 @@
 
 prog=$0
 
+US="##str3##"
 GOVUSER="##str11##"
 ANDROID_BRANDID="##str56##"
+defaultr2r="##str77##"
 
 export USRHOME=/home/$GOVUSER
 
 function help {
-    echo "./$prog [--full-install] [--only-install-deps] [<jaildir>]"
+    echo "./$prog [--full-install] [--only-install-deps] [--jail <jaildir>] <command>"
+    echo "Commands are:"
+    echo "    install"
+    echo "    r2r_lib_list_installed"
+	echo "    r2r_lib_list_default                 "
+	echo "    r2r_lib_install <e.g. bid2ask-bid>    "
+	echo "    r2r_lib_uninstall <prot-rol>  "
+	echo "    r2r_lib_commit                       "
+    echo ""
     echo "default jaildir=\"\""
 }
 
@@ -39,13 +49,17 @@ full_install=1  #a29.18
 echo "This release requires a full install"
 let onlyinstalldeps=0
 
-while [ true ]; do
+while [[ true ]]; do
     opt=$1
     shift
-    if [ "_$opt" == "_--full-install" ]; then
+    if [[ "_$opt" == "_--full-install" ]]; then
         full_install=1
         continue
-    elif [ "_$opt" == "_--only-install-deps" ]; then
+    elif [[ "_$opt" == "_--jail" ]]; then
+        jaildir=$1
+        shift
+        continue
+    elif [[ "_$opt" == "_--only-install-deps" ]]; then
         let onlyinstalldeps=1
         continue
     elif [[ _$opt == _--* ]]; then
@@ -56,7 +70,11 @@ while [ true ]; do
     fi
 done
 
-JAILDIR=$opt
+cmd=$opt
+if [[ "_$cmd" == "_" ]]; then
+    cmd="install"
+fi
+JAILDIR=$jaildir
 
 if [[ "_$JAILDIR" != "_" ]]; then
     JAILDIR=`realpath $JAILDIR`
@@ -71,7 +89,6 @@ if [[ $EUID -ne 0 ]]; then
 fi
 
 tar="tar -I zstd"
-defaultr2r="bid2ask-bid"
 
 pkg=`pwd | sed "s~.*/\(.*\)~\1~"`
 blob_brand=`echo $pkg | sed -n "s#^\([^_]*\)_\([^_]*\)_\([^_]*\).*#\1#p"`
@@ -84,6 +101,7 @@ cat << EOF
     channel $ch
 EOF
 US=$blob_brand
+echo "US=$US"
 
 function init_jail {
     echo "init_jail"
@@ -92,9 +110,18 @@ function init_jail {
 function touch_defaults {
     dst=$1
     US=$2
+    mkdir -p ${JAILDIR}$dst
     for l in `echo $defaultr2r`; do
         touch ${JAILDIR}$dst/lib${US}trader-${l}.so
     done
+}
+
+function touch_lib {
+    dst=$1
+    lib=$2
+    mkdir -p ${JAILDIR}$dst
+    touch ${JAILDIR}$dst/lib${US}trader-${lib}.so
+    echo "touched file ${JAILDIR}$dst/lib${US}trader-${lib}.so"
 }
 
 function symlink_libdir {
@@ -137,56 +164,33 @@ if [[ $onlyinstalldeps -eq 1 ]]; then
     let install_core=0
 fi
 
-function do_upgrade {
-    US=$blob_brand
-    ch=`cat $JAILDIR/var/us_nets | grep " $blob_brand " | awk '{print $1}'`
-    r=$?
-    if [[ $r -ne 0 ]]; then
-        echo "KO 97752 brand $blob_brand is not installed. Run ./$prog --full-install $JAILDIR  "
-        exit 1
-    fi
-    if [ "_$ch" == "_" ]; then
-        echo "KO 97749 brand $blob_brand is not installed."
-        exit 1
-    fi
-    ushome="/home/$GOVUSER/.${US}"
-    if [ "_$ch" != "_0" ]; then
-        ushome="$ushome/$ch"
-    fi
-    whome="$ushome/wallet"
-    thome="$whome/trader"
+function do_upgrade_r2r {
+    thome=$1
     r2rdst="$thome/lib"
     mkdir -p $r2rdst
-
-    #-------------------deps (ec)
-    if [[ $install_deps -eq 1 ]]; then
-        echo "Installing deps (libsecp256k1, fastcgi++)"
-        pushd deps > /dev/null
-            ./install_deps ${JAILDIR}
-        popd > /dev/null
-    fi
-
     #-------------------R2R
     if [[ $install_r2r -eq 1 ]]; then
         echo "Installing R2R"
         if [ -d lib ]; then
+            pwd=`pwd`
             pushd lib > /dev/null
                 arch=`uname -m`
-                if [[ -d $arch/r2r ]]; then
-                    pushd $arch/r2r  > /dev/null
+                if [[ -d ${arch}/r2r ]]; then
+                    pushd ${arch}/r2r  > /dev/null
                         #upgrade name wallet->trader
-                        if [[ -d ${JAILDIR}$r2rdst ]]; then
-                            for f in `find ${JAILDIR}$r2rdst -name "*.so"`; do
-                                n=${f##*/}
-                                n2=`echo $n | sed "s/lib${US}wallet/lib${US}trader/"`
-                                if [[ "_$n2" != "_$n" ]]; then
-                                    mv ${JAILDIR}$r2rdst/$n ${JAILDIR}$r2rdst/$n2
-                                    echo "updated lib name ${JAILDIR}$r2rdst/$n -> ${JAILDIR}$r2rdst/$n2"
-                                fi
-                                echo "${JAILDIR}$r2rdst   --  $n  -- $arch"
-                            done
-                        fi
+                        #if [[ -d ${JAILDIR}$r2rdst ]]; then
+                        #    for f in `find ${JAILDIR}$r2rdst -name "*.so"`; do
+                        #        n=${f##*/}
+                        #        n2=`echo $n | sed "s/lib${US}wallet/lib${US}trader/"`
+                        #        if [[ "_$n2" != "_$n" ]]; then
+                        #            mv ${JAILDIR}$r2rdst/$n ${JAILDIR}$r2rdst/$n2
+                        #            echo "updated lib name ${JAILDIR}$r2rdst/$n -> ${JAILDIR}$r2rdst/$n2"
+                        #        fi
+                        #        echo "${JAILDIR}$r2rdst   --  $n  -- $arch"
+                        #    done
+                        #fi
                         touch_defaults $r2rdst $US
+
                         for f in `find . -name "*.tzst"`; do
                             $tar -xf $f
                         done
@@ -195,13 +199,43 @@ function do_upgrade {
                             for f in `find ${JAILDIR}$r2rdst -name "*.so"`; do
                                 n=${f##*/}
                                 echo "${JAILDIR}$r2rdst   --  $n"
-                                if [ -f $n ]; then
+                                if [[ -f $n ]]; then
                                     cp $n ${JAILDIR}$r2rdst
-                                    echo "Installed $n"
+                                    prot=`echo $n | sed "s#lib.*trader-\(.*\)-.*\.so#\1#"`
+                                    role=`echo $n | sed "s#lib.*trader-.*-\(.*\)\.so#\1#"`
+                                    echo "    Installed $n at ${JAILDIR}$r2rdst"
+                                    if [[ -d $pwd/r2r/home/$prot/$role ]]; then
+                                        mkdir -p ${thome}/$prot/$role
+                                        if [[ ! -f ${thome}/$prot/$role/name ]]; then
+                                            cp $pwd/r2r/home/$prot/$role/name ${thome}/$prot/$role/
+                                            echo "    updated ${thome}/$prot/$role/name"
+                                        else
+                                            echo "    ${thome}/$prot/$role/name already exists."
+                                        fi
+                                        if [[ ! -f ${thome}/$prot/$role/ico.png ]]; then
+                                            cp $pwd/r2r/home/$prot/$role/ico.png ${thome}/$prot/$role/
+                                            echo "    updated ${thome}/$prot/$role/ico.png"
+                                        else
+                                            echo "    ${thome}/$prot/$role/ico.png already exists."
+                                        fi
+                                    else
+                                        echo "    source r2r info dir $pwd/r2r/home/$prot/$role doesn't exists."
+                                    fi
+#                                    if [[ -d $pwd/r2r/html/$prot/$role ]]; then
+#                                        mkdir -p /$prot/$role
+#                                        if [[ ! -f ${thome}/$prot/$role/name ]]; then
+#                                            cp $pwd/r2r/home/$prot/$role/name ${thome}/$prot/$role/
+#                                        fi
+#                                        if [[ ! -f ${thome}/$prot/$role/ico.png ]]; then
+#                                            cp $pwd/r2r/home/$prot/$role/ico.png ${thome}/$prot/$role/
+#                                        fi
+#                                    fi
                                 else
                                     echo "Could not find $n in blob. Not updating this r2r lib."
                                 fi
                             done
+
+
                         fi
                     popd > /dev/null
                 fi
@@ -221,6 +255,30 @@ function do_upgrade {
             popd > /dev/null
         fi
     fi
+}
+
+function do_upgrade {
+    ch=`cat $JAILDIR/var/us_nets | grep " $blob_brand " | awk '{print $1}'`
+    r=$?
+    if [[ $r -ne 0 ]]; then
+        echo "KO 97712 brand $blob_brand is not installed. Run ./$prog --full-install $JAILDIR  "
+        exit 1
+    fi
+    if [ "_$ch" == "_" ]; then
+        echo "KO 97729 brand $blob_brand is not installed. ch=$ch"
+        exit 1
+    fi
+    ushome="/home/$GOVUSER/.${US}"
+    if [ "_$ch" != "_0" ]; then
+        ushome="$ushome/$ch"
+    fi
+    whome="$ushome/wallet"
+    thome="$whome/trader"
+    mkdir -p $thome
+
+    #-------------------R2R libs
+    do_upgrade_r2r $thome
+
     #-------------------Android APK
     if [[ $install_android_apk -eq 1 ]]; then
         echo "Installing android app"
@@ -250,12 +308,27 @@ function do_upgrade {
         $tar -xf core_${blob_branch}_${blob_hash}.tar.zst
         pushd core > /dev/null
             make JAILDIR="${JAILDIR}" install
+            if [[ $? -ne 0 ]]; then
+                echo "KO 30948 do_upgrade finishes with error." 
+                return 1
+            fi
         popd > /dev/null
     fi
     #-----------------------
+    echo "finished do_upgrade" 
+    return 0
 }
 
 function do_install {
+    #-------------------deps (ec)
+    if [[ $install_deps -eq 1 ]]; then
+        echo "Installing deps (libsecp256k1, fastcgi++)"
+        pushd deps > /dev/null
+            ./install_deps ${JAILDIR}
+        popd > /dev/null
+    fi
+
+    #-------------------core - system-base
     corepkg=`find . -type f -name "core*.zst"`
     $tar -xf $corepkg
     pushd core > /dev/null
@@ -268,18 +341,126 @@ if [[ "_${JAILDIR}" != "_" ]]; then
     init_jail
 fi
 
-if [[ $full_install -eq 0 ]]; then
-    if [[ ! -f $JAILDIR/etc/systemd/system/${US}-gov.service ]]; then
-        echo "essential files are missing. Doing full install."
-        full_install=1
+if [[ "_$cmd" == "_install" ]]; then
+    if [[ $full_install -eq 0 ]]; then
+        if [[ ! -f $JAILDIR/etc/systemd/system/${US}-gov.service ]]; then
+            echo "essential files are missing. Doing full install."
+            full_install=1
+        fi
     fi
+
+    if [[ $full_install -eq 1 ]]; then
+        do_install
+        if [[ $? -ne 0 ]]; then
+            echo "KO 50398 Install failed"
+            exit 1
+        fi
+    fi
+
+    do_upgrade
+    if [[ $? -ne 0 ]]; then
+        echo "KO 50399 Upgrade failed"
+        exit 1
+    fi
+    exit 0
 fi
 
-if [[ $full_install -eq 1 ]]; then
-    do_install
+if [[ "_$cmd" == "_r2r_lib_list_default" ]]; then
+    echo "libs installed by default:"
+    echo ${defaultr2r}
+    exit 0
 fi
 
-do_upgrade
+if [[ "_$cmd" == "_r2r_lib_install" ]]; then
+    echo "Installing R2R lib"
+    lib=$1
+    shift
+    arch=`uname -m`
+    #if [[ ! -f lib/$arch/r2r/lib${US}trader-${lib} ]]; then
+    #    echo "KO 76095 file lib/$arch/r2r/$lib not found."
+    #    exit 1
+    #fi
+    ch=`cat $JAILDIR/var/us_nets | grep " $US " | awk '{print $1}'`
+    r=$?
+    if [[ $r -ne 0 ]]; then
+        echo "KO 92752 brand $US is not installed."
+        exit 1
+    fi
+    if [ "_$ch" == "_" ]; then
+        echo "KO 92749 brand $US is not installed. ch=$ch"
+        exit 1
+    fi
+    ushome="/home/$GOVUSER/.${US}"
+    if [ "_$ch" != "_0" ]; then
+        ushome="$ushome/$ch"
+    fi
+    whome="$ushome/wallet"
+    thome="$whome/trader"
+    r2rdst="$thome/lib"
+    mkdir -p $r2rdst
+    touch_lib $r2rdst ${lib}
+    echo "commit is required to complete."
+    exit 0
+fi
 
-exit 0
+if [[ "_$cmd" == "_r2r_lib_uninstall" ]]; then
+    lib=$1
+    shift
+    echo "Uninstalling R2R lib $lib"
+    arch=`uname -m`
+    if [[ ! -f lib/$arch/r2r/$lib ]]; then
+        echo "KO 76095 file lib/$arch/r2r/$lib not found."
+        exit 1
+    fi
+    ch=`cat $JAILDIR/var/us_nets | grep " $US " | awk '{print $1}'`
+    r=$?
+    if [[ $r -ne 0 ]]; then
+        echo "KO 94752 brand $US is not installed."
+        exit 1
+    fi
+    if [ "_$ch" == "_" ]; then
+        echo "KO 94749 brand $US is not installed."
+        exit 1
+    fi
+    ushome="/home/$GOVUSER/.${US}"
+    if [ "_$ch" != "_0" ]; then
+        ushome="$ushome/$ch"
+    fi
+    whome="$ushome/wallet"
+    thome="$whome/trader"
+    r2rdst="$thome/lib"
+    echo "deleted file $r2rdst/lib${US}trader-${lib}.so"
+    rm -f $r2rdst/lib${US}trader-${lib}.so
+    echo "commit is required to complete."
+    exit 0
+fi
+
+if [[ "_$cmd" == "_r2r_lib_commit" ]]; then
+    ch=`cat $JAILDIR/var/us_nets | grep " $blob_brand " | awk '{print $1}'`
+    r=$?
+    if [[ $r -ne 0 ]]; then
+        echo "KO 97752 brand $blob_brand is not installed. Run ./$prog --full-install $JAILDIR  "
+        exit 1
+    fi
+    if [ "_$ch" == "_" ]; then
+        echo "KO 97749 brand $blob_brand is not installed."
+        exit 1
+    fi
+    ushome="/home/$GOVUSER/.${US}"
+    if [ "_$ch" != "_0" ]; then
+        ushome="$ushome/$ch"
+    fi
+    whome="$ushome/wallet"
+    thome="$whome/trader"
+
+    #-------------------R2R libs
+    do_upgrade_r2r $thome
+    echo "REQUIRED: systemctl restart ${US}-wallet"
+    exit 0
+fi
+
+help
+exit 1
+
+
 
diff --git a/core0/us/bin/install_blob.in b/core0/us/bin/install_blob.in
--- a/core0/us/bin/install_blob.in
+++ b/core0/us/bin/install_blob.in
@@ -24,12 +24,54 @@
 
 JAILDIR=""
 
+CHANNEL=0
+US=""
+BLOB_ADDR=""
+BLOB_ID=""
+GOVUSER=""
+UPSTREAM_URL=""
+SEEDS=""
+
+function cfg_vars0 {
+    STATIC_US="##str3##"
+    let STATIC_FCGI=##str45##
+
+    STATIC_CHANNEL=##str6##
+    STATIC_BLOB_ADDR="##str39##"
+    STATIC_BLOB_ID="##str40##"
+    STATIC_GOVUSER="##str11##"
+    STATIC_UPSTREAM_URL="##str65##"
+    STATIC_SEEDS="##str67##"
+    if [[ $append -eq 0 ]]; then
+        if [[ -f ${JAILDIR}/etc/$STATIC_US/config ]]; then
+            echo "Loading static config from ${JAILDIR}/etc/$STATIC_US/config"
+            . ${JAILDIR}/etc/$STATIC_US/config
+            STATIC_CHANNEL=$str6
+            STATIC_BLOB_ADDR="$str39"
+            STATIC_BLOB_ID="$str40"
+            STATIC_GOVUSER="$str11"
+            STATIC_UPSTREAM_URL="$str65"
+            STATIC_SEEDS="$str67"
+        fi
+    fi
+    CHANNEL=${STATIC_CHANNEL}
+    US=${STATIC_US}
+    BLOB_ADDR=${STATIC_BLOB_ADDR}
+    BLOB_ID=${STATIC_BLOB_ID}
+    GOVUSER=${STATIC_GOVUSER}
+    UPSTREAM_URL=${STATIC_UPSTREAM_URL}
+    SEEDS="${STATIC_SEEDS}"
+}
+
+cfg_vars0
+
 function do_help {
     echo "##str3## installation script."
     echo "./$prog [flags] [command]"
     echo ""
     echo "flags:"
     echo "  --blob <file>        Blob file is given manually. /var/${US}/installed_blob__pinned is created."
+    echo "  --rebrand            Replace the brand."
 #    echo "  --append             Give permission to append a new entry in /var/us_nets."
     echo "  --skip-seeds         In case the blob needs to be fetched, it is done trying only the BDE (brand distribution end),"
     echo "                           skipping going through a number of random nodes."
@@ -45,6 +87,7 @@ function do_help {
     echo "  install/{nothing}        Fetchs the latest blob and installs it."
     echo "  uninstall                removes the software from the system, leaving user data intact."
     echo "  bootstrap_home <homedir> Installs wallet-rpc for a new system user."
+    echo "  make                     Blob makefile."
     echo "  extract_r2r_sdk          Obtains the R2R SDK from the blob."
     echo "  extract_src              Obtains the source code."
     echo "  fetch                    fetch blob from nodes."
@@ -68,12 +111,15 @@ function do_help {
 
 blob=""
 let append=0
+let rebrand=0
 let skip_seeds=0
 jaildir=""
 let forcepublish=0
 let full_install=0
 let force=0
 let maxpeers=100
+cmdargs=""
+
 function parse_input {
     while [[ true ]]; do
         opt=$1
@@ -87,6 +133,9 @@ function parse_input {
             echo "Broken feature. Node can run only 1 brand 1 channel until it is fixed."
             exit 1
             let append=1
+            continue
+        elif [[ "_$opt" == "_--rebrand" ]]; then
+            let rebrand=1
             continue
         elif [[ "_$opt" == "_--skip-seeds" ]]; then
             let skip_seeds=1
@@ -114,7 +163,6 @@ function parse_input {
             let force=1
             continue
         elif [[ _$opt == _-* ]]; then
-            cfg_vars
             do_help
             echo "KO 86755 Invalid option $opt"
             exit 1
@@ -126,8 +174,68 @@ function parse_input {
     if [[ "_$cmd" == "_" ]]; then
         cmd="install"
     fi
+    cmdargs="$@"
     #echo "cmd=$cmd"
 }
+
+function cfg_vars {
+    if [[ $append -eq 0 ]]; then
+        if [[ -f /var/us_nets ]]; then
+            let n=`cat /var/us_nets | grep "^[0-9]* .*" | wc -l`
+            if [[ $n -gt 1 ]]; then
+                echo "Found more than one entry in /us/nets"
+                cat /var/us_nets | grep "^[0-9]* .*" | grep " ${US} " > /tmp/x918274
+                mv /tmp/x918274 /var/us_nets
+                let n=`cat /var/us_nets | grep "^[0-9]* .*" | wc -l`
+                if [[ $n -eq 1 ]]; then
+                    echo "KO 78674 Unexpected content in /var/us_nets"
+                    exit 1
+                fi
+            fi
+            CHANNEL=`cat /var/us_nets | grep "^[0-9]* .*" | awk {'print $1'}`
+            US=`cat /var/us_nets | grep "^[0-9]* .*" | awk {'print $2'}`
+            BLOB_ADDR=`cat /var/us_nets | grep "^[0-9]* .*" | awk {'print $3'}`
+            BLOB_ID=`cat /var/us_nets | grep "^[0-9]* .*" | awk {'print $4'}`
+            if [[ "_${US}" != "_${STATIC_US}" ]]; then
+                if [[ $rebrand -eq 1 ]]; then
+                    echo "rebranding. Aborted. TODO"
+                    exit 1
+                else
+                    UPSTREAM_URL=""
+                    SEEDS=""
+                fi
+            fi
+        fi
+        datadir=/home/${GOVUSER}/.${US}
+        if [[ "_$CHANNEL" != "_0" ]]; then
+            datadir=${datadir0}/$CHANNEL
+        fi
+        cat ${datadir}/gov/nodes.* 2>/dev/null > /tmp/x5833677
+        echo ${SEEDS} | xargs -n1 >> /tmp/x5833677
+        ns=`cat /tmp/x5833677 | wc -l`
+        SEEDS="`cat /tmp/x5833677 | sed 's/72$/80/' | sort | uniq  | grep -v '^$' | shuf | xargs`"
+        rm -f /tmp/x5833677
+        if [[ $maxpeers -gt 0 ]]; then
+            #echo "limit of $maxpeers seeds applied"
+            SEEDS="`echo "$SEEDS" | xargs -n1 | head -n$maxpeers | xargs`"
+        fi
+    else
+        echo "KO 69078 append is disabled."
+        exit 1
+    fi
+    cat << EOF
+    CHANNEL=${CHANNEL}
+    US=${US}
+    BLOB_ADDR=${BLOB_ADDR}
+    BLOB_ID=${BLOB_ID}
+    GOVUSER=${GOVUSER}
+    UPSTREAM_URL=${UPSTREAM_URL}
+    ${ns} SEEDS (limit $maxpeers)
+EOF
+
+}
+
+cfg_vars
 
 function set_jail0 {
     if [[ "_$jaildir" != "_" ]]; then
@@ -217,6 +325,61 @@ function do_extract_r2r_sdk {
     blob=`realpath $blob`
     extract_r2r_sdk_from_blob $blob
     exit 0
+}
+
+#    rm -rf tmp
+#    mkdir tmp
+#    pushd tmp > /dev/null
+#        $tar -xf ${blob_local_file}
+#        if [[ $r -ne 0 ]]; then
+#            echo "KO 76037"
+#            return 1
+#        fi
+#        dir=`find . -mindepth 1 -maxdepth 1 -type d`
+#        pushd $dir > /dev/null
+#            dname=$(basename `pwd`)
+#            bname=`echo $dname | tr '_' ' ' | awk '{ print $1 }'`
+#            if [[ "_$bname" != "_${US}" ]]; then
+#                echo "KO 43096 Blob brand $bname doesn't match ${US}. Aborting."
+#                return 1
+#            fi
+#            bin/apply_blob $opts ${JAILDIR}
+#            if [[ $r -ne 0 ]]; then
+#                echo "KO 65099"
+#                return 1
+#            fi
+#        popd > /dev/null
+#    popd > /dev/null
+#    rm -rf tmp
+
+function do_make {
+    rm -rf tmp
+    mkdir tmp
+    if [[ $? -ne 0 ]]; then
+        echo "KO 59423 directory tmp exists."
+        exit 1
+    fi
+    pushd tmp > /dev/null
+        tar -I zstd -xf ${blob_local_file}
+        dir=`ls -1`
+        pushd $dir > /dev/null
+            dname=$(basename `pwd`)
+            bname=`echo $dname | tr '_' ' ' | awk '{ print $1 }'`
+            if [[ "_$bname" != "_${US}" ]]; then
+                echo "KO 43096 Blob brand $bname doesn't match ${US}. Aborting."
+                return 1
+            fi
+            opts=""
+            if [[ "_${JAILDIR}" != "_" ]]; then
+                opts+="--jail ${JAILDIR} "
+            fi
+            echo "Invoking blob make.sh $opts $@"
+            ./make.sh $opts $@
+        popd > /dev/null
+        rm -rf $dir
+    popd > /dev/null
+    rm tmp -r
+    return 0
 }
 
 function do_scan {
@@ -371,100 +534,6 @@ function init_jail {
     fi
     find ${JAILDIR} -type f
 }
-
-CHANNEL=0
-US=""
-BLOB_ADDR=""
-BLOB_ID=""
-GOVUSER=""
-UPSTREAM_URL=""
-SEEDS=""
-
-function cfg_vars0 {
-    STATIC_US="##str3##"
-    let STATIC_FCGI=##str45##
-
-    STATIC_CHANNEL=##str6##
-    STATIC_BLOB_ADDR="##str39##"
-    STATIC_BLOB_ID="##str40##"
-    STATIC_GOVUSER="##str11##"
-    STATIC_UPSTREAM_URL="##str65##"
-    STATIC_SEEDS="##str67##"
-    if [[ $append -eq 0 ]]; then
-        if [[ -f ${JAILDIR}/etc/$STATIC_US/config ]]; then
-            echo "Loading static config from ${JAILDIR}/etc/$STATIC_US/config"
-            . ${JAILDIR}/etc/$STATIC_US/config
-            STATIC_CHANNEL=$str6
-            STATIC_BLOB_ADDR="$str39"
-            STATIC_BLOB_ID="$str40"
-            STATIC_GOVUSER="$str11"
-            STATIC_UPSTREAM_URL="$str65"
-            STATIC_SEEDS="$str67"
-        fi
-    fi
-    CHANNEL=${STATIC_CHANNEL}
-    US=${STATIC_US}
-    BLOB_ADDR=${STATIC_BLOB_ADDR}
-    BLOB_ID=${STATIC_BLOB_ID}
-    GOVUSER=${STATIC_GOVUSER}
-    UPSTREAM_URL=${STATIC_UPSTREAM_URL}
-    SEEDS="${STATIC_SEEDS}"
-}
-
-function cfg_vars {
-    cfg_vars0
-    if [[ $append -eq 0 ]]; then
-        if [[ -f /var/us_nets ]]; then
-            let n=`cat /var/us_nets | grep "^[0-9]* .*" | wc -l`
-            if [[ $n -gt 1 ]]; then
-                echo "Found more than one entry in /us/nets"
-                cat /var/us_nets | grep "^[0-9]* .*" | grep " ${US} " > /tmp/x918274
-                mv /tmp/x918274 /var/us_nets
-                let n=`cat /var/us_nets | grep "^[0-9]* .*" | wc -l`
-                if [[ $n -eq 1 ]]; then
-                    echo "KO 78674 Unexpected content in /var/us_nets"
-                    exit 1
-                fi
-            fi
-            CHANNEL=`cat /var/us_nets | grep "^[0-9]* .*" | awk {'print $1'}`
-            US=`cat /var/us_nets | grep "^[0-9]* .*" | awk {'print $2'}`
-            BLOB_ADDR=`cat /var/us_nets | grep "^[0-9]* .*" | awk {'print $3'}`
-            BLOB_ID=`cat /var/us_nets | grep "^[0-9]* .*" | awk {'print $4'}`
-            if [[ "_${US}" != "_${STATIC_US}" ]]; then
-                UPSTREAM_URL=""
-                SEEDS=""
-            fi
-        fi
-        datadir=/home/${GOVUSER}/.${US}
-        if [[ "_$CHANNEL" != "_0" ]]; then
-            datadir=${datadir0}/$CHANNEL
-        fi
-        cat ${datadir}/gov/nodes.* 2>/dev/null > /tmp/x5833677
-        echo ${SEEDS} | xargs -n1 >> /tmp/x5833677
-        ns=`cat /tmp/x5833677 | wc -l`
-        SEEDS="`cat /tmp/x5833677 | sed 's/72$/80/' | sort | uniq  | grep -v '^$' | shuf | xargs`"
-        rm -f /tmp/x5833677
-        if [[ $maxpeers -gt 0 ]]; then
-            #echo "limit of $maxpeers seeds applied"
-            SEEDS="`echo "$SEEDS" | xargs -n1 | head -n$maxpeers | xargs`"
-        fi
-    else
-        echo "KO 69078 append is disabled."
-        exit 1
-    fi
-    cat << EOF
-    CHANNEL=${CHANNEL}
-    US=${US}
-    BLOB_ADDR=${BLOB_ADDR}
-    BLOB_ID=${BLOB_ID}
-    GOVUSER=${GOVUSER}
-    UPSTREAM_URL=${UPSTREAM_URL}
-    ${ns} SEEDS (limit $maxpeers)
-EOF
-
-}
-
-cfg_vars
 
 if [[ "_${JAILDIR}" != "_" ]]; then
     init_jail ${US}
@@ -679,6 +748,23 @@ function read_addr_key {
 let pinned=0
 blob_local_file=""
 
+function resolve_blob_curblob {
+    if [[ "_$blob_local_file" != "_" ]]; then
+        return 0 #already resolved
+    fi
+    if [[ "_$blob" != "_" ]]; then
+        blob_local_file=`realpath $blob`
+        return 0
+    fi
+    if [[ ! -f ${JAILDIR}/home/$GOVUSER/downloads/blob/${US}/cur ]]; then
+        echo "KO 87025 cur blob not found at ${JAILDIR}/home/$GOVUSER/downloads/blob/${US}/cur"
+        exit 1
+    fi
+    blob_local_file=${JAILDIR}/home/$GOVUSER/downloads/blob/${US}/cur
+    blob_local_file=`realpath $blob_local_file`
+    return 0
+}
+
 function resolve_blob {
     echo "resolve blob"
     if [[ "_$blob_local_file" != "_" ]]; then
@@ -736,7 +822,9 @@ function resolve_blob {
     if [[ $ffs -eq 1 ]]; then
         echo "Trying to fetch the $US blob using the seed list."
         fetch_from_seeds $US
-        [[ $? -ne 0 ]] && return 1
+        if [[ $? -ne 0 ]]; then
+            return 1
+        fi
         fsroot=$(dirname "$blob")
         blob=$(basename "$blob")
         echo "fetched $US from seeds. fsroot=$fsroot blob=$blob"
@@ -762,28 +850,39 @@ function update {
         fi
     fi
     opts=""
-    [[ $full_install -eq 1 ]] && opts="$opts --full-install"
-    tar="tar -I zstd "
+    if [[ $full_install -eq 1 ]]; then
+        opts="$opts --full-install "
+    fi
+#    tar="tar -I zstd "
     echo "Installing $US blob ${blob_local_file} channel $CHANNEL"
     echo "opts=$opts"
-    rm -rf tmp
-    mkdir tmp
-    pushd tmp > /dev/null
-        $tar -xf ${blob_local_file}
-        [[ $r -ne 0 ]] && return 1
-        dir=`find . -mindepth 1 -maxdepth 1 -type d`
-        pushd $dir > /dev/null
-            dname=$(basename `pwd`)
-            bname=`echo $dname | tr '_' ' ' | awk '{ print $1 }'`
-            if [[ "_$bname" != "_${US}" ]]; then
-                echo "Blob brand $bname doesn't match ${US}. Aborting."
-                return 1
-            fi
-            bin/apply_blob $opts ${JAILDIR}
-            [[ $r -ne 0 ]] && return 1
-        popd > /dev/null
-    popd > /dev/null
-    rm -rf tmp
+
+    do_make apply_blob $opts 
+
+#    rm -rf tmp
+#    mkdir tmp
+#    pushd tmp > /dev/null
+#        $tar -xf ${blob_local_file}
+#        if [[ $r -ne 0 ]]; then
+#            echo "KO 76037"
+#            return 1
+#        fi
+#        dir=`find . -mindepth 1 -maxdepth 1 -type d`
+#        pushd $dir > /dev/null
+#            dname=$(basename `pwd`)
+#            bname=`echo $dname | tr '_' ' ' | awk '{ print $1 }'`
+#            if [[ "_$bname" != "_${US}" ]]; then
+#                echo "KO 43096 Blob brand $bname doesn't match ${US}. Aborting."
+#                return 1
+#            fi
+#            bin/apply_blob $opts ${JAILDIR}
+#            if [[ $r -ne 0 ]]; then
+#                echo "KO 65099"
+#                return 1
+#            fi
+#        popd > /dev/null
+#    popd > /dev/null
+#    rm -rf tmp
     echo "touched ${JAILDIR}/var/${US}/installed_blob"
     echo $blob > ${JAILDIR}/var/${US}/installed_blob
     if [[ $pinned -eq 1 ]]; then
@@ -836,8 +935,11 @@ function do_publish2 {
 function do_publish {
     read_addr_key
     resolve_blob
-    [[ $? -ne 0 ]] && return 1
+    if [[ $? -ne 0 ]]; then
+        return 1
+    fi
     do_publish2
+    return $?
 }
 
 function post_install {
@@ -849,7 +951,7 @@ function post_install {
     date
     echo "Installed $US blob $blob at ${JAILDIR}/"
     echo ""
-    echo "systemctl restart ${US}-wallet" >> ${JAILDIR}/tmp/post-install_blob
+    #echo "systemctl restart ${US}-wallet" >> ${JAILDIR}/tmp/post-install_blob
     fetch_from_seeds_cleanup
     date
     if [[ -f ${JAILDIR}/var/${US}/installed_blob__pinned ]]; then
@@ -867,21 +969,22 @@ function post_install {
         echo "Executing post-install"
         cat /tmp/post-install_blob
         /tmp/post-install_blob
+        rm /tmp/post-install_blob
     fi
     exit 0    #unreachable when invoked from gov ch 0
 }
 
 function cleanup_oldstuff {
     echo "clean up deprecated files"
-    rm -f ${JAILDIR}/etc/apt/sources.list.d/us.list
-    rm -f ${JAILDIR}/etc/apt/sources.list.d/raspi.list
-    rm -f ${JAILDIR}/var/www/us_html/index.html
-    rm -f ${JAILDIR}/var/www/us_html/geonodes.jpg
-    rm -f ${JAILDIR}/var/www/us_html/us-c.png
-    rm -f ${JAILDIR}/var/www/us_anon/geonodes.jpg
-    rm -f ${JAILDIR}/var/www/us_anon/us-c.png
-    rm -f ${JAILDIR}/home/${GOVUSER}/.${US}/wallet/trader/lib${US}trader-pat*.so
-    chown root.root /home
+    #rm -f ${JAILDIR}/etc/apt/sources.list.d/us.list
+    #rm -f ${JAILDIR}/etc/apt/sources.list.d/raspi.list
+    #rm -f ${JAILDIR}/var/www/us_html/index.html
+    #rm -f ${JAILDIR}/var/www/us_html/geonodes.jpg
+    #rm -f ${JAILDIR}/var/www/us_html/us-c.png
+    #rm -f ${JAILDIR}/var/www/us_anon/geonodes.jpg
+    #rm -f ${JAILDIR}/var/www/us_anon/us-c.png
+    #rm -f ${JAILDIR}/home/${GOVUSER}/.${US}/wallet/trader/lib${US}trader-pat*.so
+    #chown root.root /home
 }
 
 function do_install {
@@ -900,40 +1003,35 @@ function do_install {
     read_addr_key
 
     resolve_blob
-    [[ $? -ne 0 ]] && return 1
-
-
+    if [[ $? -ne 0 ]]; then
+        echo "KO 76987"
+        return 1
+    fi
+    echo "update"
     update
-    [[ $? -ne 0 ]] && return 1
-    
+    if [[ $? -ne 0 ]]; then
+        echo "KO 76986"
+        return 1
+    fi    
+
+    echo "do_publish2"
     do_publish2
 
+    echo "post_install"
     post_install
+
     cleanup_oldstuff
     echo "FINISHED"
 }
 
 function do_install_core0_deps {
-    read_addr_key
-    resolve_blob
     if [[ $? -ne 0 ]]; then
         return 1
     fi
-    opts="--only-install-deps"
-    tar="tar -I zstd "
-    echo "Installing deps $US blob $blob"
-    rm -rf tmp
-    mkdir tmp
-    pushd tmp > /dev/null
-        $tar -xf ${blob_local_file}
-        dir=`find . -mindepth 1 -maxdepth 1 -type d`
-        pushd $dir > /dev/null
-            bin/apply_blob $opts ${JAILDIR}
-            [[ $? -ne 0 ]] && return 1
-        popd > /dev/null
-    popd > /dev/null
-    rm -rf tmp
-    return 0
+    opts="--only-install-deps "
+    echo "Installing deps $US blob $blob_local_file"
+    do_make apply_blob $opts
+    return $?            
 }
 
 function do_uninstall {
@@ -954,6 +1052,8 @@ function exec_cmd20 {
     if [[ "_$cmd" == "_install" ]]; then
         do_install
     elif [[ "_$cmd" == "_install_core0_deps" ]]; then
+        read_addr_key
+        resolve_blob
         do_install_core0_deps
     elif [[ "_$cmd" == "_uninstall" ]]; then
         do_uninstall
@@ -963,6 +1063,9 @@ function exec_cmd20 {
         do_bootstrap_home "$where"
     elif [[ "_$cmd" == "_extract_r2r_sdk" ]]; then
         do_extract_r2r_sdk
+    elif [[ "_$cmd" == "_make" ]]; then
+        resolve_blob_curblob
+        do_make $cmdargs
     elif [[ "_$cmd" == "_extract_src" ]]; then
         do_extract_src
     elif [[ "_$cmd" == "_resolve_blob" ]]; then
diff --git a/core1/bin/10_make_build_jobs b/core1/bin/10_make_build_jobs
--- a/core1/bin/10_make_build_jobs
+++ b/core1/bin/10_make_build_jobs
@@ -242,12 +242,29 @@ function make_build_job {
         rephash=`git rev-parse HEAD`
         echo "Licensing core0"
         echo "rephash $rephash"
+        pushd core0/us/srctool > /dev/null
+            make
+            if [[ $? -ne 0 ]]; then
+                echo "KO 44665"
+                exit 1
+            fi
+        popd > /dev/null
+        mv core0/us/srctool/srctool .
         pushd core0/us > /dev/null
-            bin/patch_src -a $brands/$brand/source_code_header || exit 1
+            ../../srctool --dir -a $brands/$brand/source_code_header .
+            if [[ $? -ne 0 ]]; then
+                echo "KO 71180 patch_src failed"
+                exit 1
+            fi
         popd > /dev/null
         echo "licensing core1"
         pushd core1 > /dev/null
-            bin/patch_src -a $brands/$brand/source_code_header || exit 1
+            ../srctool --dir -a $brands/$brand/source_code_header .
+            if [[ $? -ne 0 ]]; then
+                echo "KO 79681 patch_src failed"
+                exit 1
+            fi
+#            bin/patch_src -a $brands/$brand/source_code_header || exit 1
         popd > /dev/null
         pushd core0/us > /dev/null
             bin/apply_brand $brands/$brand $branch
@@ -319,6 +336,29 @@ function make_build_job {
             #echo "adding headers to r2r sources "
             #bin/patch_src -a ../core0/us/doc/header || exit 1 
         popd > /dev/null
+        if [[ $str76 -eq 1 ]]; then
+            echo "licensing core2"
+            pushd core2 > /dev/null
+                ../srctool --dir -a $brands/$brand/source_code_header .
+                if [[ $? -ne 0 ]]; then
+                    echo "KO 79682 patch_src failed"
+                    exit 1
+                fi
+    #            bin/patch_src -a $brands/$brand/source_code_header || exit 1
+            popd > /dev/null
+            cp core2 $brand/ -R
+            pushd "$brand/core2/us/trader" > /dev/null
+                echo "configuring core2 r2r"
+                fgs=""
+                echo "bin/configure $fgs"
+                bin/configure $fgs
+                find . -name "*.in" -delete
+                rm bin/configure
+                #echo "adding headers to r2r sources "
+                #bin/patch_src -a ../core0/us/doc/header || exit 1 
+            popd > /dev/null
+        fi
+        rm srctool
         mv $brand ..
         echo $brand >> /tmp/done_brands
     popd > /dev/null
diff --git a/core1/snippet/build_job_make b/core1/snippet/build_job_make
--- a/core1/snippet/build_job_make
+++ b/core1/snippet/build_job_make
@@ -166,10 +166,14 @@ EOF
                 if [ "_$arch" == "_armv7l" ]; then #Raspberry Pi Zero. Raspi 3 is backwards compatible.
                     ln -s armv7l armv6l
                     ln -s armv7l-dev armv6l-dev
-                    tar -czf armv7l.tgz armv7l armv6l
-                    tar -czf armv7l-dev.tgz armv7l-dev armv6l-dev
+                    ln -s armv7l aarch64
+                    ln -s armv7l-dev aarch64-dev
+                    tar -czf armv7l.tgz armv7l armv6l aarch64-dev
+                    tar -czf armv7l-dev.tgz armv7l-dev armv6l-dev aarch64-dev
                     ln -s armv7l.tgz armv6l.tgz
                     ln -s armv7l-dev.tgz armv6l-dev.tgz
+                    ln -s armv7l.tgz aarch64.tgz
+                    ln -s armv7l-dev.tgz aarch64-dev.tgz
                 else
                     tar -czf $arch.tgz $arch
                     tar -czf ${arch}-dev.tgz ${arch}-dev
@@ -186,14 +190,21 @@ EOF
                 rm -f armv6l-dev.tgz
                 mv core0/us/armv6l.tgz .
                 mv core0/us/armv6l-dev.tgz .
+
+                rm -f aarch64.tgz
+                rm -f aarch64-dev.tgz
+                mv core0/us/aarch64.tgz .
+                mv core0/us/aarch64-dev.tgz .
             fi
             rm -rf core0
             rm -rf core1
+            rm -rf core2
             echo -n "Produced files at "
             pwd
             ls $arch.tgz ${arch}-dev.tgz apply_blob install_blob
             if [ "_$arch" == "_armv7l" ]; then
                 ls armv6l.tgz armv6l-dev.tgz
+                ls aarch64.tgz aarch64-dev.tgz
             fi
         popd >/dev/null
     done
@@ -276,7 +287,6 @@ EOF
                 if [ $str33 -eq 1 ]; then
                     logstag="_logs"
                 fi
-                pwd
                 for f in `find . -maxdepth 1 -type f -name "*.so"`; do
                     echo $f
                     file=`echo $(basename $f)`
@@ -291,10 +301,78 @@ EOF
                 done
                 if [ "_$arch" == "_armv7l" ]; then
                     ln -s armv7l armv6l    #Raspberry Pi Zero. Raspi 3 is backwards compatible.
+                    ln -s armv7l aarch64   #arm64 bits
                 fi
+                echo "pwd: $pwd"
+                echo "Core 1: Protocols with home data:"
+                find r2r -type d -name "home" | sed "s#r2r/\(.*\)/home#\1#"
+                for homsubdir in `find r2r -type d -name "home" | sed "s#r2r/\(.*\)/home#\1#"`; do
+                    echo "mv r2r/${homsubdir}/home/* ${pwd}/r2r/home/${homsubdir}"
+                    mkdir -p ${pwd}/r2r/home/${homsubdir}
+                    mv r2r/${homsubdir}/home/* ${pwd}/r2r/home/${homsubdir}
+                done
+                echo "Protocols with html:"
+                find r2r -type d -name "html" | sed "s#r2r/\(.*\)/html#\1#"
+                for homsubdir in `find r2r -type d -name "html" | sed "s#r2r/\(.*\)/html#\1#"`; do
+                    echo "mv r2r/${homsubdir}/html/* ${pwd}/r2r/html/${homsubdir}"
+                    mkdir -p ${pwd}/r2r/html/${homsubdir}
+                    mv r2r/${homsubdir}/html/* ${pwd}/r2r/html/${homsubdir}
+                done
             popd >/dev/null
+            if [[ -d core2 ]]; then
+                c2="`realpath core2`"
+                pushd core2/us/trader > /dev/null
+                    echo "making distr for arch $arch brand $brand"
+                    dbgtag=""
+                    if [ $str29 -eq 1 ]; then
+                        dbgtag="_dbg"
+                    fi
+                    make -j$jobs CXX="${CXX}" INCC0="$incc0" LIBC0="$libc0" CORE1="$c1" CORE2="$c2"
+                    if [[ $? -ne 0 ]]; then
+                        echo "make failed"
+                        exit 1
+                    fi
+                    logstag=""
+                    if [ $str33 -eq 1 ]; then
+                        logstag="_logs"
+                    fi
+                    pwd
+                    for f in `find . -maxdepth 1 -type f -name "*.so"`; do
+                        echo $f
+                        file=`echo $(basename $f)`
+                        dir=`echo $(dirname $f)`
+                        echo "dir $dir file $file"
+                        pushd $dir >/dev/null
+                            prot=`echo $file | sed "s#lib\(.*\).so#\1#"`
+                            echo "prot=$prot"
+                            mkdir -p ${dstarchpwd}/r2r
+                            tar -I zstd -cf ${dstarchpwd}/r2r/lib${prot}${dbgtag}${logstag}_${branch}_${hash}.tzst $file
+                        popd >/dev/null
+                    done
+                    if [ "_$arch" == "_armv7l" ]; then
+                        ln -s armv7l armv6l    #Raspberry Pi Zero. Raspi 3 is backwards compatible.
+                        ln -s armv7l aarch64   #arm64 bits
+                    fi
+                    echo "pwd: $pwd"
+                    echo "Core 2: Protocols with home data:"
+                    find r2r -type d -name "home" | sed "s#r2r/\(.*\)/home#\1#"
+                    for homsubdir in `find r2r -type d -name "home" | sed "s#r2r/\(.*\)/home#\1#"`; do
+                        echo "mv r2r/${homsubdir}/home/* ${pwd}/r2r/home/${homsubdir}"
+                        mkdir -p ${pwd}/r2r/home/${homsubdir}
+                        mv r2r/${homsubdir}/home/* ${pwd}/r2r/home/${homsubdir}
+                    done
+                    echo "Protocols with html:"
+                    find r2r -type d -name "html" | sed "s#r2r/\(.*\)/html#\1#"
+                    for homsubdir in `find r2r -type d -name "html" | sed "s#r2r/\(.*\)/html#\1#"`; do
+                        echo "mv r2r/${homsubdir}/html/* ${pwd}/r2r/html/${homsubdir}"
+                        mkdir -p ${pwd}/r2r/html/${homsubdir}
+                        mv r2r/${homsubdir}/html/* ${pwd}/r2r/html/${homsubdir}
+                    done
+                popd >/dev/null
+            fi
             rm -rf core0
             rm -rf core1
+            rm -rf core2
             rm -rf usr
             echo "Produced files"
             find -type f -name "*.tzst"
@@ -408,6 +486,7 @@ EOF
             popd >/dev/null
             rm core0 -rf
             rm core1 -rf
+            rm core2 -rf
             rm -f makefile_distr
         popd >/dev/null
     done
