downstream refs: 04f806d 25decd5 eb73102 de89781 53e329f b43c6ba 393c395 f9df30d e3f9e1b e69a09d 0a33287 4b3fc18

diff --git a/core0/us/bin/gen_http_nodes b/core0/us/bin/gen_http_nodes
--- a/core0/us/bin/gen_http_nodes
+++ b/core0/us/bin/gen_http_nodes
@@ -21,20 +21,45 @@
 #===-
 #===----------------------------------------------------------------------------
 #===-
+#
+# find brand nodes in etc/nodes.distr0 
 
+function help {
+    echo "$0 scan [brand]"
+    echo "scans nodes in etc/nodes.distr0 in search of nodes with the http port open."
+    echo "If brand is specified, also search which ones run the given brand."
+    echo ""
+    echo "Update etc/nodes.distr0 first:"
+    echo "  scp -i <identiry> <any-node>:/home/gov/.us/gov/nodes.auto etc/nodes.distr0"
+}
+
+cmd=$1
+shift
 US=$1
+shift
+
+if [[ "_$cmd" != "_scan" ]]; then
+    help
+    echo "KO 86875 Invalid command."
+    exit 1
+fi
+
 nodes0=/tmp/nodes0
 if [[ ! -f $nodes0 ]]; then
+    echo "Finding all nodes with http port open"
     echo "" > $nodes0
     for h in `cat etc/nodes.distr0 | sed 's/72$/80/'`; do
-        wget -t 1 --quiet --connect-timeout=2 -O - $h > /dev/null
+        cmd="timeout 10 wget -t 1 --quiet --connect-timeout=2 -O - $h"
+        echo "Exec: $cmd"
+        eval $cmd > /dev/null
         let r=$?
         if [[ r -eq 0 ]]; then
             echo "$h"| tee -a $nodes0
         fi
     done
+else
+    echo "/tmp/nodes0 exist"
 fi
-
 
 if [[ "_$US" == "_" ]]; then
 	echo "file $nodes0:"
@@ -45,6 +70,8 @@ fi
 
 httpnodes="`cat $nodes0 | shuf | xargs` "
 echo "httpnodes=$httpnodes"
+file="/tmp/nodes_${US}"
+echo "" > $file
 while [[ true ]]; do
     httpnode=`echo $httpnodes | tr ' ' '\n' | head -n1`
     httpnodes=`echo "$httpnodes" | sed "s#$httpnode ##"`
@@ -52,7 +79,10 @@ while [[ true ]]; do
     if [ "_$httpnode" == "_" ]; then
         break
     fi
-    wget -q "${httpnode}/blob/${US}/curhash" -o curhash
+    cmd="timeout 10 wget -q --connect-timeout=2 -O curhash \"http://${httpnode}/downloads/blob/${US}/curhash\""
+    echo "Exec: $cmd"
+    rm -f curhash
+    eval $cmd
     let r=$?
     if [[ $r -ne 0 ]]; then
         echo "${httpnode} hasn't ${US}"
@@ -65,9 +95,14 @@ while [[ true ]]; do
     curhash=`cat curhash`
     rm curhash
     echo "======================================${httpnode} has ${US}"
-    echo "$httpnode"
+    echo "$httpnode" >> $file
 done
+rm -f curhash
+echo "${US} nodes:"
+echo -n "str67=\""
+v=`cat $file | sort | xargs`
+echo -n $v
+echo "\" #Seeds; Use bin/gen_http_nodes"
 
-
-
+exit 0
 
diff --git a/core1/bin/70_make_blobs b/core1/bin/70_make_blobs
--- a/core1/bin/70_make_blobs
+++ b/core1/bin/70_make_blobs
@@ -26,7 +26,7 @@ echo "## 70_make_blobs ##"
 echo "###################"
 
 numh=`cat distr/build_hashes | grep "^vhash " | awk '{print $2}' | sort | uniq | wc -l`
-if [ $numh -ne 1 ]; then
+if [[ $numh -ne 1 ]]; then
     echo "KO 6753 multiple hashes"
     exit 1
 fi
@@ -70,7 +70,7 @@ for branddir in `find distr -maxdepth 1 -mindepth 1 -type d`; do
     echo "hash=$hash"
     echo "find $branddir -name \"core_*_$hash.tar.zst\""
     branch=`find $branddir -name "core_*_$hash.tar.zst" | sed "s#.*core_\(.*\)_${hash}.tar.zst#\1#"`
-    if [ -f distr/$brand/bin/apply_blob ]; then
+    if [[ -f distr/$brand/bin/apply_blob ]]; then #any expected-to-be-there file
         echo "brand $brand branch $branch hash $hash branddir $branddir"
         pushd distr > /dev/null
             blobdir="${brand}_${branch}_${hash}${flagscode}"
@@ -78,6 +78,10 @@ for branddir in `find distr -maxdepth 1 -mindepth 1 -type d`; do
             rm -rf $blobdir
             mkdir -p $blobdir
             cp $brand/* $blobdir/ -R
+            if [[ ! -f $blobdir/release_notes ]]; then
+                echo "KO 87945 missing release_notes."
+                exit 1
+            fi
             cp deps $blobdir/ -R
             echo "Excluding OS Image"
             rm -rf $blobdir/raspberry_pi
@@ -87,6 +91,10 @@ for branddir in `find distr -maxdepth 1 -mindepth 1 -type d`; do
                 echo "apk=$apk"
                 if [[ "_$apk" != "_" ]]; then
                     apkhash=`us-wallet digest $apk`
+                    if [[ $? -ne 0 ]]; then
+                        echo "KO 89782 need a working us-wallet program."
+                        exit 1
+                    fi
                     ln -s "$apk" blob.apk
                     echo "$apkhash" > blobhash 
                     echo "apkhash=$apkhash"
@@ -97,7 +105,7 @@ for branddir in `find distr -maxdepth 1 -mindepth 1 -type d`; do
             ls ../snippet/blob_make.sh
             echo "cp ../snippet/blob_make.sh $blobdir/make.sh"
             cp ../snippet/blob_make.sh $blobdir/make.sh
-            chmod +x make.sh           
+            chmod +x $blobdir/make.sh           
             tar -I zstd -cf $blobdir.tzst $blobdir
             mv $blobdir.tzst ../blobs/
             mv /tmp/${brand}_install_blob ../blobs/
